/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "iTunesStoreUI-Structs.h"

@class NSString;

@interface SUComposeTextFieldConfiguration : XXUnknownSuperclass {
	UIEdgeInsets _borderInsets;
	BOOL _isRequired;
	NSString* _label;
	unsigned _maxLength;
	NSString* _placeholder;
	NSString* _value;
}
@property(assign, nonatomic) UIEdgeInsets borderInsets;
@property(assign, nonatomic, getter=isRequired) BOOL required;
@property(retain, nonatomic) NSString* label;
@property(assign, nonatomic) unsigned maxLength;
@property(retain, nonatomic) NSString* placeholder;
@property(retain, nonatomic) NSString* value;
-(void)dealloc;
@end

