/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "iTunesStoreUI-Structs.h"

@class SUWebView, DOMElement, UIImage;

@interface SUDOMElement : XXUnknownSuperclass {
	DOMElement* _element;
	UIImage* _image;
	SUWebView* _webView;
}
@property(readonly, assign, nonatomic) DOMElement* element;
@property(retain, nonatomic) SUWebView* webView;
@property(readonly, assign, nonatomic) UIImage* imageRepresentation;
@property(readonly, assign, nonatomic) CGRect frame;
-(id)initWithDOMElement:(id)domelement;
-(void)dealloc;
-(void)setProperty:(id)property value:(id)value;
@end

