/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "iTunesStoreUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSError, NSArray;

@interface SUInputSourceInputStream : XXUnknownSuperclass {
	/*function-pointer*/ void* _clientCallback;
	XXStruct_4pnlqD _clientContext;
	id _delegate;
	NSArray* _inputSources;
	int _inputSourceIndex;
	CFRunLoopRef _runLoop;
	CFRunLoopSourceRef _runLoopSource;
	BOOL _sentAtEndEvent;
	BOOL _sentOpenEvent;
	NSError* _streamError;
	unsigned _streamStatus;
}
@property(readonly, assign, nonatomic) NSArray* inputSources;
-(id)init;
-(id)initWithData:(id)data;
-(id)initWithFileAtPath:(id)path;
-(id)initWithInputSources:(id)inputSources;
-(id)initWithURL:(id)url;
-(void)dealloc;
-(void)close;
-(id)delegate;
-(BOOL)getBuffer:(char**)buffer length:(unsigned*)length;
-(BOOL)hasBytesAvailable;
-(void)open;
-(id)propertyForKey:(id)key;
-(int)read:(char*)read maxLength:(unsigned)length;
-(void)removeFromRunLoop:(id)runLoop forMode:(id)mode;
-(void)_scheduleInCFRunLoop:(CFRunLoopRef)cfrunLoop forMode:(CFStringRef)mode;
-(void)scheduleInRunLoop:(id)runLoop forMode:(id)mode;
-(BOOL)_setCFClientFlags:(unsigned long)flags callback:(/*function-pointer*/ void*)callback context:(XXStruct_4pnlqD*)context;
-(void)setDelegate:(id)delegate;
-(BOOL)setProperty:(id)property forKey:(id)key;
-(id)streamError;
-(unsigned)streamStatus;
-(void)_unscheduleFromCFRunLoop:(CFRunLoopRef)cfrunLoop forMode:(CFStringRef)mode;
-(void)_close;
-(id)_currentInputSource;
-(void)_scheduleCallback;
-(void)_setStreamError:(id)error;
-(void)_streamEventCallback;
@end

