/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SUItemValidator.h"

@class NSArray, NSMutableArray;

@interface SUItemValidator : XXUnknownSuperclass {
@private
	NSMutableArray* _collectionTests;
	NSMutableArray* _itemTests;
}
@property(readonly, assign, nonatomic) NSArray* validationTests;
-(void)dealloc;
-(void)addCollectionValidationTests:(id)tests;
-(void)addItemValidationTests:(id)tests;
-(void)removeValidationTest:(id)test;
-(BOOL)validateItems:(id)items error:(id*)error;
@end

@interface SUItemValidator (SUPurchaseValidation)
+(id)purchaseValidatorWithItems:(id)items;
@end

