/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "iTunesStoreUI-Structs.h"

@class NSURL, NSString;

@interface SUItemLink : XXUnknownSuperclass <NSCopying> {
@private
	int _linkTarget;
	int _linkType;
	NSString* _title;
	NSURL* _url;
}
@property(assign, nonatomic) int linkTarget;
@property(assign, nonatomic) int linkType;
@property(copy, nonatomic) NSString* title;
@property(retain, nonatomic) NSURL* URL;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
@end

