/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUItemValidatorTest.h"


@interface SUPurchaseValidatorTest : SUItemValidatorTest {
}
-(BOOL)validateItem:(id)item error:(id*)error;
-(BOOL)validateItems:(id)items error:(id*)error;
@end

