/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUContinuation.h"


@interface SUPurchaseContinuation : SUContinuation {
	id _purchase;
}
@property(readonly, assign, nonatomic) id purchase;
-(id)initWithPurchase:(id)purchase;
-(void)dealloc;
-(void)cancel;
-(void)start;
@end

