/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Protocol;

@interface SUResponderChainInvocationRecorder : XXUnknownSuperclass {
	Protocol* _protocol;
}
-(id)initWithTarget:(id)target protocol:(id)protocol;
-(id)_targetForSelector:(SEL)selector sender:(id)sender;
-(id)adjustedTargetForSelector:(SEL)selector;
-(void)invokeInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
@end

