/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "iTunesStoreUI-Structs.h"

@class NSString, SUViewController;

@interface SURotationController : XXUnknownSuperclass {
@private
	NSString* _rotationStyle;
	SUViewController* _viewController;
}
@property(copy, nonatomic) NSString* rotationStyle;
@property(assign, nonatomic) SUViewController* viewController;
-(id)init;
-(id)initWithViewController:(id)viewController;
-(void)dealloc;
-(void)animateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)finishRotationFromInterfaceOrientation:(int)interfaceOrientation;
-(void)prepareForDeferredRotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)prepareToRotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldDeferRotationToInterfaceOrientation:(int)interfaceOrientation;
-(CGRect)viewFrameForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)_orientationAffectsViewFrame;
@end

