/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUScriptViewControllerNativeObject.h"
#import "MPMediaPickerControllerDelegate.h"


@interface SUScriptMediaPickerNativeObject : SUScriptViewControllerNativeObject <MPMediaPickerControllerDelegate> {
}
-(void)destroyNativeObject;
-(void)setupNativeObject;
-(void)mediaPicker:(id)picker didPickMediaItems:(id)items;
-(void)mediaPickerDidCancel:(id)mediaPicker;
@end

