/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUScriptViewControllerNativeObject.h"


@interface SUScriptStorePageNativeObject : SUScriptViewControllerNativeObject {
}
-(void)setupNativeObject;
-(void)destroyNativeObject;
-(void)_webViewControllerNote:(id)note;
-(id)_eventNameForNote:(id)note;
@end

