/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import "SUStorePageViewController.h"
#import "iTunesStoreUI-Structs.h"


@interface SUSearchRootStorePageViewController : SUStorePageViewController {
}
-(void)reloadCancelBarButtonItem;
-(id)copyArchivableContext;
-(void)resetNavigationItem:(id)item;
-(void)setParentViewController:(id)controller;
-(void)setSection:(id)section;
-(void)viewWillDisappear:(BOOL)view;
@end

