/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "iTunesStoreUI-Structs.h"

@class NSString, UIFont, UIColor;

@interface SUTableHeaderView : XXUnknownSuperclass {
	UIColor* _bottomBorderColor;
	UIEdgeInsets _edgeInsets;
	int _index;
	UIColor* _shadowColor;
	int _style;
	NSString* _subtitle;
	UIFont* _subtitleFont;
	CGSize _subtitleSize;
	UIColor* _textColor;
	NSString* _title;
	UIFont* _titleFont;
	CGSize _titleSize;
}
@property(retain, nonatomic) UIColor* bottomBorderColor;
@property(assign, nonatomic) UIEdgeInsets edgeInsets;
@property(assign, nonatomic) int index;
@property(retain, nonatomic) UIColor* shadowColor;
@property(assign, nonatomic) int style;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) UIFont* subtitleFont;
@property(retain, nonatomic) UIColor* textColor;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) UIFont* titleFont;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)sizeToFit;
-(CGSize)_subtitleSize;
-(CGSize)_titleSize;
@end

