/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SUViewControllerFactory : XXUnknownSuperclass {
}
-(id)newDownloadsViewController;
-(id)newNetworkLockoutViewControllerWithSection:(id)section;
-(id)newPlaceholderViewController;
-(id)newReportAProblemViewControllerWithItemIdentifier:(unsigned long long)itemIdentifier;
-(id)newStorePageViewControllerWithSection:(id)section;
-(id)newViewControllerForPage:(id)page ofType:(int)type;
-(id)newViewControllerForTrackList:(id)trackList;
-(id)newVolumeViewController;
@end

