/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import "ChatKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface CKContentOffsetAnimation : XXUnknownSuperclass {
	CGPoint _startContentOffset;
	CGPoint _endContentOffset;
}
-(void)setProgress:(float)progress;
-(void)setStartContentOffset:(CGPoint)offset;
-(void)setEndContentOffset:(CGPoint)offset;
-(CGPoint)endContentOffset;
@end

