/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Search.framework/Search
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SPDomainManager : XXUnknownSuperclass {
}
+(id)defaultManager;
-(void)notifyIndexer;
-(void)applicationWasUninstalled:(id)uninstalled;
-(void)registerApplication:(id)application withCategories:(id)categories;
-(void)_removeAllDomainsForDisplayIdentifier:(id)displayIdentifier;
@end

