/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "_NSNegateBooleanTransformer.h"


__attribute__((visibility("hidden")))
@interface _NSIsNilTransformer : _NSNegateBooleanTransformer {
}
+(BOOL)supportsReverseTransformation;
-(id)transformedValue:(id)value;
-(id)description;
@end

