/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSCharacterSet.h"


__attribute__((visibility("hidden")))
@interface _NSPlaceholderCharacterSet : NSCharacterSet {
@private
	NSCharacterSet* _original;
	NSCharacterSet* _invertedSet;
	struct {
		unsigned _inverted : 1;
		unsigned _builtin : 1;
		unsigned _isCF : 1;
		unsigned _reserved : 29;
	} _flags;
}
-(id)initWithSet:(id)set options:(unsigned)options;
-(CFCharacterSetRef)_expandedCFCharacterSet;
-(void)_expandInverted;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(BOOL)characterIsMember:(unsigned short)member;
-(BOOL)longCharacterIsMember:(unsigned long)member;
-(BOOL)isSupersetOfSet:(id)set;
-(BOOL)hasMemberInPlane:(unsigned char)plane;
-(BOOL)isEqual:(id)equal;
-(id)bitmapRepresentation;
-(BOOL)isEmpty;
-(id)invertedSet;
-(id)autorelease;
-(id)retain;
-(unsigned)retainCount;
-(oneway void)release;
-(void)dealloc;
-(id)replacementObjectForKeyedArchiver:(id)keyedArchiver;
-(id)replacementObjectForCoder:(id)coder;
@end

