/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSConcreteData : XXUnknownSuperclass {
@private
	unsigned _isInline : 1;
	unsigned _shouldFree : 1;
	unsigned _hasVM : 1;
	unsigned _retainCount : 29;
	unsigned _length;
	unsigned _capacity;
	void* _bytes;
	unsigned char _space[12];
}
-(unsigned)length;
-(const void*)bytes;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)_bytesAreVM;
-(void)getBytes:(void*)bytes;
-(void)getBytes:(void*)bytes length:(unsigned)length;
-(void)getBytes:(void*)bytes range:(NSRange)range;
-(id)init;
-(id)initWithBytes:(void*)bytes length:(unsigned)length copy:(BOOL)copy freeWhenDone:(BOOL)done bytesAreVM:(BOOL)vm;
-(void)dealloc;
-(void)finalize;
@end

