/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSPredicateOperator.h"


@interface NSCompoundPredicateOperator : NSPredicateOperator {
}
+(id)andPredicateOperator;
+(id)orPredicateOperator;
+(id)notPredicateOperator;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(id)predicateFormat;
-(id)symbol;
-(BOOL)evaluatePredicates:(id)predicates withObject:(id)object;
-(BOOL)evaluatePredicates:(id)predicates withObject:(id)object substitutionVariables:(id)variables;
@end

