/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSValue.h"
#import "Foundation-Structs.h"


@interface NSConcreteValue : NSValue {
	unsigned _specialFlags;
	void* typeInfo;
}
+(void)initialize;
-(void)getValue:(void*)value;
-(const char*)objCType;
-(const void*)_value;
-(BOOL)isEqualToValue:(id)value;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(void)encodeWithCoder:(id)coder;
@end

