/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSFileWrapper.h"
#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

@interface NSFileWrapper : XXUnknownSuperclass <NSCoding> {
@private
	NSDictionary* _fileAttributes;
	NSString* _preferredFileName;
	NSString* _fileName;
	id _contents;
	id _icon;
	id _moreVars;
}
+(void)initialize;
+(BOOL)_forPath:(id)path getItemKind:(id*)kind modificationDate:(id*)date;
+(BOOL)_canSafelyMapFilesAtPath:(id)path;
+(id)_newContentsAtURL:(id)url path:(id)path itemKind:(id)kind oldChildrenByUniqueFileName:(id)name options:(unsigned)options error:(id*)error;
-(id)init;
-(id)_init;
-(id)initWithURL:(id)url options:(unsigned)options error:(id*)error;
-(id)initDirectoryWithFileWrappers:(id)fileWrappers;
-(id)initRegularFileWithContents:(id)contents;
-(id)initSymbolicLinkWithDestinationURL:(id)destinationURL;
-(id)initWithSerializedRepresentation:(id)serializedRepresentation;
-(void)dealloc;
-(BOOL)isDirectory;
-(BOOL)isRegularFile;
-(BOOL)isSymbolicLink;
-(void)_observePreferredFileNameOfChild:(id)child;
-(void)setPreferredFilename:(id)filename;
-(id)preferredFilename;
-(void)setFilename:(id)filename;
-(id)filename;
-(void)setFileAttributes:(id)attributes;
-(id)fileAttributes;
-(BOOL)_matchesItemKind:(id)kind modificationDate:(id)date;
-(BOOL)matchesContentsOfURL:(id)url;
-(BOOL)_readContentsFromURL:(id)url path:(id)path itemKind:(id)kind options:(unsigned)options error:(id*)error;
-(BOOL)readFromURL:(id)url options:(unsigned)options error:(id*)error;
-(void)_forWritingToURL:(id)url returnContentsLazyReadingError:(id*)error;
-(BOOL)_writeContentsToURL:(id)url path:(id)path originalContentsURL:(id)url3 tryHardLinking:(BOOL)linking didHardLinking:(BOOL*)linking5 error:(id*)error;
-(id)_attributesToWrite;
-(void)_updateDescendantFileNames;
-(BOOL)writeToURL:(id)url options:(unsigned)options originalContentsURL:(id)url3 error:(id*)error;
-(id)_initWithImpl:(id)impl preferredFileName:(id)name uniqueFileName:(id)name3 docInfo:(id)info iconData:(id)data;
-(id)_newImpl;
-(id)serializedRepresentation;
-(void)_addParent:(id)parent;
-(void)_removeParent:(id)parent;
-(void)_initDirectoryContents;
-(id)_addChild:(id)child forUniqueFileName:(id)uniqueFileName;
-(void)_resetFileModificationDate;
-(id)addFileWrapper:(id)wrapper;
-(id)addRegularFileWithContents:(id)contents preferredFilename:(id)filename;
-(id)_uniqueFileNameOfChild:(id)child;
-(void)_removeChild:(id)child forUniqueFileName:(id)uniqueFileName;
-(void)removeFileWrapper:(id)wrapper;
-(id)fileWrappers;
-(id)keyForFileWrapper:(id)fileWrapper;
-(id)regularFileContents;
-(id)symbolicLinkDestinationURL;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

@interface NSFileWrapper (NSInternal)
+(id)_pathForURL:(id)url reading:(BOOL)reading error:(id*)error;
+(id)_temporaryDirectoryURLForWritingToURL:(id)url error:(id*)error;
+(void)_writeAttributes:(id)attributes toURL:(id)url;
+(BOOL)_finishWritingToURL:(id)url byMovingItemAtURL:(id)url2 addingAttributes:(id)attributes error:(id*)error;
+(BOOL)_finishWritingToURL:(id)url byTakingContentsFromItemAtURL:(id)url2 addingAttributes:(id)attributes usingTemporaryDirectoryAtURL:(id)url4 backupFileName:(id)name error:(id*)error;
+(void)_removeTemporaryDirectoryAtURL:(id)url;
-(id)_fullDescription:(BOOL)description;
@end

