/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface NSFormatter : XXUnknownSuperclass <NSCopying, NSCoding> {
}
-(id)stringForObjectValue:(id)objectValue;
-(id)attributedStringForObjectValue:(id)objectValue withDefaultAttributes:(id)defaultAttributes;
-(id)editingStringForObjectValue:(id)objectValue;
-(BOOL)getObjectValue:(out id*)value forString:(id)string errorDescription:(out id*)description;
-(BOOL)getObjectValue:(out id*)value forString:(id)string range:(inout NSRange*)range error:(out id*)error;
-(BOOL)isPartialStringValid:(id)valid newEditingString:(id*)string errorDescription:(id*)description;
-(BOOL)isPartialStringValid:(id*)valid proposedSelectedRange:(NSRange*)range originalString:(id)string originalSelectedRange:(NSRange)range4 errorDescription:(id*)description;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

