/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Foundation-Structs.h"

@class NSObject, NSIndexSet;

__attribute__((visibility("hidden")))
@interface NSKeyValueChangeDictionary : XXUnknownSuperclass {
@private
	int _retainCountMinusOne;
	struct {
		unsigned kind;
		NSObject* oldValue;
		NSObject* newValue;
		NSIndexSet* indexes;
	} _details;
	NSObject* _originalObservable;
	BOOL _isPriorNotification;
	BOOL _isRetainingObjects;
}
-(id)initWithDetailsNoCopy:(XXStruct_m4zdSA)detailsNoCopy originalObservable:(id)observable isPriorNotification:(BOOL)notification;
-(void)setDetailsNoCopy:(XXStruct_m4zdSA)copy originalObservable:(id)observable;
-(void)setOriginalObservable:(id)observable;
-(void)retainObjects;
-(id)retain;
-(oneway void)release;
-(unsigned)retainCount;
-(void)dealloc;
-(unsigned)count;
-(id)objectForKey:(id)key;
-(id)keyEnumerator;
@end

