/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSKeyValueProxyGetter.h"

@class NSKeyValueNonmutatingCollectionMethodSet;

__attribute__((visibility("hidden")))
@interface NSKeyValueCollectionGetter : NSKeyValueProxyGetter {
@private
	NSKeyValueNonmutatingCollectionMethodSet* _methods;
}
-(id)initWithContainerClassID:(id)containerClassID key:(id)key methods:(id)methods proxyClass:(Class)aClass;
-(void)dealloc;
-(id)methods;
@end

