/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSMutableString.h"
#import "Foundation-Structs.h"

@class NSMutableAttributedString;

@interface NSMutableStringProxyForMutableAttributedString : NSMutableString {
@private
	NSMutableAttributedString* mutableAttributedString;
}
-(id)initWithMutableAttributedString:(id)mutableAttributedString;
-(void)dealloc;
-(void)finalize;
-(unsigned)length;
-(unsigned short)characterAtIndex:(unsigned)index;
-(void)getCharacters:(unsigned short*)characters range:(NSRange)range;
-(void)replaceCharactersInRange:(NSRange)range withString:(id)string;
@end

