/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface NSNotificationCenter : XXUnknownSuperclass {
@private
	void* _impl;
	void* _callback_block[4];
	void* _pad[8];
}
+(id)defaultCenter;
-(id)init;
-(void)finalize;
-(void)dealloc;
-(id)description;
-(void)addObserver:(id)observer selector:(SEL)selector name:(id)name object:(id)object;
-(void)removeObserver:(id)observer;
-(void)removeObserver:(id)observer name:(id)name object:(id)object;
-(void)postNotification:(id)notification;
-(void)postNotificationName:(id)name object:(id)object;
-(void)postNotificationName:(id)name object:(id)object userInfo:(id)info;
-(id)addObserverForName:(id)name object:(id)object queue:(id)queue usingBlock:(id)block;
-(BOOL)isEmpty;
@end

