/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface NSOperation : XXUnknownSuperclass {
@private
	id _private;
	void* _reserved;
}
+(void)initialize;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(id)_implicitObservationInfo;
-(void*)observationInfo;
-(void)setObservationInfo:(void*)info;
-(id)init;
-(id)retain;
-(void)release;
-(unsigned)retainCount;
-(void)dealloc;
-(void)finalize;
-(BOOL)isCancelled;
-(void)cancel;
-(BOOL)isExecuting;
-(BOOL)isFinished;
-(BOOL)isConcurrent;
-(BOOL)isAsynchronous;
-(BOOL)isReady;
-(int)queuePriority;
-(void)setQueuePriority:(int)priority;
-(double)threadPriority;
-(void)setThreadPriority:(double)priority;
-(id)completionBlock;
-(void)setCompletionBlock:(id)block;
-(void)waitUntilFinished;
-(void)waitUntilFinishedOrTimeout:(double)timeout;
-(void)addDependency:(id)dependency;
-(void)removeDependency:(id)dependency;
-(id)dependencies;
-(void)main;
-(void)start;
@end

