/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSRegularExpressionCheckingResult.h"

@class NSRegularExpression;

@interface NSSimpleRegularExpressionCheckingResult : NSRegularExpressionCheckingResult {
@private
	NSRegularExpression* _regularExpression;
	NSRange _ranges[3];
}
-(id)initWithRanges:(NSRange*)ranges count:(unsigned)count regularExpression:(id)expression;
-(id)initWithRangeArray:(id)rangeArray regularExpression:(id)expression;
-(void)dealloc;
-(id)regularExpression;
-(NSRange)range;
-(BOOL)_adjustRangesWithOffset:(int)offset;
-(unsigned)numberOfRanges;
-(NSRange)rangeAtIndex:(unsigned)index;
-(id)rangeArray;
@end

