/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Foundation-Structs.h"

@class NSString;

@interface NSSortDescriptor : XXUnknownSuperclass <NSCoding, NSCopying> {
@private
	unsigned _sortDescriptorFlags;
	NSString* _key;
	SEL _selector;
	id _selectorOrBlock;
}
+(void)initialize;
+(id)sortDescriptorWithKey:(id)key ascending:(BOOL)ascending;
+(id)sortDescriptorWithKey:(id)key ascending:(BOOL)ascending selector:(SEL)selector;
+(id)sortDescriptorWithKey:(id)key ascending:(BOOL)ascending comparator:(id)comparator;
+(id)_defaultSelectorName;
-(id)initWithKey:(id)key ascending:(BOOL)ascending;
-(id)initWithKey:(id)key ascending:(BOOL)ascending selector:(SEL)selector;
-(id)initWithKey:(id)key ascending:(BOOL)ascending comparator:(id)comparator;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(void)_setKey:(id)key;
-(id)key;
-(void)_setAscending:(BOOL)ascending;
-(BOOL)ascending;
-(SEL)selector;
-(id)comparator;
-(void)_setSelectorName:(id)name;
-(id)_selectorName;
-(id)description;
-(int)compareObject:(id)object toObject:(id)object2;
-(id)reversedSortDescriptor;
-(BOOL)_isEqualToSortDescriptor:(id)sortDescriptor;
-(BOOL)isEqual:(id)equal;
@end

