/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSCoder.h"


@interface NSUnarchiver : NSCoder {
@private
	void* datax;
	unsigned cursor;
	NSZone* objectZone;
	unsigned systemVersion;
	BOOL streamerVersion;
	BOOL swap;
	BOOL unused1;
	BOOL unused2;
	void* pointerTable;
	void* stringTable;
	id classVersions;
	int lastLabel;
	void* map;
	void* allUnarchivedObjects;
	id reserved;
}
+(void)initialize;
+(id)unarchiveObjectWithData:(id)data;
+(id)unarchiveObjectWithFile:(id)file;
+(void)decodeClassName:(id)name asClassName:(id)name2;
+(id)classNameDecodedForArchiveClassName:(id)archiveClassName;
-(id)initForReadingWithData:(id)data;
-(void)dealloc;
-(void)finalize;
-(void)replaceObject:(id)object withObject:(id)object2;
-(void)_setAllowedClasses:(id)classes;
-(void)setObjectZone:(NSZone*)zone;
-(NSZone*)objectZone;
-(BOOL)isAtEnd;
-(unsigned)systemVersion;
-(int)versionForClassName:(id)className;
-(id)data;
-(void)decodeValueOfObjCType:(const char*)objCType at:(void*)at;
-(void)decodeValuesOfObjCTypes:(const char*)objCTypes;
-(void)decodeArrayOfObjCType:(const char*)objCType count:(unsigned)count at:(void*)at;
-(void*)decodeBytesWithReturnedLength:(unsigned*)returnedLength;
-(id)decodeObject;
-(id)decodeDataObject;
-(void)decodeClassName:(id)name asClassName:(id)name2;
-(id)classNameDecodedForArchiveClassName:(id)archiveClassName;
@end

