/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSUndoManager.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Foundation-Structs.h"

@class NSArray;

@interface NSUndoManager : XXUnknownSuperclass {
@private
	id _undoStack;
	id _redoStack;
	NSArray* _runLoopModes;
	int _disabled;
	struct {
		unsigned undoing : 1;
		unsigned redoing : 1;
		unsigned registeredForCallback : 1;
		unsigned postingCheckpointNotification : 1;
		unsigned groupsByEvent : 1;
		unsigned reserved : 27;
	} _flags;
	id _target;
	id _proxy;
	void* _NSUndoManagerReserved1;
	void* _NSUndoManagerReserved2;
}
-(id)init;
-(void)dealloc;
-(void)_scheduleAutomaticTopLevelGroupEnding;
-(void)_cancelAutomaticTopLevelGroupEnding;
-(void)_prepareEventGrouping;
-(void)_postCheckpointNotification;
-(void)beginUndoGrouping;
-(int)groupingLevel;
-(BOOL)_endUndoGroupRemovingIfEmpty:(BOOL)empty;
-(void)endUndoGrouping;
-(void)disableUndoRegistration;
-(void)enableUndoRegistration;
-(BOOL)isUndoRegistrationEnabled;
-(BOOL)groupsByEvent;
-(void)setGroupsByEvent:(BOOL)event;
-(void)setLevelsOfUndo:(unsigned)undo;
-(unsigned)levelsOfUndo;
-(void)setRunLoopModes:(id)modes;
-(id)runLoopModes;
-(void)undo;
-(void)undoNestedGroup;
-(void)redo;
-(BOOL)canUndo;
-(BOOL)canRedo;
-(BOOL)isUndoing;
-(BOOL)isRedoing;
-(void)removeAllActions;
-(void)removeAllActionsWithTarget:(id)target;
-(id)prepareWithInvocationTarget:(id)invocationTarget;
-(id)_methodSignatureForTargetSelector:(SEL)targetSelector;
-(void)_registerUndoObject:(id)object;
-(void)_forwardTargetInvocation:(id)invocation;
-(void)registerUndoWithTarget:(id)target selector:(SEL)selector object:(id)object;
-(id)undoActionName;
-(id)redoActionName;
-(void)_setGroupIdentifier:(id)identifier;
-(void)setActionName:(id)name;
-(id)undoMenuItemTitle;
-(id)redoMenuItemTitle;
-(id)undoMenuTitleForUndoActionName:(id)undoActionName;
-(id)redoMenuTitleForUndoActionName:(id)undoActionName;
@end

@interface NSUndoManager (NSPrivate)
+(void)_setEndsTopLevelGroupingsAfterRunLoopIterations:(BOOL)iterations;
+(void)_endTopLevelGroupings;
-(id)_undoStack;
-(BOOL)_shouldCoalesceTypingForText:(id)text :(id)arg2;
-(void)_processEndOfEventNotification:(id)eventNotification;
-(void)_commitUndoGrouping;
-(void)_rollbackUndoGrouping;
@end

