/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSObject.h"


@protocol NSURLAuthenticationChallengeSender <NSObject>
-(void)useCredential:(id)credential forAuthenticationChallenge:(id)authenticationChallenge;
-(void)continueWithoutCredentialForAuthenticationChallenge:(id)authenticationChallenge;
-(void)cancelAuthenticationChallenge:(id)challenge;
@end

