/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import "GQDNameMappable.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface GQDTDurationFormat : XXUnknownSuperclass <GQDNameMappable> {
@private
	CFStringRef mFormatString;
}
+(const StateSpec*)stateForReading;
-(id)initWithFormatString:(CFStringRef)formatString;
-(void)dealloc;
-(CFStringRef)formatString;
-(int)readAttributesFromReader:(xmlTextReader*)reader;
@end

