/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "GQDTCell.h"
#import "iWorkImport-Structs.h"

@class GQDTComputedFormatSpec;

__attribute__((visibility("hidden")))
@interface GQDTNumberCell : GQDTCell {
@private
	double mValue;
	GQDTComputedFormatSpec* mComputedFormat;
}
-(void)dealloc;
-(double)value;
-(CFStringRef)createStringValue;
-(int)readAttributesForNumberCell:(xmlTextReader*)numberCell;
-(int)readAttributesForNCell:(xmlTextReader*)ncell;
@end

