/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import "GQDWPTocEntry.h"
#import "GQDWPBlockList.h"


__attribute__((visibility("hidden")))
@interface GQDWPTocEntry : GQDWPBlockList {
@private
	CFStringRef mBookmark;
}
-(void)dealloc;
-(CFStringRef)bookmark;
@end

@interface GQDWPTocEntry (Private)
-(int)readAttributesFromReader:(xmlTextReader*)reader processor:(id)processor;
@end

