/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "GQDWPAttachment.h"

@class GQDRoot;

__attribute__((visibility("hidden")))
@interface GQDWPAttachmentRef : GQDWPAttachment {
@private
	GQDRoot* mRoot;
	char* mUID;
}
-(id)initWithUID:(char*)uid root:(id)root;
-(void)dealloc;
-(id)drawable;
@end

