/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import "GQHChart.h"


__attribute__((visibility("hidden")))
@interface GQHChartLegend : GQHChart {
}
+(CFDataRef)renderChart:(id)chart;
+(char*)pdfId:(id)anId;
+(id)geometry:(id)geometry;
+(int)handleFloatingLegend:(id)legend state:(id)state;
+(int)handleInlineLegend:(id)legend state:(id)state;
@end

