/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Preferences-Structs.h"

@class UILabel;

@interface FailureBarView : XXUnknownSuperclass {
	UILabel* _titleLabel;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setFailureCount:(int)count;
@end

