/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "GameKitServices-Structs.h"


@interface GKSConnectivitySettings : XXUnknownSuperclass {
}
+(void)initialize;
+(void)setAddress:(id)address forService:(id)service;
+(void)setServerAddresses:(id)addresses;
+(void)setClientOptions:(id)options;
+(id)getClientOption:(id)option;
+(id)getAddressForService:(id)service;
+(tagIPPORT*)getIPPortForService:(id)service;
+(id)getAllSettings;
+(int)getNATTypeFromCarrierBundle;
+(int)getKeepAliveTimeoutFromCarrierBundle;
-(id)init;
-(void)dealloc;
@end

