/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsTrainer.framework/SportsTrainer
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SportsTrainer-Structs.h"

@class UIImage;

@interface STButtonBackgroundView : XXUnknownSuperclass {
	unsigned _buttonCount;
	UIImage* _backgroundImage;
}
@property(assign, nonatomic) unsigned buttonCount;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame buttonCount:(unsigned)count;
-(void)drawRect:(CGRect)rect;
@end

