/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsTrainer.framework/SportsTrainer
 */

#import "SportsTrainer-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (NikeAdditions)
+(id)backgroundImageViewForImage:(id)image frame:(CGRect)frame;
@end

@interface XXUnknownSuperclass (NikeAdditions)
+(id)nikeBackgroundImage;
+(id)nikeRunLandscapeBackgroundImage;
+(id)reversedNikeRunLandscapeBackgroundImage;
@end

