/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DAVKit.framework/DAVKit
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "DAVResponseBodyReader.h"

@class NSString, NSMutableData;

@interface _DAVLockBodyReader : XXUnknownSuperclass <DAVResponseBodyReader> {
	NSMutableData* readData;
	NSString* lockToken;
	int timeout;
}
-(id)init;
-(void)dealloc;
-(id)lockToken;
-(int)lockTimeout;
-(void)_calculateLockInfos;
-(BOOL)request:(id)request acceptResponseWithHTTPStatusCode:(int)httpstatusCode;
-(void)request:(id)request readResponseBody:(id)body;
@end

