/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
 */

#import "TelephonyUI-Structs.h"
#import "TPLCDBar.h"

@class UIView, TPLCDTextView, TPLCDSubImageView;

@interface TPLCDView : TPLCDBar {
	UIView* _contentView;
	TPLCDTextView* _textView;
	TPLCDTextView* _secondLineTextView;
	TPLCDTextView* _labelView;
	TPLCDSubImageView* _imageView;
	unsigned _layoutAsLabelled : 1;
}
+(float)textFontSize;
+(float)labelFontSize;
-(CGRect)_fullSizedContentViewFrame;
-(void)_resetContentViewFrame;
-(id)initWithDefaultSizeForOrientation:(int)orientation;
-(void)dealloc;
-(void)setContentsAlpha:(float)alpha;
-(float)_labelVInset;
-(float)_textVInset;
-(void)setText:(id)text;
-(id)text;
-(CGRect)_text1Frame;
-(CGRect)textFrame;
-(CGRect)_text2Frame;
-(id)secondLineText;
-(CGRect)_labelFrame;
-(CGRect)_imageViewFrame;
-(void)layoutSubviews;
-(void)setSecondLineText:(id)text;
-(void)didFinishAnimatingLCDLabelFadeOut:(id)anOut finished:(id)finished context:(id)context;
-(void)setLabel:(id)label animate:(BOOL)animate;
-(void)setLabel:(id)label;
-(id)label;
-(void)blinkLabel;
-(void)setSubImage:(id)image;
-(id)subImage;
-(void)setShadowColor:(id)color;
-(void)setLayoutAsLabelled:(BOOL)labelled;
@end

