/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "NSObject.h"


@protocol MFMailComposeControllerDelegate <NSObject>
@optional
-(void)mailComposeController:(id)controller willUseMessageHeaders:(id)headers;
-(void)mailComposeController:(id)controller loadedAttachments:(id)attachments;
-(void)mailComposeControllerFinishedLoadingInitialAttachments:(id)attachments;
-(void)mailComposeControllerComposeBodyFieldDidFinishLoad;
-(void)mailComposeControllerCompositionFinished:(id)finished;
-(void)mailComposeControllerWillAttemptToSend:(id)mailComposeController;
-(void)mailComposeControllerDidAttemptToSend:(id)mailComposeController outgoingMessageDelivery:(id)delivery;
-(void)mailComposeControllerDidAttemptToSaveDraft:(id)mailComposeController account:(id)account result:(int)result;
@end

