/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MessageUI-Structs.h"
#import "_MFComposeRecipientViewDelegate.h"
#import "ABUnknownPersonViewControllerDelegate.h"
#import "ABPersonViewControllerDelegate.h"
#import "MFComposeBodyFieldDelegate.h"
#import "MFContactsSearchConsumer.h"
#import "UITextContentViewDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UIScrollViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MFComposeSubjectView, UIView, UIBarButtonItem, UINavigationItem, UITextContentView, UIPickerView, ABPeoplePickerNavigationController, UITableView, UIResponder, MFComposeFromView, NSNumber, MFComposeMultiView, NSInvocation, MFContactsSearchManager, MFContactsSearchResultsModel, MFComposeRecipientAtom, _MFComposeRecipientView, MFComposeScrollView, MFComposeImageSizeView, MFFromAddressViewController, MFComposeBodyField;
@protocol MFMailComposeViewDelegate, MFMailPopoverManagerDelegate;

@interface MFMailComposeView : XXUnknownSuperclass <UITextContentViewDelegate, UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource, MFContactsSearchConsumer, ABPersonViewControllerDelegate, ABUnknownPersonViewControllerDelegate, MFComposeBodyFieldDelegate, _MFComposeRecipientViewDelegate> {
	UIBarButtonItem* _sendButtonItem;
@private
	UIView* _contentView;
	UINavigationItem* _navigationItem;
	UIBarButtonItem* _closeButtonItem;
	MFComposeBodyField* _bodyField;
	UIView* _headerView;
	MFComposeScrollView* _bodyScroller;
	UITextContentView* _textView;
	_MFComposeRecipientView* _toField;
	_MFComposeRecipientView* _ccField;
	_MFComposeRecipientView* _bccField;
	MFComposeSubjectView* _subjectField;
	MFComposeFromView* _fromField;
	MFComposeMultiView* _multiField;
	MFComposeImageSizeView* _imageSizeField;
	UIView* _shadowView;
	UIPickerView* _fromAddressPickerView;
	MFFromAddressViewController* _fromAddressViewController;
	ABPeoplePickerNavigationController* _peoplePicker;
	unsigned _options;
	float _finalToHeight;
	float _finalCCHeight;
	float _offsetBeforeSearch;
	float _keyboardIntersection;
	id _sendTarget;
	SEL _sendAction;
	id _closeTarget;
	SEL _closeAction;
	id _presentPeoplePickerTarget;
	SEL _presentPeoplePickerAction;
	id _dismissPeoplePickerTarget;
	SEL _dismissPeoplePickerAction;
	id _presentPersonCardTarget;
	SEL _presentPersonCardAction;
	id _dismissPersonCardTarget;
	SEL _dismissPersonCardAction;
	_MFComposeRecipientView* _lastChangedRecipientView;
	_MFComposeRecipientView* _activeRecipientView;
	UITableView* _searchResultsTable;
	id<MFMailPopoverManagerDelegate> _popoverOwner;
	UIResponder* _firstResponderBeforeSheet;
	UIResponder* _pinningResponder;
	MFComposeRecipientAtom* _savedAddressAtom;
	BOOL _animationDisabled;
	id<MFMailComposeViewDelegate> _mailComposeViewDelegate;
	MFContactsSearchManager* _contactsSearchActor;
	MFContactsSearchResultsModel* _searchResultsModel;
	NSNumber* _searchTaskID;
	NSInvocation* _delayedPopoverInvocation;
	unsigned _scheduledDeferedProgressMonitoring : 1;
	unsigned _toHeightChanging : 1;
	unsigned _ccHeightChanging : 1;
	unsigned _pinToBottomOfHeaderView : 1;
	unsigned _changingRecipients : 1;
	unsigned _isLoading : 1;
	unsigned _multiFieldOverride : 1;
	unsigned _isShowingPeoplePicker : 1;
	unsigned _pendingMultiFieldOverride : 1;
	unsigned _isRotating : 1;
	unsigned _isClosing : 1;
	unsigned _isShowingFromAddressPickerWheel : 1;
	unsigned _isShowingImageResizingBar : 1;
	BOOL _isForEditing;
}
@property(assign, nonatomic) id<MFMailComposeViewDelegate> composeViewDelegate;
@property(retain, nonatomic) NSNumber* searchTaskID;
@property(assign, nonatomic) BOOL isForEditing;
-(id)_searchResultsTable;
-(void)_collectKeyViews:(id)views;
-(BOOL)_fixUpView:(id)view changingView:(id)view2 toSize:(CGSize)size fieldFrame:(CGRect*)frame;
-(void)composeHeaderViewClicked:(id)clicked;
-(void)_multiFieldClicked;
-(void)_setupField:(id)field isNew:(BOOL)aNew changingView:(id)view toSize:(CGSize)size fieldFrame:(CGRect*)frame visible:(BOOL)visible;
-(void)_setupField:(id*)field withLabel:(id)label navTitle:(id)title property:(int)property changingView:(id)view toSize:(CGSize)size fieldFrame:(CGRect*)frame visible:(BOOL)visible;
-(void)_getLabel:(id*)label andAccountDescription:(id*)description currentScaleImageSize:(id*)size forState:(XXStruct_WhIsoD)state;
-(void)_setupMultiFieldWithState:(XXStruct_WhIsoD)state changingView:(id)view toSize:(CGSize)size fieldFrame:(CGRect*)frame;
-(void)_setupFromFieldChangingView:(id)fieldChangingView toSize:(CGSize)size fieldFrame:(CGRect*)frame visible:(BOOL)visible;
-(void)_setupSubjectField:(CGRect*)field;
-(void)_setupImageSizeFieldChangingView:(id)view toSize:(CGSize)size fieldFrame:(CGRect*)frame visible:(BOOL)visible;
-(void)_setupBodyFieldWithHeaderFrame:(CGRect)headerFrame enclosingFrame:(CGRect)frame changingView:(id)view frameToPin:(CGRect)pin wasSearching:(BOOL)searching;
-(void)_layoutSubviewsWithActiveRecipientView:(BOOL)activeRecipientView changingView:(id)view toSize:(CGSize)size;
-(void)getOptionalFieldState:(XXStruct_WhIsoD*)state;
-(void)_layoutSubviews:(BOOL)subviews changingView:(id)view toSize:(CGSize)size;
-(void)_layoutSubviews:(BOOL)subviews changingView:(id)view toSize:(CGSize)size searchResultsWereDismissed:(BOOL)dismissed;
-(void)_layoutSubviews:(BOOL)subviews;
-(void)toggleImageSizeFieldIfNecessary;
-(id)initWithFrame:(CGRect)frame navigationItem:(id)item options:(unsigned)options delegate:(id)delegate;
-(id)bottomView;
-(void)dealloc;
-(void)setAutoresizingMask:(unsigned)mask;
-(BOOL)endEditing:(BOOL)editing;
-(BOOL)allowSend;
-(BOOL)isLoading;
-(void)setIsLoading:(BOOL)loading;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)setPopoverOwner:(id)owner;
-(void)searchResultsPopoverWasDismissed;
-(BOOL)composeRecipientViewIsShowingPeoplePicker:(id)picker;
-(void)_presentDelayedPopover;
-(void)_cancelDelayedPopover;
-(void)resetContentSize;
-(id)toField;
-(id)ccField;
-(id)bccField;
-(id)subjectField;
-(id)fromField;
-(id)imageSizeField;
-(id)multiField;
-(id)bodyField;
-(id)bodyScroller;
-(id)bodyTextView;
-(void)_adjustScrollerContentSize;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_finishUpRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didAnimateFirstHalfOfRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)composeBodyFieldFrameChanged:(id)changed;
-(void)composeBodyFieldDidDraw:(id)composeBodyField;
-(void)composeBodyFieldDidFirstVisuallyNonEmptyLayout:(id)composeBodyField;
-(void)layoutSubviews;
-(void)composeBodyFieldDidFinishLoadForFrame:(id)composeBodyField;
-(void)_adjustScrollerForBottomView;
-(CGRect)_frameForFromAddressPicker;
-(void)fromAddressPickerPopoverWasDismissed;
-(void)setFromAddressPickerVisible:(BOOL)addressPickerVisible;
-(BOOL)isFromAddressPickerVisible;
-(void)fromAddressPickerNeedsToBeRefreshed;
-(void)setAnimationDisabled:(BOOL)disabled;
-(void)_updateKeyboardIntersection:(CGRect)intersection;
-(void)automaticKeyboardFinishedAppearing:(id)appearing;
-(void)automaticKeyboardFinishedDisappearing:(id)disappearing;
-(void)setKeyboardVisible:(BOOL)visible animate:(BOOL)animate;
-(BOOL)isKeyboardVisible;
-(void)scrollerDidScroll:(id)scroller;
-(float)_heightForBottomView;
-(void)setNavigationBarTitle:(id)title animated:(BOOL)animated;
-(void)setSendTarget:(id)target action:(SEL)action;
-(void)setCloseTarget:(id)target action:(SEL)action;
-(void)_sendButtonClicked:(id)clicked;
-(void)_closeButtonClicked:(id)clicked;
-(void)setSendEnabled:(BOOL)enabled closeEnabled:(BOOL)enabled2;
-(void)setSendEnabled:(BOOL)enabled;
-(void)saveFirstResponder;
-(void)saveFirstResponderWithKeyboardPinning:(BOOL)keyboardPinning;
-(void)restoreFirstResponder;
-(void)restoreFirstResponderWithKeyboardPinning:(BOOL)keyboardPinning;
-(void)scrollToTopAnimated:(BOOL)topAnimated;
-(void)setScrollsToTop:(BOOL)top;
-(void)displayAlertSheet:(id)sheet;
-(void)dismissAlertSheet:(id)sheet animate:(BOOL)animate willClose:(BOOL)close;
-(void)setEnabled:(BOOL)enabled changingUI:(BOOL)ui;
-(void)setToolbarButtonsEnabled:(BOOL)enabled;
-(int)activeAddressField;
-(void)composeRecipientView:(id)view didChangeSize:(CGSize)size;
-(void)composeRecipientViewWillBecomeFirstResponder:(id)composeRecipientView;
-(void)composeRecipientViewDidResignFirstResponder:(id)composeRecipientView;
-(void)composeRecipientViewDidBecomeFirstResponder:(id)composeRecipientView;
-(id)composeRecipientView:(id)view composeRecipientForAddress:(id)address;
-(id)composeRecipientView:(id)view composeRecipientForRecord:(void*)record identifier:(int)identifier;
-(void)composeRecipientView:(id)view textDidChange:(id)text;
-(void)composeRecipientViewReturnPressed:(id)pressed;
-(void)consumeSearchResults:(id)results type:(int)type taskID:(id)anId;
-(void)finishedSearchingForType:(int)type;
-(void)finishedTaskWithID:(id)anId;
-(void)beganNetworkActivity;
-(void)endedNetworkActivity;
-(void)composeRecipientViewDidFinishEnteringRecipient:(id)composeRecipientView;
-(void)composeRecipientView:(id)view requestDeleteRecipientAtIndex:(int)index;
-(void)removeFromSuperview;
-(void)setPresentPeoplePickerTarget:(id)target action:(SEL)action;
-(void)setDismissPeoplePickerTarget:(id)target action:(SEL)action;
-(void)dismissPeoplePicker;
-(void)popoverControllerDidDismiss:(id)popoverController;
-(void)composeRecipientViewRequestAddRecipient:(id)recipient;
-(void)transitionViewDidComplete:(id)transitionView;
-(void)composeRecipientViewDidFinishPickingRecipient:(id)composeRecipientView;
-(void)setPresentPersonCardTarget:(id)target action:(SEL)action;
-(void)setDismissPersonCardTarget:(id)target action:(SEL)action;
-(void)presentPersonCardViewController:(id)controller fromView:(id)view;
-(void)dismissPersonCard;
-(void)composeRecipientView:(id)view showPersonCardForAtom:(id)atom;
-(BOOL)personViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(void*)person;
-(BOOL)unknownPersonViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)parentWillClose;
-(void)parentDidClose;
-(BOOL)textContentView:(id)view shouldScrollForPendingContentSize:(CGSize)pendingContentSize;
-(BOOL)textContentView:(id)view shouldChangeSizeForContentSize:(CGSize)contentSize;
-(void)textContentView:(id)view didChangeSize:(CGSize)size;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
@end

