/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSData, NSURLConnection, NSMutableData;

@interface YTDeviceAuthenticator : XXUnknownSuperclass {
	NSURLConnection* _connection;
	NSMutableData* _responseData;
	NSString* _token;
	double _timeTokenGranted;
	int _phase;
	NSData* _r1;
	NSData* _r1Hash;
	NSData* _r2;
	NSData* _hmac;
}
+(id)sharedAuthenticator;
-(void)_loadStatusChanged;
-(void)_copyCertificateData:(id*)data privateKey:(SecKey**)key;
-(BOOL)canAuthenticate;
-(BOOL)_authenticate1;
-(BOOL)_authenticate2;
-(void)_clearNonces;
-(void)_failWithErrorCode:(int)errorCode;
-(void)authenticate;
-(BOOL)isAuthenticating;
-(id)token;
-(void)invalidateToken;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)_succeeded;
-(void)_connectionDidEnd;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
@end

