/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import "ICCameraFile.h"

@class NSString;

@interface PTPCameraFile : ICCameraFile {
@private
	void* _ptpCameraFileProperties;
	NSString* _path;
}
@property(retain) NSString* path;
@property(copy) id info;
@property(readonly, assign) unsigned objHandle;
@property(readonly, assign) unsigned storageID;
@property(readonly, assign) unsigned type;
-(id)initWithName:(id)name parentFolder:(id)folder device:(id)device type:(unsigned)type storageID:(unsigned long)anId objectHandle:(unsigned long)handle;
-(void)dealloc;
-(void)finalize;
-(long)writeDataToFile:(int)file fromOffset:(long long)offset ofLength:(long long*)length;
-(id)thumbData;
-(id)metadataDict;
@end

