/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface PTPInitCommandRequestPacket : XXUnknownSuperclass {
	unsigned char _initiatorGUID[16];
	NSString* _initiatorFriendlyName;
}
-(id)initWithInitiatorGUID:(char*)initiatorGUID initiatorFriendlyName:(id)name;
-(id)initWithTCPBuffer:(void*)tcpbuffer;
-(void)dealloc;
-(id)contentForTCP;
-(id)description;
-(const char*)initiatorGUID;
-(void)setInitiatorGUID:(char*)guid;
-(id)initiatorFriendlyName;
-(void)setInitiatorFriendlyName:(id)name;
@end

