/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet;

@interface ADKeyStore : XXUnknownSuperclass {
	NSMutableSet* _whitelistedScalarKeys;
	NSMutableSet* _whitelistedScalarPrefixes;
	NSMutableSet* _whitelistedDistributionKeys;
	NSMutableSet* _whitelistedDistributionPrefixes;
	BOOL _isInternalDevice;
}
-(id)initWithPath:(id)path additionalAcceptedClasses:(id)classes;
-(id)initWithDefaultPathAndAdditionalAcceptedClasses:(id)defaultPathAndAdditionalAcceptedClasses;
-(void)dealloc;
-(BOOL)scalarKeyIsWhitelisted:(id)whitelisted;
-(BOOL)distributionKeyIsWhitelisted:(id)whitelisted;
@end

