/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import "WebKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class WebResource, NSArray;

__attribute__((visibility("hidden")))
@interface WebArchivePrivate : XXUnknownSuperclass {
@private
	WebResource* cachedMainResource;
	NSArray* cachedSubresources;
	NSArray* cachedSubframeArchives;
	RefPtr<WebCore::LegacyWebArchive> coreArchive;
}
+(void)initialize;
-(id)init;
-(id)initWithCoreArchive:(PassRefPtr<WebCore::LegacyWebArchive>)coreArchive;
-(LegacyWebArchive*)coreArchive;
-(void)setCoreArchive:(PassRefPtr<WebCore::LegacyWebArchive>)archive;
-(void)dealloc;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

