/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WebDefaultFrameLoadDelegate : XXUnknownSuperclass {
}
+(id)sharedFrameLoadDelegate;
-(void)webView:(id)view didStartProvisionalLoadForFrame:(id)frame;
-(void)webView:(id)view didReceiveServerRedirectForProvisionalLoadForFrame:(id)frame;
-(void)webView:(id)view didFailProvisionalLoadWithError:(id)error forFrame:(id)frame;
-(void)webView:(id)view didCommitLoadForFrame:(id)frame;
-(void)webView:(id)view didReceiveTitle:(id)title forFrame:(id)frame;
-(void)webView:(id)view didFinishLoadForFrame:(id)frame;
-(void)webView:(id)view didFailLoadWithError:(id)error forFrame:(id)frame;
-(void)webView:(id)view didChangeLocationWithinPageForFrame:(id)frame;
-(void)webView:(id)view willPerformClientRedirectToURL:(id)url delay:(double)delay fireDate:(id)date forFrame:(id)frame;
-(void)webView:(id)view didCancelClientRedirectForFrame:(id)frame;
-(void)webView:(id)view willCloseFrame:(id)frame;
-(void)webView:(id)view didClearWindowObject:(id)object forFrame:(id)frame;
-(void)webView:(id)view windowScriptObjectAvailable:(id)available;
-(void)webViewDidDisplayInsecureContent:(id)webView;
-(void)webView:(id)view didRunInsecureContent:(id)content;
-(void)webView:(id)view didClearWindowObjectForFrame:(id)frame inScriptWorld:(id)scriptWorld;
-(void)webView:(id)view didPushStateWithinPageForFrame:(id)frame;
-(void)webView:(id)view didReplaceStateWithinPageForFrame:(id)frame;
-(void)webView:(id)view didPopStateWithinPageForFrame:(id)frame;
-(void)webView:(id)view didFirstLayoutInFrame:(id)frame;
-(void)webView:(id)view didFinishDocumentLoadForFrame:(id)frame;
-(void)webView:(id)view didHandleOnloadEventsForFrame:(id)frame;
-(void)webView:(id)view didFirstVisuallyNonEmptyLayoutInFrame:(id)frame;
-(void)webView:(id)view didClearInspectorWindowObject:(id)object forFrame:(id)frame;
@end

