/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import "WebKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WebEditCommand : XXUnknownSuperclass {
@private
	RefPtr<WebCore::EditCommand> m_command;
}
+(void)initialize;
+(id)commandWithEditCommand:(PassRefPtr<WebCore::EditCommand>)editCommand;
-(id)initWithEditCommand:(PassRefPtr<WebCore::EditCommand>)editCommand;
-(void)dealloc;
-(void)finalize;
-(EditCommand*)command;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

