/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class WebGeolocationManagerPrivate;

@interface WebGeolocationManager : XXUnknownSuperclass {
@private
	WebGeolocationManagerPrivate* _private;
}
+(id)sharedGeolocationManager;
-(id)init;
-(void)suspend;
-(void)resume;
-(void)dealloc;
@end

