/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WebPreferencesPrivate : XXUnknownSuperclass {
@private
	NSMutableDictionary* values;
	NSString* identifier;
	NSString* IBCreatorID;
	BOOL autosaves;
	BOOL automaticallyDetectsCacheModel;
	unsigned numWebViews;
}
-(void)dealloc;
@end

