/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"
#import "WebPolicyDecisionListener.h"

@class WebPolicyDecisionListenerPrivate;

@protocol WebPolicyDecisionListener <NSObject>
-(void)use;
-(void)download;
-(void)ignore;
@end

__attribute__((visibility("hidden")))
@interface WebPolicyDecisionListener : XXUnknownSuperclass <WebPolicyDecisionListener> {
@private
	WebPolicyDecisionListenerPrivate* _private;
}
-(id)_initWithTarget:(id)target action:(SEL)action;
-(void)dealloc;
-(void)_usePolicy:(int)policy;
-(void)_invalidate;
-(void)use;
-(void)ignore;
-(void)download;
@end

