/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import "ICSProperty.h"

@class NSString, ICSDateValue;

@interface ICSAttendeeComment : ICSProperty {
}
@property(retain) ICSDateValue* x_calendarserver_dtstamp;
@property(retain) NSString* x_calendarserver_attendee_ref;
-(id)initWithComment:(id)comment;
-(void)setComment:(id)comment;
@end

