/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import "ICSBusyStatusValue.h"
#import "ICSPredefinedValue.h"


@interface ICSBusyStatusValue : ICSPredefinedValue {
}
+(id)busyStatusTypeFromCode:(int)code;
@end

@interface ICSBusyStatusValue (ICSWriter)
-(void)_ICSStringWithOptions:(unsigned)options appendingToString:(id)string;
@end

@interface ICSBusyStatusValue (iCalendarImport)
+(id)busyStatusValueFromICSString:(id)icsstring;
@end

