/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import "ICSPredefinedValue.h"
#import "ICSClassificationValue.h"


@interface ICSClassificationValue : ICSPredefinedValue {
}
+(id)classificationFromCode:(int)code;
@end

@interface ICSClassificationValue (ICSWriter)
-(void)_ICSStringWithOptions:(unsigned)options appendingToString:(id)string;
@end

@interface ICSClassificationValue (iCalendarImport)
+(id)classificationValueFromICSString:(id)icsstring;
@end

