/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import "ICSScheduleStatusParameter.h"
#import "ICSPredefinedValue.h"


@interface ICSScheduleStatusParameter : ICSPredefinedValue {
}
+(id)scheduleStatusParameterFromCode:(int)code;
@end

@interface ICSScheduleStatusParameter (ICSWriter)
-(void)_ICSStringWithOptions:(unsigned)options appendingToString:(id)string;
@end

@interface ICSScheduleStatusParameter (iCalendarImport)
+(id)scheduleStatusParameterFromICSString:(id)icsstring;
@end

