/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import "DataAccess-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class DACalendarDatabase;

@interface DACalendarObject : XXUnknownSuperclass {
	DACalendarDatabase* _database;
	void* _ref;
}
@property(readonly, assign, nonatomic) DACalendarDatabase* database;
@property(readonly, assign, nonatomic) void* ref;
+(id)NSArrayFromCFArray:(CFArrayRef)cfarray objectClass:(Class)aClass database:(id)database;
-(id)initWithDatabase:(id)database ref:(void*)ref;
-(void)dealloc;
@end

