/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray;

@interface DASettingsTemplate : XXUnknownSuperclass {
	NSString* _name;
	int _order;
	NSString* _primaryDomain;
	NSArray* _domainAliasPatterns;
	NSString* _primaryUsernameDomain;
	int _httpPort;
	int _httpsPort;
	int _port;
	NSString* _pathFormat;
	BOOL _isDefaultTemplate;
	BOOL _defaultUseSSL;
}
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) int order;
@property(retain, nonatomic) NSString* primaryDomain;
@property(retain, nonatomic) NSArray* domainAliasPatterns;
@property(retain, nonatomic) NSString* primaryUsernameDomain;
@property(assign, nonatomic) int httpPort;
@property(assign, nonatomic) int httpsPort;
@property(retain, nonatomic) NSString* pathFormat;
@property(assign) BOOL isDefaultTemplate;
@property(assign, nonatomic) BOOL defaultUseSSL;
@property(readonly, assign, nonatomic) NSString* defaultScheme;
@property(readonly, assign, nonatomic) int defaultPort;
+(id)knownTemplates;
+(id)defaultTemplate;
+(BOOL)requiresPathFormat;
+(BOOL)requiresPorts;
+(id)templateWithDomain:(id)domain;
+(BOOL)_isValidPort:(int)port;
-(id)_initWithName:(id)name plist:(id)plist;
-(void)dealloc;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(int)compare:(id)compare;
-(BOOL)_isDomainInAliases:(id)aliases;
-(void)initAccount:(id)account;
-(void)setDomain:(id)domain forAccount:(id)account;
-(void)setUsername:(id)username forAccount:(id)account;
-(void)setUseSSL:(BOOL)ssl forAccount:(id)account;
-(void)setPort:(int)port forAccount:(id)account;
-(void)setURL:(id)url forAccount:(id)account;
-(void)setPrincipalURLForAccount:(id)account toURL:(id)url;
-(void)_setPrincipalURLForAccount:(id)account;
-(void)_appendPrimarySuffixToUsernameIfNeeded:(id)usernameIfNeeded;
-(id)descriptionForAccount:(id)account;
-(BOOL)_isPrincipalPathCustomForAccount:(id)account;
-(id)_principalPathForAccount:(id)account;
-(id)description;
@end

