/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol DADataclassLockWatcher;

@interface DAWaiterWrapper : XXUnknownSuperclass {
	id<DADataclassLockWatcher> _waiter;
	int _dataclasses;
	id _completionHandler;
	int _waiterNum;
}
@property(retain) id<DADataclassLockWatcher> waiter;
@property(copy) id completionHandler;
@property(assign) int dataclasses;
@property(readonly, assign) int waiterNum;
-(id)init;
-(id)description;
-(void)dealloc;
@end

