/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
 */

#import "ApplePushService-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableDictionary, NSLock, NSString;
@protocol APSConnectionDelegate;

@interface APSConnection : XXUnknownSuperclass {
	id<APSConnectionDelegate> _delegate;
	NSLock* _lock;
	NSString* _environmentName;
	CFRunLoopSourceRef _runLoopSource;
	NSString* _connectionPortName;
	unsigned _connectionPort;
	int _serverPID;
	unsigned _connectionServerPort;
	CFMachPortRef _connectionSeverCFMachPort;
	NSArray* _enabledTopics;
	NSArray* _ignoredTopics;
	NSMutableDictionary* _subtopics;
	BOOL _enableCriticalReliability;
}
@property(assign) id<APSConnectionDelegate> delegate;
@property(readonly, assign, nonatomic) int serverPID;
+(SecIdentity*)copyIdentity;
+(double)keepAliveIntervalForEnvironmentName:(id)environmentName;
+(id)connectionsDebuggingState;
-(id)initWithEnvironmentName:(id)environmentName;
-(id)initWithEnvironmentName:(id)environmentName namedDelegatePort:(id)port;
-(void)dealloc;
-(void)_connect;
-(void)_disconnect;
-(void)_connectionServerPortInvalidated;
-(void)scheduleInRunLoop:(id)runLoop;
-(void)removeFromRunLoop;
-(id)_dataForPropertyList:(id)propertyList;
-(void)setEnabledTopics:(id)topics;
-(void)_sendEnabledTopics;
-(void)setIgnoredTopics:(id)topics;
-(void)_sendIgnoredTopics;
-(void)setSubtopic:(id)subtopic forEnabledTopic:(id)enabledTopic;
-(id)publicToken;
-(BOOL)hasIdentity;
-(void)setEnableCriticalReliability:(BOOL)reliability;
-(void)_sendEnableCriticalReliability;
-(void)_deliverMessageForTopic:(id)topic userInfo:(id)info;
-(void)_deliverPublicToken:(id)token;
@end

