/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, MPAudioDeviceController;

@interface MPAudioRoutingPicker : XXUnknownSuperclass {
	MPAudioDeviceController* _audioDeviceController;
	BOOL _ignoringInteractionEvents;
	NSArray* _routes;
}
-(id)initWithAVController:(id)avcontroller;
-(void)setAVController:(id)controller;
-(void)dealloc;
-(void)audioDeviceControllerAudioRoutesChanged:(id)changed;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)willMoveToSuperview:(id)superview;
-(BOOL)requiresPortraitOrientation;
-(BOOL)_pickRouteAtIndex:(unsigned)index withPassword:(id)password;
@end

