/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MPMediaItemCollection.h"
#import "MediaPlayer-Structs.h"

@class NSMutableDictionary, MPMediaQuery, MPMediaItem;

@interface MPConcreteMediaItemCollection : MPMediaItemCollection {
@private
	long long _identifier;
	MPMediaQuery* _itemsQuery;
	NSMutableDictionary* _properties;
	int _grouping;
	MPMediaItem* _representativeItem;
}
-(id)initWithIdentifier:(long long)identifier valuesForProperties:(id)properties itemsQuery:(id)query grouping:(int)grouping;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)mediaLibrary;
-(unsigned long long)persistentID;
-(id)valueForProperty:(id)property;
-(id)itemsQuery;
-(id)items;
-(id)representativeItem;
-(unsigned)count;
-(int)mediaTypes;
@end

