/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPSwipableView.h"
#import "MPNowPlayingItemQueueInfoButtonDelegate.h"
#import "MPVideoOverlay.h"

@class MPNowPlayingItemQueueInfoButton, UINavigationBar, MPDetailSlider, UINavigationItem, MPCenteringNavigationBar, MPAVItem, MPVideoViewController, UIImageView, UILabel, UIView, UINavigationButton, MPTransportControls;
@protocol MPVideoOverlayDelegate;

@interface MPFullScreenVideoOverlay : MPSwipableView <MPNowPlayingItemQueueInfoButtonDelegate, MPVideoOverlay> {
	MPVideoViewController* _videoController;
	id<MPVideoOverlayDelegate> _delegate;
	MPAVItem* _item;
	int _interfaceOrientation;
	UIView* _loadingMovieIndicatorView;
	MPDetailSlider* _scrubControl;
	UILabel* _scrubSpeedLabel;
	UILabel* _scrubInstructionsLabel;
	MPTransportControls* _transportControls;
	MPNowPlayingItemQueueInfoButton* _itemQueueInfoButton;
	UINavigationButton* _backButton;
	MPCenteringNavigationBar* _navigationBar;
	UIImageView* _navigationBarBackground;
	UIImageView* _navigationBarShadow;
	UINavigationItem* _navigationItem;
	UINavigationButton* _scaleModeButton;
	unsigned _desiredParts;
	unsigned _disabledParts;
	unsigned _visibleParts;
	unsigned _tvOutEnabled : 1;
	unsigned _wantsTick : 1;
	unsigned _allowsDetailScrubbing : 1;
	unsigned _detailScrubbing : 1;
}
@property(assign, nonatomic) id<MPVideoOverlayDelegate> delegate;
@property(assign, nonatomic) unsigned desiredParts;
@property(assign, nonatomic) unsigned disabledParts;
@property(retain, nonatomic) MPAVItem* item;
@property(readonly, retain, nonatomic) UINavigationBar* navigationBar;
@property(assign, nonatomic) int interfaceOrientation;
@property(readonly, retain, nonatomic) MPTransportControls* transportControls;
@property(assign, nonatomic) MPVideoViewController* videoViewController;
@property(assign, nonatomic) unsigned visibleParts;
@property(assign, nonatomic) BOOL allowsWirelessPlayback;
@property(assign, nonatomic) BOOL allowsDetailScrubbing;
@property(assign, nonatomic) BOOL TVOutEnabled;
-(id)initWithFrame:(CGRect)frame interfaceOrientation:(int)orientation;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)restoreSanity;
-(void)startTicking;
-(void)stopTicking;
-(void)didMoveToSuperview;
-(void)didMoveToWindow;
-(void)_initNavigationBarBackground;
-(void)layoutSubviews;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)setAlpha:(float)alpha;
-(void)setHidden:(BOOL)hidden;
-(void)showAlternateTracks;
-(void)hideAlternateTracks;
-(int)nowPlayingItemQueueInfoButton:(id)button willDisplayInfoType:(int)type;
-(void)_configureLinkButtonForCurrentItemTime;
-(void)crossedURLTimeMarker:(id)marker;
-(id)viewsToFadeOutWhenShowingBackside;
-(void)setDesiredParts:(unsigned)parts animate:(BOOL)animate;
-(void)setVideoController:(id)controller;
-(void)setVisibleParts:(unsigned)parts animate:(BOOL)animate;
-(void)_backButtonAction:(id)action;
-(void)_scaleButtonAction:(id)action;
-(void)_destinationDidChangeNotification:(id)_destination;
-(void)_tickNotification:(id)notification;
-(void)_timeDidJumpNotification:(id)_time;
-(void)_validityChangedNotification:(id)notification;
-(void)_statusBarHeightChanged:(id)changed;
-(void)_bufferingStateDidChange:(id)_bufferingState;
-(void)_playbackStateDidChangeNotification:(id)_playbackState;
-(void)_scaleModeDidChangeNotification:(id)_scaleMode;
-(void)detailSliderTrackingDidBegin:(id)detailSliderTracking;
-(void)detailSliderTrackingDidEnd:(id)detailSliderTracking;
-(void)detailSliderTrackingDidCancel:(id)detailSliderTracking;
-(void)detailSlider:(id)slider didChangeValue:(float)value;
-(void)detailSlider:(id)slider didChangeScrubSpeed:(int)speed;
-(unsigned)_desiredPartsForTransportControlsWithParts:(unsigned)parts;
-(id)_loadingMovieIndicatorView;
-(void)_initNavigationBar;
-(void)_reloadTransportControls:(BOOL)controls;
-(void)_reloadNavigationBarWithAnimation:(BOOL)animation;
-(id)_scrubControlWithFrame:(CGRect)frame;
-(void)_updateScrubControlWithAnimation:(BOOL)animation;
-(BOOL)_updateScrubControlVisibility;
-(void)_updateTimeBasedValues;
-(unsigned)_visiblePartsForTransportControlsWithParts:(unsigned)parts;
-(void)_showScrubInstructions;
-(void)_hideScrubInstructions;
@end

