/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, MPMediaLibrary;

@interface MPMediaLibraryConnectionAssertion : XXUnknownSuperclass {
@private
	MPMediaLibrary* _library;
@protected
	NSString* _identifier;
}
@property(readonly, assign, nonatomic) NSString* identifier;
-(id)_initWithMediaLibrary:(id)mediaLibrary identifier:(id)identifier;
-(void)dealloc;
-(id)description;
@end

