/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MPMediaQueryCriteria;

@interface MPMediaLibraryEntityWriteStream : XXUnknownSuperclass {
@private
	id _entityArray;
	MPMediaQueryCriteria* _queryCriteria;
	unsigned _index;
	unsigned _count;
	BOOL _cancelled;
}
@property(readonly, assign, nonatomic, getter=isCancelled) BOOL cancelled;
@property(readonly, assign, nonatomic) unsigned index;
@property(readonly, assign, nonatomic) unsigned count;
-(id)initWithEntityStreamArray:(id)entityStreamArray queryCriteria:(id)criteria count:(unsigned)count;
-(void)dealloc;
-(id)description;
-(void)writeItemWithIdentifier:(long long)identifier valuesForProperties:(id)properties;
-(void)writeCollectionWithIdentifier:(long long)identifier valuesForProperties:(id)properties;
-(void)_writeCollectionWithIdentifier:(long long)identifier valuesForProperties:(id)properties itemsQueryCriteria:(id)criteria;
-(void)cancel;
@end

