/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import "NSObject.h"


@protocol CalSearchDataSink <NSObject>
-(void)calSearch:(id)search foundOccurrences:(CFArrayRef)occurrences cachedDays:(CFArrayRef)days cachedDaysIndexes:(CFArrayRef)indexes;
-(void)calSearchComplete:(id)complete;
@optional
-(bool)calSearchShouldStopSearching:(id)calSearch;
-(void)calSearch:(id)search showResultsStartingOnDate:(double)date;
@end

