/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, EKEventStore, NSArray, UITableView, NSIndexPath, NSSet, NSMutableDictionary;
@protocol EKCalendarChooserDelegate;

@interface EKCalendarChooser : XXUnknownSuperclass {
@private
	int _style;
	UITableView* _tableView;
	id<EKCalendarChooserDelegate> _delegate;
	EKEventStore* _store;
	NSArray* _groups;
	NSMutableDictionary* _storeGroupMap;
	NSMutableSet* _selectedCalendars;
	NSIndexPath* _checkedRow;
	unsigned _listIsFlat : 1;
	unsigned _showAll : 1;
	unsigned _showColors : 1;
	unsigned _allSelected : 1;
	unsigned _allowsRotation : 1;
	unsigned _showsDoneButton : 1;
	unsigned _showsCancelButton : 1;
}
@property(assign, nonatomic) id<EKCalendarChooserDelegate> delegate;
@property(readonly, assign, nonatomic) int style;
@property(copy, nonatomic) NSSet* selectedCalendars;
@property(assign, nonatomic) BOOL showsCancelButton;
@property(assign, nonatomic) BOOL showsDoneButton;
@property(retain, nonatomic) EKEventStore* eventStore;
-(id)initWithChooserStyle:(int)chooserStyle;
-(void)dealloc;
-(void)loadView;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(CGSize)contentSizeForViewInPopoverView;
-(void)setAllowsRotation:(BOOL)rotation;
-(BOOL)allowsRotation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)cancel:(id)cancel;
-(void)done:(id)done;
-(id)_groupForSource:(id)source;
-(id)_saveSelection;
-(void)_restoreSelection:(id)selection newCalendars:(id)calendars;
-(void)calendarsChanged:(id)changed;
-(id)_loadCalendars;
-(void)_applySelection;
-(void)_setCalendars:(id)calendars;
-(void)setCheckedRow:(id)row;
-(void)setSelectedCalendar:(id)calendar;
-(id)selectedCalendar;
-(id)_indexPathForCalendar:(id)calendar source:(id)source;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)_numSelectedGroups;
-(void)_selectGroup:(id)group selected:(BOOL)selected;
-(void)_selectCalendar:(id)calendar selected:(BOOL)selected;
-(void)_selectAllCalendarsAndStores:(BOOL)stores;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
@end

