/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class EKGroupInfo, EKCalendar, NSString, UIColor;

__attribute__((visibility("hidden")))
@interface EKCalendarInfo : XXUnknownSuperclass {
@private
	EKCalendar* _calendar;
	UIColor* _color;
	BOOL _selected;
	EKGroupInfo* _group;
}
@property(retain, nonatomic) UIColor* color;
@property(assign, nonatomic) BOOL selected;
@property(assign, nonatomic) EKGroupInfo* group;
@property(readonly, assign, nonatomic) BOOL isSubscribed;
@property(readonly, assign, nonatomic) int displayOrder;
@property(readonly, copy, nonatomic) NSString* title;
@property(retain, nonatomic) EKCalendar* calendar;
-(id)initWithCalendar:(id)calendar;
-(void)dealloc;
@end

