/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "NSObject.h"


@protocol EKDayViewContentDataSource <NSObject>
-(unsigned)numberOfEventsInDayViewContent:(id)dayViewContent;
-(id)dayViewContent:(id)content startDateForEventAtIndex:(unsigned)index;
-(id)dayViewContent:(id)content endDateForEventAtIndex:(unsigned)index;
-(double)dayViewContent:(id)content durationForEventAtIndex:(unsigned)index;
-(id)dayViewContent:(id)content occurrenceViewForEventAtIndex:(unsigned)index;
@end

