/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EKEventDetailCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface EKEventDetailAvailabilityCell : EKEventDetailCell {
@private
	UILabel* _availabilityTitleView;
	UILabel* _availabilityView;
}
-(void)dealloc;
-(BOOL)isEditableForEvent;
-(BOOL)update;
-(void)setAvailability:(int)availability;
-(id)_availabilityTitleView;
-(id)_availabilityView;
-(void)layoutForWidth:(float)width position:(int)position;
@end

