/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EKEventEditItem.h"
#import "EventKitUI-Structs.h"
#import "UITextFieldDelegate.h"

@class UIResponder, UITableViewCell;

__attribute__((visibility("hidden")))
@interface EKEventTitleInlineEditItem : EKEventEditItem <UITextFieldDelegate> {
@private
	UITableViewCell* _titleCell;
	UITableViewCell* _locationCell;
	UIResponder* _selectedTextField;
}
@property(retain, nonatomic) UIResponder* selectedResponder;
-(float)defaultCellHeightForSubitemAtIndex:(int)index forWidth:(float)width;
-(void)dealloc;
-(BOOL)isInline;
-(id)selectedTextField;
-(void)reset;
-(int)numberOfSubitems;
-(id)_makeCell:(int)cell;
-(id)cellForSubitemAtIndex:(int)index;
-(BOOL)saveAndDismissWithForce:(BOOL)force;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
@end

