/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import "EKEventDetailItem.h"

@class EKEventDetailRecurrenceCell, NSString;

__attribute__((visibility("hidden")))
@interface EKEventRecurrenceDetailItem : EKEventDetailItem {
@private
	EKEventDetailRecurrenceCell* _cell;
	int _repeatType;
	int _originalRepeatType;
	XXStruct_lQVxyC _repeatEndGr;
	NSString* _customRepeatDescription;
	BOOL _indent;
}
-(void)dealloc;
-(void)reset;
-(BOOL)configureWithCalendar:(id)calendar preview:(BOOL)preview;
-(void)setEvent:(id)event store:(id)store;
-(id)cellForSubitemAtIndex:(int)index;
-(float)defaultCellHeightForSubitemAtIndex:(int)index forWidth:(float)width;
@end

