/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "EKEventEditItemViewControllerDelegate.h"

@class EKEventStore, EKEventEditItemViewController, EKEvent;
@protocol EKEventEditItemDelegate;

__attribute__((visibility("hidden")))
@interface EKEventEditItem : XXUnknownSuperclass <EKEventEditItemViewControllerDelegate> {
@private
	EKEventStore* _store;
	EKEvent* _event;
	id<EKEventEditItemDelegate> _delegate;
	EKEventEditItemViewController* _viewController;
}
@property(assign) id<EKEventEditItemDelegate> delegate;
-(void)dealloc;
-(void)setEvent:(id)event store:(id)store;
-(void)reset;
-(BOOL)configureForCalendarConstraints:(id)calendarConstraints;
-(int)numberOfSubitems;
-(float)defaultCellHeightForSubitemAtIndex:(int)index forWidth:(float)width;
-(id)cellForSubitemAtIndex:(int)index;
-(id)detailViewControllerWithFrame:(CGRect)frame forSubitemAtIndex:(int)index;
-(void)eventEditor:(id)editor didSelectSubitem:(int)subitem;
-(void)notifyDidStartEditing;
-(void)notifyDidEndEditing;
-(void)notifySubitemDidCommit:(int)notifySubitem;
-(void)notifyTextChanged;
-(BOOL)saveAndDismissWithForce:(BOOL)force;
-(BOOL)eventEditItemViewControllerCommit:(id)commit;
-(void)eventEditItemViewControllerWantsKeyboardPinned:(BOOL)pinned;
-(void)editItemViewController:(id)controller didCompleteWithAction:(int)action;
-(BOOL)isInline;
-(id)selectedTextField;
@end

