/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import "EKPadAllDayView.h"


@interface EKPadDayAllDayView : EKPadAllDayView {
}
-(id)makeAllDayLabel;
-(void)buildDayLabel;
-(void)updateDayLabels;
-(id)_calendarOrderSortDescriptor;
-(id)getSortedBlocksFromOccurrenceBlocks:(id)occurrenceBlocks;
@end

