/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CTMmsEncoder : XXUnknownSuperclass {
}
+(id)decodeSmsFromData:(id)data;
+(id)encodeSms:(id)sms;
+(id)encodeMessage:(id)message;
+(id)decodeMessageFromData:(id)data;
@end

