/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSNumber;

@interface SSApplicationUserReview : XXUnknownSuperclass {
@private
	NSString* _applicationPath;
	NSNumber* _itemIdentifier;
	float _userRating;
	NSNumber* _versionIdentifier;
}
@property(readonly, assign, nonatomic) NSString* applicationPath;
@property(assign, nonatomic) float userRating;
@property(readonly, assign, nonatomic, getter=isValidReview) BOOL validReview;
-(id)init;
-(id)initForApplicationWithPath:(id)path;
-(void)dealloc;
-(BOOL)scheduleReview;
-(void)_loadApplicationMetadata;
@end

