/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSLock, NSArray, NSURLRequest;

@interface SSDownloadAsset : XXUnknownSuperclass <NSCoding> {
@private
	NSString* _downloadFileName;
	long long _fileSize;
	NSString* _finalizedFileName;
	NSArray* _hashes;
	long long _numberOfBytesToHash;
	BOOL _isExternal;
	NSLock* _lock;
	NSString* _processedPath;
	int _type;
	NSURLRequest* _urlRequest;
}
@property(assign) long long numberOfBytesToHash;
@property(retain) NSArray* hashes;
@property(assign, getter=isExternal) BOOL external;
@property(readonly, assign) NSString* purchaseManifestKey;
@property(readonly, assign) NSString* downloadInformationKey;
@property(readonly, assign) NSString* finalizedPath;
@property(retain) NSString* finalizedFileName;
@property(retain) NSString* processedPath;
@property(readonly, assign) NSString* downloadPath;
@property(retain) NSString* downloadFileName;
@property(assign) long long fileSize;
@property(retain) NSURLRequest* URLRequest;
@property(assign) int type;
+(id)assetWithURL:(id)url type:(int)type;
-(id)init;
-(id)initWithURLRequest:(id)urlrequest type:(int)type;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)copyPropertyListEncoding;
-(id)initWithPropertyListEncoding:(id)propertyListEncoding;
-(void)setLocalFileNameFromBase:(id)base;
@end

