/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "StoreServices-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURL;

@interface SSItemArtworkImage : XXUnknownSuperclass <NSCopying> {
@private
	int _height;
	NSString* _imageKind;
	int _imageOrientation;
	float _imageScale;
	BOOL _prerendered;
	NSURL* _url;
	int _width;
}
@property(readonly, assign, nonatomic) int height;
@property(copy, nonatomic) NSString* imageKind;
@property(assign, nonatomic) int imageOrientation;
@property(assign, nonatomic) float imageScale;
@property(assign, nonatomic, getter=isPrerendered) BOOL prerendered;
@property(retain, nonatomic) NSURL* URL;
@property(readonly, assign, nonatomic) int width;
@property(readonly, assign, nonatomic) CGSize imageSize;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)initWithArtworkDictionary:(id)artworkDictionary;
-(void)setImageKindWithTypeName:(id)typeName variantName:(id)name;
@end

