/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "StoreServices-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary, SSItemArtworkImage, NSMutableDictionary;

@interface SSItemContentRating : XXUnknownSuperclass <NSCopying> {
@private
	NSMutableDictionary* _dictionary;
}
@property(readonly, assign, nonatomic) SSItemArtworkImage* ratingSystemLogo;
@property(readonly, assign, nonatomic) NSDictionary* contentRatingDictionary;
@property(assign, nonatomic) BOOL shouldHideWhenRestricted;
@property(readonly, assign, nonatomic, getter=isRestricted) BOOL restricted;
@property(assign, nonatomic) int ratingSystem;
@property(copy, nonatomic) NSString* ratingLabel;
@property(copy, nonatomic) NSString* ratingDescription;
@property(assign, nonatomic) int rank;
@property(readonly, assign, nonatomic, getter=isExplicitContent) BOOL explicitContent;
+(int)ratingSystemFromString:(id)string;
+(id)stringForRatingSystem:(int)ratingSystem;
-(id)init;
-(id)initWithDictionary:(id)dictionary;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)valueForProperty:(id)property;
-(BOOL)_isRatingSystemForApps:(int)apps;
-(BOOL)_isRatingSystemForMovies:(int)movies;
-(BOOL)_isRatingSystemForMusic:(int)music;
-(BOOL)_isRatingSystemForTV:(int)tv;
-(void)_setValueCopy:(id)copy forProperty:(id)property;
-(void)_setValue:(id)value forProperty:(id)property;
@end

