/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "SSRequest.h"

@class NSMutableIndexSet, NSArray;
@protocol SSPurchaseRequestDelegate;

@interface SSPurchaseRequest : SSRequest {
@private
	NSMutableIndexSet* _acknowledgedPurchases;
	NSArray* _purchases;
	BOOL _shouldValidatePurchases;
}
@property(assign, nonatomic) id<SSPurchaseRequestDelegate> delegate;
@property(assign, nonatomic) BOOL shouldValidatePurchases;
@property(readonly, assign) NSArray* purchases;
-(id)init;
-(id)initWithPurchases:(id)purchases;
-(void)dealloc;
-(id)copyPropertyListEncoding;
-(id)initWithPropertyListEncoding:(id)propertyListEncoding;
-(void)handleDaemonExit;
-(BOOL)issueRequestForIdentifier:(id)identifier error:(id*)error;
-(void)registerForDaemonNotifications;
-(void)unregisterForDaemonNotifications;
-(void)_purchaseFailedNotification:(id)notification;
-(void)_purchaseFinishedNotification:(id)notification;
-(id)_purchaseForUniqueIdentifier:(id)uniqueIdentifier;
-(void)_sendError:(id)error forPurchase:(id)purchase;
@end

