/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSMutableDictionary, NSDictionary, NSMutableArray, NSArray;

@interface IMFileTransferCenter : XXUnknownSuperclass {
	NSMutableDictionary* _guidToTransferMap;
	NSMutableDictionary* _guidToRemovedTransferMap;
	NSMutableDictionary* _accountIDToTransferGUIDsMap;
	NSMutableArray* _preauthorizedInfos;
	NSMutableArray* _preauthorizedGUIDs;
	NSMutableSet* _activeTransfers;
	NSMutableSet* _pendingTransfers;
}
@property(readonly, assign, nonatomic) BOOL hasPendingFileTransfers;
@property(readonly, assign, nonatomic) BOOL hasActiveFileTransfers;
@property(readonly, assign, nonatomic) NSArray* orderedTransfers;
@property(readonly, assign, nonatomic) NSDictionary* activeTransfers;
+(id)sharedInstance;
+(void)setTransferCenterClass:(Class)aClass;
+(Class)transferCenterClass;
+(Class)fileTransferClass;
-(id)init;
-(void)dealloc;
-(void)_addPendingTransfer:(id)transfer;
-(void)_removePendingTransfer:(id)transfer;
-(void)acknowledgePendingTransfer:(id)transfer;
-(void)acknowledgeAllPendingTransfers;
-(void)_addActiveTransfer:(id)transfer;
-(void)_removeActiveTransfer:(id)transfer;
-(void)_removeAllActiveTransfers;
-(void)_clearTransfers;
-(void)_addTransfer:(id)transfer toAccount:(id)account;
-(void)_addTransfer:(id)transfer;
-(BOOL)doesLocalURLRequireArchiving:(id)archiving toHandle:(id)handle;
-(id)guidForNewOutgoingTransferWithLocalURL:(id)localURL;
-(void)assignTransfer:(id)transfer toHandle:(id)handle securityLevel:(int)level;
-(id)transferForGUID:(id)guid;
-(id)transferForGUID:(id)guid includeRemoved:(BOOL)removed;
-(void)sendTransfer:(id)transfer;
-(void)acceptTransfer:(id)transfer withPath:(id)path autoRename:(BOOL)rename overwrite:(BOOL)overwrite;
-(void)stopTransfer:(id)transfer;
-(void)removeTransfer:(id)transfer;
-(void)retargetTransfer:(id)transfer toPath:(id)path;
-(id)transfersForAccount:(id)account;
-(BOOL)isFileTransfer:(id)transfer preauthorizedWithDictionary:(id)dictionary;
-(void)preauthorizeFileTransferFromOtherPerson:(id)otherPerson account:(id)account filename:(id)filename saveToPath:(id)path;
-(BOOL)wasFileTransferPreauthorized:(id)preauthorized;
-(void)acceptFileTransferIfPreauthorzed:(id)preauthorzed;
-(void)_handleStandaloneFileTransferRegistered:(id)registered;
-(void)_handleAllFileTransfers:(id)transfers;
-(void)_handleFileTransfer:(id)transfer createdWithProperties:(id)properties;
-(void)_handleFileTransfer:(id)transfer updatedWithProperties:(id)properties;
-(void)_handleFileTransfer:(id)transfer updatedWithCurrentBytes:(unsigned long long)currentBytes totalBytes:(unsigned long long)bytes averageTransferRate:(unsigned long long)rate;
@end

