/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VisualVoicemail.framework/VisualVoicemail
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VisualVoicemail-Structs.h"


@interface VVNotificationInterpreter : XXUnknownSuperclass {
}
+(id)interpretedDictionaryForNotificationUserInfo:(CFDictionaryRef)notificationUserInfo;
@end

