/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "PhotoLibrary-Structs.h"

@class UITableView, NSArray, PLAirTunesService;
@protocol PLAirTunesServicePickerViewControllerDelegate;

@interface PLAirTunesServicePickerViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	NSArray* _availableServices;
	id _delegate;
	UITableView* _table;
	PLAirTunesService* _selectedService;
}
@property(assign, nonatomic) id<PLAirTunesServicePickerViewControllerDelegate> delegate;
-(void)dealloc;
-(id)initWithAvailableAirTunesServices:(id)availableAirTunesServices previouslySelectedService:(id)service;
-(void)loadView;
-(void)viewDidAppear:(BOOL)view;
-(CGSize)contentSizeForViewInPopoverView;
-(void)_setCell:(id)cell checked:(BOOL)checked;
-(void)setAvailableServices:(id)services;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
@end

