/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PhotoLibrary-Structs.h"

@class UIView, NSString, UILabel, PLVideoView;

@interface PLImageView : XXUnknownSuperclass {
	NSString* _name;
	UIView* _borderView;
	PLVideoView* _videoView;
	UILabel* _textBadge;
	unsigned _shadowEnabled : 1;
	unsigned _suppressShadowDrawing : 1;
	unsigned _borderIsVisible : 1;
	float _aspectRatio;
	double _lastBorderAlphaTime;
	double _lastShadowAlphaTime;
	float _transitionProgress;
	BOOL _edgeAntialiasingEnabled;
}
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) float transitionProgress;
@property(retain, nonatomic) PLVideoView* videoView;
@property(assign, nonatomic, getter=isShadowEnabled) BOOL shadowEnabled;
@property(assign, nonatomic) float borderAlpha;
@property(assign, nonatomic, getter=isBorderVisible) BOOL borderVisible;
@property(assign, nonatomic, getter=isDimmed) BOOL dimmed;
+(void)initialize;
+(BOOL)shouldDrawShadows;
+(id)textBadgeForString:(id)string photoSize:(CGSize)size;
-(id)textBadgeString;
-(void)setTextBadgeString:(id)string;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)fits allowRounding:(BOOL)rounding;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)renderSnapshotInContext:(CGContextRef)context;
-(void)layoutSubviews;
-(void)_updateShadowPath;
-(void)setImage:(id)image;
-(void)parentDidLayout;
-(void)setBorderAlpha:(float)alpha forced:(BOOL)forced;
-(void)setBorderWidthScale:(float)scale heightScale:(float)scale2;
-(void)setEdgeAntialiasingEnabled:(BOOL)enabled;
@end

