/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface PLImageSource : XXUnknownSuperclass {
}
-(id)newImageForObject:(id)object createMetadata:(id*)metadata;
-(id)identifier;
-(id)imageKeyForObject:(id)object;
@end

