/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PhotoLibrary-Structs.h"
#import "MPMediaPickerControllerDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class NSString, PLSlideshowTransitionsViewController, MPMediaPickerController, UITableViewCell, PLSlideshowAirPlayRoutesViewController, NSArray, UITableView, MPMediaItemCollection, UIView;
@protocol PLSlideshowSettingsViewControllerDelegate;

@interface PLSlideshowSettingsViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, MPMediaPickerControllerDelegate> {
	NSArray* _airPlayServices;
	unsigned _selectedAirPlayServiceIndex;
	NSArray* _transitionKeys;
	NSArray* _alternateTransitionLocalizations;
	NSString* _selectedTransition;
	BOOL _shouldPlayMusic;
	MPMediaPickerController* _mediaPicker;
	MPMediaItemCollection* _selectedMusicCollection;
	UIView* _containerView;
	UITableView* _table;
	UITableViewCell* _transitionCell;
	UITableViewCell* _selectedMusicCell;
	UITableViewCell* _playSlideshowCell;
	UITableViewCell* _playMusicSwitchCell;
	PLSlideshowTransitionsViewController* _transitionsController;
	PLSlideshowAirPlayRoutesViewController* _airPlayRoutesController;
	id<PLSlideshowSettingsViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<PLSlideshowSettingsViewControllerDelegate> delegate;
@property(assign, nonatomic) MPMediaItemCollection* slideshowMusicCollection;
@property(assign, nonatomic) BOOL slideshowShouldPlayMusic;
@property(retain, nonatomic) NSString* selectedTransition;
+(id)AppleTVPushTransitions;
+(id)TVOutTransitions;
+(id)iPhoneTransitions;
+(id)iPadTransitions;
+(int)_uiTransitionForTransitionKey:(id)transitionKey;
+(id)_transitionKeyForUITransition:(int)uitransition;
-(id)initWithAirPlayServices:(id)airPlayServices selectedServiceIndex:(unsigned)index;
-(void)dealloc;
-(void)applySlideshowSettings:(id)settings;
-(id)slideshowSettings;
-(void)_playMusicSwitchValueDidChange:(id)_playMusicSwitchValue;
-(void)viewWillAppear:(BOOL)view;
-(id)_selectedAirPlayService;
-(void)_updateSettingsInfo;
-(void)loadView;
-(CGSize)contentSizeForViewInPopoverView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)_selectedMusic;
-(void)_playButtonWasPressed:(id)pressed;
-(void)_preheatMediaPicker;
-(BOOL)_includeAirPlaySection;
-(unsigned)_airPlaySection;
-(unsigned)_mainSection;
-(unsigned)_startSection;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)mediaPicker:(id)picker didPickMediaItems:(id)items;
-(void)mediaPickerDidCancel:(id)mediaPicker;
@end

