/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "NSObject.h"


@protocol PLUIEditImageViewControllerDelegate <NSObject>
@optional
-(void)editImageViewController:(id)controller didEditImageWithOptions:(id)options;
-(void)editImageViewControllerDidCancel:(id)editImageViewController;
@end

