/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLWStackedImageCacheCreator.h"

@class NSMutableArray;

@interface PLWEventImporterStackedImageCacheCreator : PLWStackedImageCacheCreator {
	NSMutableArray* _eventAlbums;
}
-(void)dealloc;
-(void)createStackedImageForAlbum:(id)album withNewlyInsertedPhoto:(id)newlyInsertedPhoto;
-(id)_albums;
@end

