/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import "PLWStackedImageCache.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class PLFixedSizeLRUCache, NSLock;

@interface PLWStackedImageCache : XXUnknownSuperclass {
	PLFixedSizeLRUCache* _stackedImagesCache;
	PLFixedSizeLRUCache* _stackedImageOptionsCache;
	NSLock* _lock;
}
+(id)sharedInstance;
+(id)absolutePathToCachesDirectory;
+(id)absolutePathToCachedStackedImagesDirectory;
-(id)init;
-(void)dealloc;
-(id)stackedImageWithKey:(unsigned)key options:(id*)options;
-(void)prefetchStackedImagesWithKey1:(unsigned)key1 key2:(unsigned)a2 key3:(unsigned)a3 key4:(unsigned)a4;
-(void)setStackedImage:(id)image forKey:(unsigned)key options:(id)options;
-(void)invalidateAll;
-(void)invalidateEntryForKey:(unsigned)key;
@end

@interface PLWStackedImageCache (Internal)
-(id)_bakedStackedImageFilenameForWithKey:(unsigned)key;
-(id)_pathToBakedCachedStackedImageWithKey:(unsigned)key;
-(BOOL)_createBaseDirectoryForStackedImagesCache;
@end

