/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Assistant.framework/Assistant
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface AFAccount : XXUnknownSuperclass {
	NSString* _identifier;
	NSString* _hostname;
	NSString* _firstName;
	NSString* _lastName;
	NSString* _emailAddress;
	NSString* _password;
}
@property(copy, nonatomic) NSString* password;
@property(copy, nonatomic) NSString* emailAddress;
@property(copy, nonatomic) NSString* lastName;
@property(copy, nonatomic) NSString* firstName;
@property(copy, nonatomic) NSString* hostname;
@property(copy, nonatomic) NSString* identifier;
-(id)messageDictionary;
-(id)initWithMessageDictionary:(id)messageDictionary;
-(id)description;
-(void)dealloc;
@end

