/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "FTMessage.h"

@class NSString, NSDictionary;

@interface FTGetRegionMetadataMessage : FTMessage {
	NSString* _language;
	NSDictionary* _responseRegionInformation;
}
@property(copy) NSString* language;
@property(copy) NSDictionary* responseRegionInformation;
-(void)dealloc;
-(id)bagKey;
-(id)requiredKeys;
-(id)messageBody;
-(void)handleResponseDictionary:(id)dictionary;
@end

