/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import "FTProfileMessage.h"

@class NSArray;

@interface FTProfileQueryEmailsMessage : FTProfileMessage {
	NSArray* _responseEmails;
}
@property(copy) NSArray* responseEmailAddresses;
-(void)dealloc;
-(id)bagKey;
-(id)requiredKeys;
-(id)messageBody;
-(void)handleResponseDictionary:(id)dictionary;
@end

