/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PrintKit.framework/PrintKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDate, NSData, PKPrintSettings;

@interface PKJob : XXUnknownSuperclass {
@private
	int number;
	int mediaProgress;
	int mediaSheets;
	int mediaSheetsCompleted;
	NSString* printerDisplayName;
	int printerKind;
	NSString* printerLocation;
	PKPrintSettings* settings;
	int state;
	NSDate* timeAtCompleted;
	NSDate* timeAtCreation;
	NSDate* timeAtProcessing;
@protected
	NSData* thumbnailImage;
}
@property(assign, nonatomic) int number;
@property(assign, nonatomic) int mediaProgress;
@property(assign, nonatomic) int mediaSheets;
@property(assign, nonatomic) int mediaSheetsCompleted;
@property(retain, nonatomic) NSString* printerDisplayName;
@property(assign, nonatomic) int printerKind;
@property(retain, nonatomic) NSString* printerLocation;
@property(retain, nonatomic) PKPrintSettings* settings;
@property(assign, nonatomic) int state;
@property(retain, nonatomic) NSDate* timeAtCompleted;
@property(retain, nonatomic) NSDate* timeAtCreation;
@property(retain, nonatomic) NSDate* timeAtProcessing;
@property(retain, nonatomic) NSData* thumbnailImage;
+(id)currentJob;
+(id)jobs;
-(int)cancel;
-(int)update;
@end

