/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class SSAuthenticationContext, NSNumber, SSAuthenticateRequest;

@interface ISStoreAuthenticateOperation : ISOperation {
	NSNumber* _authenticatedDSID;
	SSAuthenticateRequest* _request;
}
@property(readonly, assign) SSAuthenticationContext* authenticationContext;
-(id)initWithAuthenticationContext:(id)authenticationContext;
-(void)dealloc;
-(id)authenticatedAccountDSID;
-(void)run;
-(id)uniqueKey;
-(void)authenticateRequest:(id)request didReceiveResponse:(id)response;
-(void)request:(id)request didFailWithError:(id)error;
-(id)_authenticatedDSID;
-(void)_setAuthenticatedDSID:(id)dsid;
@end

