/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, NSDate;

@interface _CPPowerAssertionThread : XXUnknownSuperclass {
	NSTimer* _timer;
	NSDate* _earliest;
}
-(void)main;
-(void)addAssertion:(id)assertion;
-(void)didTimeOut:(id)anOut;
@end

