/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSLocking.h"

@class NSString;

@interface CPExclusiveLock : XXUnknownSuperclass <NSLocking> {
	int _fd;
	NSString* _name;
}
-(id)init;
-(id)initWithName:(id)name;
-(void)dealloc;
-(void)lock;
-(void)unlock;
-(BOOL)tryLock;
-(void)setName:(id)name;
-(id)name;
@end

