/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/JSON.framework/JSON
 */

#import "JSON.h"


__attribute__((visibility("hidden")))
@interface JSONWriter : JSON {
}
-(id)stringWithObject:(id)object;
-(id)indent;
-(BOOL)appendValue:(id)value into:(id)into;
-(BOOL)appendArray:(id)array into:(id)into;
-(BOOL)appendDictionary:(id)dictionary into:(id)into;
-(BOOL)appendString:(id)string into:(id)into;
@end

