/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMCSSRule.h"

@class DOMCSSRuleList, DOMMediaList;

__attribute__((visibility("hidden")))
@interface DOMCSSMediaRule : DOMCSSRule {
}
@property(readonly, retain) DOMCSSRuleList* cssRules;
@property(readonly, retain) DOMMediaList* media;
-(unsigned)insertRule:(id)rule index:(unsigned)index;
-(unsigned)insertRule:(id)rule :(unsigned)arg2;
-(void)deleteRule:(unsigned)rule;
@end

