/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMObject.h"

@class NSString;
@protocol DOMEventTarget;

@interface DOMEvent : DOMObject {
}
@property(assign) BOOL cancelBubble;
@property(assign) BOOL returnValue;
@property(readonly, retain) id<DOMEventTarget> srcElement;
@property(readonly, assign) unsigned long long timeStamp;
@property(readonly, assign) BOOL cancelable;
@property(readonly, assign) BOOL bubbles;
@property(readonly, assign) unsigned short eventPhase;
@property(readonly, retain) id<DOMEventTarget> currentTarget;
@property(readonly, retain) id<DOMEventTarget> target;
@property(readonly, copy) NSString* type;
-(void)dealloc;
-(void)finalize;
-(BOOL)defaultPrevented;
-(void)stopPropagation;
-(void)preventDefault;
-(void)initEvent:(id)event canBubbleArg:(BOOL)arg cancelableArg:(BOOL)arg3;
-(void)initEvent:(id)event :(BOOL)arg2 :(BOOL)arg3;
-(void)stopImmediatePropagation;
@end

