/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "WebCore-Structs.h"
#import "WAKResponder.h"
#import "WAKView.h"

@class NSMutableSet;

@interface WAKView : WAKResponder {
@private
	WKViewContext viewContext;
	WKView* viewRef;
	NSMutableSet* subviewReferences;
}
+(CFDictionaryRef)_viewWrappers;
+(void)_addViewWrapper:(id)wrapper;
+(void)_removeViewWrapper:(id)wrapper;
+(id)_wrapperForViewRef:(WKView*)viewRef;
+(id)focusView;
-(void)_handleEvent:(id)event;
-(id)nextResponder;
-(BOOL)_handleResponderCall:(int)call;
-(id)_initWithViewRef:(WKView*)viewRef;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)window;
-(WKView*)_viewRef;
-(id)_subviewReferences;
-(id)subviews;
-(id)superview;
-(id)lastScrollableAncestor;
-(void)addSubview:(id)subview;
-(void)willRemoveSubview:(id)subview;
-(void)removeFromSuperview;
-(void)viewDidMoveToWindow;
-(void)frameSizeChanged;
-(void)setNeedsDisplay:(BOOL)display;
-(void)setNeedsDisplayInRect:(CGRect)rect;
-(BOOL)needsDisplay;
-(void)display;
-(void)displayIfNeeded;
-(void)drawRect:(CGRect)rect;
-(void)viewWillDraw;
-(CGRect)bounds;
-(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(void)setFrameOrigin:(CGPoint)origin;
-(void)setFrameSize:(CGSize)size;
-(void)setBoundsSize:(CGSize)size;
-(void)displayRect:(CGRect)rect;
-(void)displayRectIgnoringOpacity:(CGRect)opacity;
-(void)displayRectIgnoringOpacity:(CGRect)opacity inContext:(CGContextRef)context;
-(CGRect)visibleRect;
-(CGPoint)convertPoint:(CGPoint)point toView:(id)view;
-(CGPoint)convertPoint:(CGPoint)point fromView:(id)view;
-(CGSize)convertSize:(CGSize)size toView:(id)view;
-(CGRect)convertRect:(CGRect)rect fromView:(id)view;
-(CGRect)convertRect:(CGRect)rect toView:(id)view;
-(void)lockFocus;
-(void)unlockFocus;
-(id)hitTest:(CGPoint)test;
-(void)setHidden:(BOOL)hidden;
-(BOOL)isDescendantOf:(id)of;
-(BOOL)mouse:(CGPoint)mouse inRect:(CGRect)rect;
-(BOOL)needsPanelToBecomeKey;
-(void)setNextKeyView:(id)view;
-(id)previousValidKeyView;
-(id)nextKeyView;
-(id)nextValidKeyView;
-(id)previousKeyView;
-(void)invalidateGState;
-(void)releaseGState;
-(BOOL)inLiveResize;
-(void)setAutoresizingMask:(unsigned)mask;
-(unsigned)autoresizingMask;
-(void)scrollPoint:(CGPoint)point;
-(BOOL)scrollRectToVisible:(CGRect)visible;
-(void)setNeedsLayout:(BOOL)layout;
-(void)layout;
-(void)layoutIfNeeded;
-(void)setScale:(float)scale;
-(float)scale;
-(void)_setDrawsOwnDescendants:(BOOL)descendants;
-(id)description;
-(void)_appendDescriptionToString:(id)string atLevel:(int)level;
@end

@interface WAKView (iPhoneAccessibility)
-(BOOL)accessibilityIsIgnored;
@end

