/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "WebCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WebCoreSharedBufferData : XXUnknownSuperclass {
@private
	RefPtr<WebCore::SharedBuffer> sharedBuffer;
}
+(void)initialize;
-(void)dealloc;
-(void)finalize;
-(id)initWithSharedBuffer:(SharedBuffer*)sharedBuffer;
-(unsigned)length;
-(const void*)bytes;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

