/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "WebCore-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface WebEventRegion : XXUnknownSuperclass <NSCopying> {
@private
	CGPoint p1;
	CGPoint p2;
	CGPoint p3;
	CGPoint p4;
}
-(id)initWithPoints:(CGPoint)points :(CGPoint)arg2 :(CGPoint)arg3 :(CGPoint)arg4;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(BOOL)hitTest:(CGPoint)test;
-(BOOL)isEqual:(id)equal;
-(FloatQuad)quad;
@end

