/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "WebCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface WebScriptObjectPrivate : XXUnknownSuperclass {
@private
	JSObject* imp;
	RootObject* rootObject;
	RootObject* originRootObject;
	BOOL isCreatedByDOMWrapper;
}
@end

