/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "NSObject.h"


@protocol HistoryItem <NSObject>
-(id)initWithDictionaryRepresentation:(id)dictionaryRepresentation;
-(id)dictionaryRepresentation;
-(int)type;
@end

