/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MKAccuracyLayer : XXUnknownSuperclass {
}
@property(assign) float accuracy;
@property(assign) float lineWidth;
@property(assign) CGColorRef strokeColor;
@property(assign) CGColorRef fillColor;
+(id)defaultValueForKey:(id)key;
+(CGRect)boundsForAccuracy:(float)accuracy;
+(CGRect)accuracyRectForPosition:(CGPoint)position accuracy:(float)accuracy;
+(BOOL)needsDisplayForKey:(id)key;
-(BOOL)isHoveringAnimation:(id*)animation;
-(BOOL)sizeToFitAccuracy;
-(BOOL)isAccuracyMinBounded:(float)bounded;
-(BOOL)isAccuracyMaxBounded:(float)bounded;
-(BOOL)isAccuracyBounded:(float)bounded;
-(BOOL)sizeToFitAccuracy:(float)fitAccuracy animated:(BOOL)animated;
-(void)drawInContext:(CGContextRef)context;
@end

