/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MKDate, MKSearchResult, NSMutableArray;

__attribute__((visibility("hidden")))
@interface MKDirectionsRouteInfo : XXUnknownSuperclass {
@private
	MKSearchResult* _startSearchResultRef;
	MKSearchResult* _endSearchResultRef;
	MKSearchResult* _routeStartSearchResult;
	MKSearchResult* _routeEndSearchResult;
	MKDate* _initialTransitRequestDate;
	NSMutableArray* _responses;
}
@property(retain, nonatomic) MKSearchResult* startSearchResultRef;
@property(retain, nonatomic) MKSearchResult* endSearchResultRef;
@property(retain, nonatomic) MKSearchResult* routeStartSearchResult;
@property(retain, nonatomic) MKSearchResult* routeEndSearchResult;
@property(retain, nonatomic) MKDate* initialTransitRequestDate;
@property(retain, nonatomic) NSMutableArray* responses;
+(id)routeInfo;
-(id)init;
-(void)dealloc;
-(id)description;
-(id)debugDescription;
@end

