/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class GMMLocation;

__attribute__((visibility("hidden")))
@interface MKLocationResult : XXUnknownSuperclass {
@private
	MKLocationRequester* _requester;
	GMMLocation* _location;
}
-(void)dealloc;
@end

