/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MKMiniTile : XXUnknownSuperclass {
}
-(id)init;
-(id)actionForKey:(id)key;
-(void)drawInContext:(CGContextRef)context;
@end

