/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray, NSMapTable, GMMMapPoint, MKStreetView, MKPanoramaLoaderProxy;
@protocol MKPanoramaThumbnailDelegate;

__attribute__((visibility("hidden")))
@interface MKPanoramaInternal : XXUnknownSuperclass {
@private
	MKPanoramaLoaderProxy* loaderProxy;
	NSString* panoramaID;
	NSMapTable* tileDataTable;
	unsigned throttleFlags;
	unsigned throttleTimeInterval;
	unsigned maxZoomLevel;
	CGImageRef mapImageRef;
	NSMapTable* thumbnails;
	id<MKPanoramaThumbnailDelegate> thumbView;
	CGSize imageSize;
	CGSize tileSize;
	BOOL cubic;
	GMMMapPoint* mapPoint;
	CADoublePoint coordinate;
	NSArray* annotations;
	NSString* streetNumber;
	NSString* streetName;
	MKStreetView* view;
	double yaw;
	double tiltYaw;
	double tiltPitch;
	double cameraPitch;
	double horizontalFOV;
	double minVisiblePitch;
	double maxVisiblePitch;
	float annotationHeight;
	float annotationHorizonHeight;
	BOOL hasMetadata;
	BOOL isDisabled;
	unsigned tileByteCount;
	unsigned heapTime;
	unsigned updateTime;
}
@end

