/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MKPanoramaInternal, NSString, GMMMapPoint, MKStreetView, NSArray;
@protocol MKPanoramaThumbnailDelegate;

@interface MKPanorama : XXUnknownSuperclass {
@private
	MKPanoramaInternal* _internal;
}
@property(readonly, assign, nonatomic) float annotationHorizonHeight;
@property(readonly, assign, nonatomic) float annotationHeight;
@property(readonly, assign, nonatomic) NSArray* annotations;
@property(readonly, assign, nonatomic) double maxVisiblePitch;
@property(readonly, assign, nonatomic) double minVisiblePitch;
@property(readonly, assign, nonatomic) double horizontalFOV;
@property(readonly, assign, nonatomic) double cameraPitch;
@property(readonly, assign, nonatomic) double tiltPitch;
@property(readonly, assign, nonatomic) double tiltYaw;
@property(readonly, assign, nonatomic) double yaw;
@property(assign, nonatomic) MKStreetView* view;
@property(readonly, assign, nonatomic) NSString* streetName;
@property(readonly, assign, nonatomic) NSString* streetNumber;
@property(readonly, assign, nonatomic) GMMMapPoint* mapPoint;
@property(readonly, assign, nonatomic) CADoublePoint coordinate;
@property(readonly, assign, nonatomic) BOOL hasCoordinate;
@property(readonly, assign, nonatomic) CGSize tileSize;
@property(readonly, assign, nonatomic) CGSize imageSize;
@property(assign, nonatomic) id<MKPanoramaThumbnailDelegate> thumbnailDelegate;
@property(assign, nonatomic) CGImageRef mapImageRef;
@property(readonly, assign, nonatomic) unsigned maxZoomLevel;
@property(readonly, assign, nonatomic) BOOL isServiceThrottled;
@property(readonly, assign, nonatomic) BOOL isDisabled;
@property(readonly, assign, nonatomic) NSString* panoramaID;
@property(readonly, assign, nonatomic) BOOL hasGeometry;
@property(readonly, assign, nonatomic) BOOL hasMetadata;
@property(readonly, assign, nonatomic) BOOL hasPreview;
@property(readonly, assign, nonatomic) BOOL isPresent;
@property(readonly, assign) id loader;
+(unsigned)tileByteCount;
+(void)incrementTileByteCount:(int)count;
+(double)nextFetchTime;
+(void)incrementNextFetchTime:(double)time;
+(BOOL)shouldDelayLoad:(double*)load;
-(id)initWithId:(id)anId imageSize:(CGSize)size tileSize:(CGSize)size3 maxZoomLevel:(unsigned)level;
-(id)initWithId:(id)anId;
-(void)dealloc;
-(id)thumbnailForCoordinate:(CADoublePoint)coordinate;
-(void)_setThumbnailData:(id)data forCoordinate:(CADoublePoint)coordinate;
-(void)_removeAllThumbnails;
-(void)setMapPoint:(id)point;
-(void)setAnnotations:(id)annotations;
-(BOOL)isSpheric;
-(BOOL)isCubic;
-(unsigned)tileByteCount;
-(void)setTileByteCount:(unsigned)count;
-(void)incrementTileByteCount:(int)count;
-(void)_updateGeometry;
-(void)getTileZoomLevel:(unsigned)level xCount:(unsigned*)count yCount:(unsigned*)count3;
-(unsigned)tileCountForZoomLevel:(unsigned)zoomLevel;
-(id)tilePathsForZoomLevel:(unsigned)zoomLevel;
-(void)addTileData:(id)data path:(int)path;
-(BOOL)hasTileDataForPath:(int)path;
-(id)tileDataForZoomLevel:(int)zoomLevel;
-(id)tileDataForPath:(int)path;
-(void)_updateTileByteCount;
-(void)removeTileDataAboveZoomLevel:(int)level;
-(void)removeAllTileData;
-(id)description;
-(double)throttleTimeInterval;
-(BOOL)_readDataProperties:(id)properties error:(id*)error;
-(BOOL)_readProjectionProperties:(id)properties error:(id*)error;
-(BOOL)_readAnotationProperties:(id)properties error:(id*)error;
-(BOOL)readMetadata:(id)metadata error:(id*)error;
-(id)_mapkit_cache_key;
-(unsigned)_mapkit_cache_accessTime;
-(void)set_mapkit_cache_accessTime:(unsigned)time;
-(void)compact:(unsigned)compact;
@end

