/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MKTiledLayer : XXUnknownSuperclass {
@private
	struct {
		unsigned displayBaseTiles : 1;
		unsigned delegateDisplayBaseTiles : 1;
		unsigned delegateRenderLayer : 1;
	} _flags;
}
@property(readonly, assign, nonatomic) CADoubleRect visibleDoubleRect;
+(CGSize)contentSize;
+(int)minZoomLevel;
+(int)maxZoomLevel;
+(unsigned)levelsOfDetail;
+(id)defaultValueForKey:(id)key;
+(double)fadeDuration;
+(unsigned)prefetchedTiles;
-(void)setDelegate:(id)delegate;
-(void)flush;
-(void)displayTilePath:(XXStruct_j8inqB*)path;
-(void)setNeedsDisplayInTilePath:(XXStruct_j8inqB*)tilePath;
-(void)displayBaseTiles;
-(void)display;
-(void)renderInContext:(CGContextRef)context;
@end

