/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MKUserLocationViewInternal;

__attribute__((visibility("hidden")))
@interface MKUserLocationAccuracyAnimation : XXUnknownSuperclass {
@private
	MKUserLocationViewInternal* viewImpl;
}
@property(assign) BOOL bouncedDot;
@property(retain, nonatomic) MKUserLocationViewInternal* viewImpl;
+(id)defaultValueForKey:(id)key;
-(id)init;
-(void)dealloc;
-(void)runActionForKey:(id)key object:(id)object arguments:(id)arguments;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
@end

