/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"
#import "CHBGraphicProperties.h"


__attribute__((visibility("hidden")))
@interface CHBGraphicProperties : XXUnknownSuperclass {
}
+(id)oadGraphicPropertiesFromXlChartFrameType:(XlChartFrameType*)xlChartFrameType state:(id)state;
+(id)oadGraphicPropertiesFromXlChartSeriesFormat:(const XlChartSeriesFormat*)xlChartSeriesFormat state:(id)state;
+(id)oadGraphicPropertiesFromState:(id)state xlLineStyle:(const XlChartLineStyle*)style xlFillStyle:(const XlChartFillStyle*)style3;
+(id)oadStrokeFrom:(const XlChartLineStyle*)from;
+(id)oadGraphicPropertiesFromXlMarkerStyle:(const XlChartMarkerStyle*)xlMarkerStyle complex:(bool)complex state:(id)state;
@end

@interface CHBGraphicProperties (Private)
+(id)mapPresetDashFromPattern:(int)pattern;
+(id)mapFillStyle:(const XlChartFillStyle*)style xlPictureFormat:(const XlChartPicF*)format state:(id)state;
+(id)mapFillStyleForMarker:(const XlChartMarkerStyle*)marker complex:(bool)complex state:(id)state;
+(id)mapAssociatedEscherObjectstate:(id)objectstate;
+(int)oaPresetDashTypeFromLinePatternEnum:(int)linePatternEnum;
+(float)widthFromLineWeightEnum:(int)lineWeightEnum;
+(int)presetLinePatternEnumFromDash:(id)dash;
+(int)lineWeightEnumFromWidth:(float)width;
@end

