/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "CHDAxis.h"
#import "EDKeyedObject.h"

@class OADGraphicProperties, CHDTitle, EDResources;

__attribute__((visibility("hidden")))
@interface CHDAxis : XXUnknownSuperclass <EDKeyedObject> {
@private
	bool mReverseOrder;
	bool mSecondary;
	bool mDateTimeFormattingFlag;
	bool mLineVisible;
	bool mDeleted;
	bool mAutoMinimumValue;
	bool mAutoMaximumValue;
	bool mAutoCrossValue;
	bool mContentFormatDerived;
	int mAxisId;
	unsigned mContentFormatId;
	int mFontIndex;
	double mScalingMaximum;
	double mScalingMinimum;
	int mOrientation;
	double mCrossAxisId;
	double mCrossesAt;
	int mMajorTickMark;
	int mMinorTickMark;
	int mAxisPosition;
	int mAxisType;
	int mTickLabelPosition;
	CHDTitle* mTitle;
	OADGraphicProperties* mMinorGridLinesGraphicProperties;
	OADGraphicProperties* mMajorGridLinesGraphicProperties;
	OADGraphicProperties* mAxisGraphicProperties;
	int mCrossBetween;
	int mCrosses;
	double mTickLabelRotation;
	bool mIsAutoRotation;
	int mTickLabelColorIndex;
	EDResources* mResources;
}
-(id)initWithResources:(id)resources;
-(void)dealloc;
-(int)axisId;
-(void)setAxisId:(int)anId;
-(bool)isReverseOrder;
-(void)setReverseOrder:(bool)order;
-(bool)isSecondary;
-(void)setSecondary:(bool)secondary;
-(bool)isLineVisible;
-(void)setLineVisible:(bool)visible;
-(bool)isDeleted;
-(void)setDeleted:(bool)deleted;
-(bool)isAutoMinimumValue;
-(bool)isAutoMaximumValue;
-(bool)isAutoCrossValue;
-(bool)isHorizontalPosition;
-(id)font;
-(void)setFont:(id)font;
-(id)contentFormat;
-(id)defaultDateTimeContentFormat;
-(void)setContentFormat:(id)format;
-(bool)isContentFormatDerivedFromDataPoints;
-(void)setIsContentFormatDerivedFromDataPoints:(bool)dataPoints;
-(double)scalingMaximum;
-(void)setScalingMaximum:(double)maximum;
-(double)scalingMinimum;
-(void)setScalingMinimum:(double)minimum;
-(int)orientation;
-(void)setOrientation:(int)orientation;
-(double)crossAxisId;
-(void)setCrossAxisId:(double)anId;
-(double)crossesAt;
-(void)setCrossesAt:(double)at;
-(int)majorTickMark;
-(void)setMajorTickMark:(int)mark;
-(int)minorTickMark;
-(void)setMinorTickMark:(int)mark;
-(int)axisPosition;
-(void)setAxisPosition:(int)position;
-(int)axisType;
-(void)setAxisType:(int)type;
-(int)tickLabelPosition;
-(void)setTickLabelPosition:(int)position;
-(bool)isTickLabelVisible;
-(id)title;
-(void)setTitle:(id)title;
-(id)minorGridLinesGraphicProperties;
-(void)setMinorGridLinesGraphicProperties:(id)properties;
-(id)majorGridLinesGraphicProperties;
-(void)setMajorGridLinesGraphicProperties:(id)properties;
-(id)axisGraphicProperties;
-(void)setAxisGraphicProperties:(id)properties;
-(int)crossBetween;
-(void)setCrossBetween:(int)between;
-(int)crosses;
-(void)setCrosses:(int)crosses;
-(unsigned)key;
-(bool)isDate;
-(bool)isDateTimeFormattingFlag;
-(void)setDateTimeFormattingFlag:(bool)flag;
-(double)tickLabelRotationAngle;
-(void)setTickLabelRotationAngle:(double)angle;
-(bool)isTickLabelAutoRotation;
-(void)setTickLabelAutoRotation:(bool)rotation;
-(void)adjustAxisPositionForHorizontalChart;
@end

@interface CHDAxis (EDInternal)
-(unsigned)contentFormatId;
-(void)setContentFormatId:(unsigned)anId;
-(int)fontIndex;
-(void)setFontIndex:(int)index;
-(int)tickLabelColorIndex;
-(void)setTickLabelColorIndex:(int)index;
@end

