/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "CHDAnchor.h"


__attribute__((visibility("hidden")))
@interface CHDAbsoluteSizeAnchor : CHDAnchor {
@private
	CGPoint mFrom;
	CGSize mSize;
}
-(CGPoint)from;
-(void)setFrom:(CGPoint)from;
-(CGSize)size;
-(void)setSize:(CGSize)size;
@end

