/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADDrawableContainer.h"
#import "OfficeImport-Structs.h"
#import "OADGraphic.h"

@class EDSheet, CHDPlotArea, NSMutableArray, CHDTitle, CHDDefaultTextProperties, EDWorkbook, CHDLegend, OADGraphicProperties, CHDView3D;

__attribute__((visibility("hidden")))
@interface CHDChart : OADGraphic <OADDrawableContainer> {
@private
	EDSheet* mSheet;
	int mStyleId;
	bool mAutoTitleDeleted;
	bool mPlotVisibleCellsOnly;
	bool mMSGraph;
	bool mDirectionChanged;
	int mDisplayBlankCellsAs;
	CHDPlotArea* mPlotArea;
	CHDView3D* mView3D;
	CHDTitle* mTitle;
	CHDLegend* mLegend;
	EDWorkbook* mExternalData;
	OADGraphicProperties* mChartAreaGraphicProperties;
	OADGraphicProperties* mBackWallGraphicProperties;
	OADGraphicProperties* mSideWallGraphicProperties;
	OADGraphicProperties* mFloorGraphicProperties;
	CHDDefaultTextProperties* mDefaultTextProperties;
	int mChartDirection;
	CGRect mLogicalBounds;
	NSMutableArray* mDrawables;
}
+(id)binaryEffects:(BOOL)effects;
-(id)init;
-(void)dealloc;
-(id)sheet;
-(void)setSheet:(id)sheet;
-(id)workbook;
-(id)processors;
-(int)styleId;
-(void)setStyleId:(int)anId;
-(bool)isAutoTitleDeleted;
-(void)setAutoTitleDeleted:(bool)deleted;
-(bool)isPlotVisibleCellsOnly;
-(void)setPlotVisibleCellsOnly:(bool)only;
-(int)displayBlankAs;
-(void)setDisplayBlankAs:(int)as;
-(id)plotArea;
-(void)setPlotArea:(id)area;
-(id)view3D;
-(void)setView3D:(id)d;
-(id)title;
-(void)setTitle:(id)title;
-(id)legend;
-(void)setLegend:(id)legend;
-(id)externalData;
-(void)setExternalData:(id)data;
-(id)chartAreaGraphicProperties;
-(void)setChartAreaGraphicProperties:(id)properties;
-(id)backWallGraphicProperties;
-(void)setBackWallGraphicProperties:(id)properties;
-(id)sideWallGraphicProperties;
-(void)setSideWallGraphicProperties:(id)properties;
-(id)floorGraphicProperties;
-(void)setFloorGraphicProperties:(id)properties;
-(id)defaultTextProperties;
-(void)setDefaultTextProperties:(id)properties;
-(int)direction;
-(void)setDirection:(int)direction;
-(CGRect)logicalBounds;
-(void)setLogicalBounds:(CGRect)bounds;
-(unsigned)childCount;
-(void)addChild:(id)child;
-(void)addChildren:(id)children;
-(id)childAtIndex:(unsigned)index;
-(id)children;
-(void)setParentTextListStyle:(id)style;
-(id)defaultThemeFont;
-(id)defaultTextFont;
-(id)defaultDataLabelFont;
-(id)defaultSeriesTitleFont;
-(unsigned)defaultFontIndex;
-(id)defaultContentFormat;
-(id)defaultFontWithResources:(id)resources;
-(int)defaultLabelPosition;
-(id)styleMatrix;
-(id)mainType;
-(bool)is3D;
-(bool)isBinary;
-(unsigned)seriesCount;
-(bool)isMSGraph;
-(void)setMSGraph:(bool)graph;
-(bool)isDirectionChanged;
-(void)setDirectionChanged:(bool)changed;
@end

