/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CHDFormula.h"
#import "EDFormula.h"

@class EDReferenceCollection, EDWorkbook;

__attribute__((visibility("hidden")))
@interface CHDFormula : EDFormula {
@private
	EDReferenceCollection* mReferences;
	EDWorkbook* mWorkbook;
}
+(id)formulaWithReference:(id)reference;
+(id)formulaWithReferences:(id)references;
-(id)initWithWorkbook:(id)workbook;
-(id)initWithReference:(id)reference;
-(id)initWithReferences:(id)references;
-(void)dealloc;
-(void)setWorkbook:(id)workbook;
-(id)references;
-(void)setReferences:(id)references;
-(unsigned)countOfCellsBeingReferenced;
-(void)prepareTokens;
@end

@interface CHDFormula (Private)
-(id)referencesFromFormula;
@end

