/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CHXDataValue.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CHXDataValue : XXUnknownSuperclass {
}
+(id)chdStringValueFromXmlDataValueElement:(xmlNode*)xmlDataValueElement state:(id)state;
+(id)chdNumberValueFromXmlDataValueElement:(xmlNode*)xmlDataValueElement state:(id)state;
@end

@interface CHXDataValue (Private)
+(id)chdDataValueFromXmlDataValueElement:(xmlNode*)xmlDataValueElement state:(id)state;
@end

