/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "CHXDataValueProperties.h"


__attribute__((visibility("hidden")))
@interface CHXDataValueProperties : XXUnknownSuperclass {
}
+(id)readFrom:(xmlNode*)from state:(id)state;
+(id)chdDataValuePropertiesFromXmlElement:(xmlNode*)xmlElement state:(id)state;
@end

@interface CHXDataValueProperties (Private)
+(Class)chxDataValuePropertiesClassWithState:(id)state;
@end

