/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "CMDiagramMapper.h"
#import "CMDiagramShapeMapper.h"

@class OADOrientedBounds, NSString;

__attribute__((visibility("hidden")))
@interface CMDiagramShapeMapper : CMDiagramMapper {
@private
	int mChildCount;
	OADOrientedBounds* mDiagramShapeBounds;
	NSString* mIdentifier;
	float mDefaultFontSize;
	int mMaxMappableTreeDepth;
	float mDefaultScale;
}
-(id)initWithOddDiagram:(id)oddDiagram drawingContext:(id)context orientedBounds:(id)bounds identifier:(id)identifier parent:(id)parent;
-(void)mapAt:(id)at withState:(id)state;
-(CGRect)circumscribedBounds;
-(void)mapChildrenAt:(id)at withState:(id)state;
-(float)defaultFontSize;
-(void)setDefaultFonSize;
-(void)setFonSizeForChildNode:(id)childNode atIndex:(unsigned)index;
-(CGSize)textSizeForShapeSize:(CGSize)shapeSize;
-(float)setFonSizeForChildNode:(id)childNode atIndex:(unsigned)index level:(int)level;
-(CGSize)sizeForNode:(id)node atIndex:(unsigned)index;
@end

@interface CMDiagramShapeMapper (Private)
@end

