/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CMMapperRootArchiver.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CMMapper : XXUnknownSuperclass <CMMapperRootArchiver> {
@private
	CMMapper* mParent;
}
-(id)initWithParent:(id)parent;
-(void)setParent:(id)parent;
-(id)parent;
-(id)root;
-(id)archiver;
-(void)addAttribute:(id)attribute toNode:(id)node value:(id)value;
-(void)addStyleUsingGlobalCacheTo:(id)to style:(id)style;
-(void)addStyleUsingGlobalCacheTo:(id)to style:(id)style embedStyle:(BOOL)style3;
-(void)addStyle:(id)style withName:(id)name;
-(void)mapAt:(id)at withState:(id)state;
-(void)mapStylesheetAt:(id)at stylesheet:(id)stylesheet;
-(void)startMappingWithState:(id)state;
-(void)mapElement:(id)element atIndex:(unsigned)index withState:(id)state isLastElement:(BOOL)element4;
-(void)finishMappingWithState:(id)state;
@end

