/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CPTracing.h"


__attribute__((visibility("hidden")))
@interface CPImportTracing : CPTracing {
@private
	long mReadingOpstat;
	long mProcessorOpstat;
	long mImportingOpstat;
}
-(id)initWithFilename:(id)filename;
-(void)dealloc;
-(void)startReading;
-(void)stopReading;
-(void)startProcessors;
-(void)stopProcessors;
-(void)startImporting;
-(void)stopImporting;
@end

