/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EBProtection : XXUnknownSuperclass {
}
+(id)edProtectionFromXlXf:(XlXf*)xlXf;
+(id)edProtectionFromXlDXfProtect:(XlDXfProtect*)xlDXfProtect;
+(id)edProtectionFromXlGraphicsInfo:(XlGraphicsInfo*)xlGraphicsInfo;
+(XlDXfProtect*)xlDXfProtectFromEDProtection:(id)edprotection;
@end

