/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "TSUPointerKeyDictionary.h"


__attribute__((visibility("hidden")))
@interface ECPointerNilKeyDictionary : TSUPointerKeyDictionary {
@private
	id mNilKeyObject;
}
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
@end

