/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "EDTable.h"

@class EDCollection, NSString, EDReference, EDResources;

__attribute__((visibility("hidden")))
@interface EDTable : XXUnknownSuperclass {
@private
	EDResources* mResources;
	unsigned mStyleIndex;
	unsigned mHeaderRowDxfIndex;
	unsigned mTotalsRowDxfIndex;
	unsigned mDataAreaDxfIndex;
	unsigned mHeaderRowBorderDxfIndex;
	unsigned mTotalsRowBorderDxfIndex;
	unsigned mDataAreaBorderDxfIndex;
	unsigned mTableBorderDxfIndex;
	NSString* mName;
	NSString* mDisplayName;
	EDReference* mTableRange;
	NSString* mStyleName;
	unsigned mHeaderRowCount;
	unsigned mTotalsRowCount;
	bool mShowFirstColumn;
	bool mShowLastColumn;
	bool mShowRowStripes;
	bool mShowColumnStripes;
	EDCollection* mTableColumns;
}
+(id)tableWithResources:(id)resources;
-(id)initWithResources:(id)resources;
-(void)dealloc;
-(id)style;
-(void)setStyle:(id)style;
-(id)headerRowDxf;
-(void)setHeaderRowDxf:(id)dxf;
-(id)totalsRowDxf;
-(void)setTotalsRowDxf:(id)dxf;
-(id)dataAreaDxf;
-(void)setDataAreaDxf:(id)dxf;
-(id)headerRowBorderDxf;
-(void)setHeaderRowBorderDxf:(id)dxf;
-(id)totalsRowBorderDxf;
-(void)setTotalsRowBorderDxf:(id)dxf;
-(id)dataAreaBorderDxf;
-(void)setDataAreaBorderDxf:(id)dxf;
-(id)tableBorderDxf;
-(void)setTableBorderDxf:(id)dxf;
-(id)name;
-(void)setName:(id)name;
-(id)displayName;
-(void)setDisplayName:(id)name;
-(id)styleName;
-(void)setStyleName:(id)name;
-(id)tableRange;
-(unsigned)headerRowCount;
-(void)setHeaderRowCount:(unsigned)count;
-(unsigned)totalsRowCount;
-(void)setTotalsRowCount:(unsigned)count;
-(id)tableColumns;
-(bool)showFirstColumn;
-(void)setShowFirstColumn:(bool)column;
-(bool)showLastColumn;
-(void)setShowLastColumn:(bool)column;
-(bool)showRowStripes;
-(void)setShowRowStripes:(bool)stripes;
-(bool)showColumnStripes;
-(void)setShowColumnStripes:(bool)stripes;
-(void)setTableRange:(id)range;
@end

@interface EDTable (EDInternal)
-(unsigned)styleIndex;
-(void)setStyleIndex:(unsigned)index;
-(unsigned)headerRowDxfIndex;
-(void)setHeaderRowDxfIndex:(unsigned)index;
-(unsigned)totalsRowDxfIndex;
-(void)setTotalsRowDxfIndex:(unsigned)index;
-(unsigned)dataAreaDxfIndex;
-(void)setDataAreaDxfIndex:(unsigned)index;
-(unsigned)headerRowBorderDxfIndex;
-(void)setHeaderRowBorderDxfIndex:(unsigned)index;
-(unsigned)totalsRowBorderDxfIndex;
-(void)setTotalsRowBorderDxfIndex:(unsigned)index;
-(unsigned)dataAreaBorderDxfIndex;
-(void)setDataAreaBorderDxfIndex:(unsigned)index;
-(unsigned)tableBorderDxfIndex;
-(void)setTableBorderDxfIndex:(unsigned)index;
@end

