/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EDTokenTreeNode : XXUnknownSuperclass {
@private
	unsigned mTokenIndex;
	int mTokenType;
	EDTokenTreeNode* mFirstChild;
	EDTokenTreeNode* mSibling;
}
+(id)tokenTreeNodeWithIndexAndType:(unsigned)indexAndType type:(int)type;
-(id)init;
-(id)initWithIndexAndType:(unsigned)indexAndType type:(int)type;
-(void)dealloc;
-(unsigned)tokenIndex;
-(id)firstChild;
-(void)setFirstChild:(id)child;
-(id)sibling;
-(void)setSibling:(id)sibling;
@end

