/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "NSObject.h"


@protocol EFHelper <NSObject>
-(unsigned)resolveName:(id)name;
-(unsigned)resolveSheet:(id)sheet;
-(unsigned)resolveFirstSheet:(id)sheet lastSheet:(id)sheet2;
-(unsigned)resolveFile:(id)file;
-(id)resolveTable:(id)table;
-(unsigned)resolveTableToSheetId:(id)sheetId;
-(unsigned)resolveTableColumn:(id)column columnName:(id)name;
-(BOOL)isCurrentSheet:(id)sheet;
-(int)resolveFunctionName:(id)name;
-(bool)isThereContentOutsideOfLassoBoundsForRowMin:(unsigned)rowMin rowMax:(unsigned)max columnMin:(unsigned)min columnMax:(unsigned)max4;
-(int)rowNumber;
-(int)columnNumber;
@end

