/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "EDProcessor.h"
#import "EPStyleFlattener.h"

@class NSArray, NSMutableArray, EDWorksheet, EDRowBlocks, EDRowBlock, EDColumnInfoCollection;

__attribute__((visibility("hidden")))
@interface EPStyleFlattener : EDProcessor {
@private
	EDWorksheet* mWorksheet;
	EDRowBlocks* mRowBlocks;
	EDRowBlock* mCurrentRowBlock;
	EDColumnInfoCollection* mColumnInfos;
	NSArray* mKeys;
	NSMutableArray* mRanges;
	int mFirstRow;
	int mLastRow;
	int mFirstColumn;
	int mLastColumn;
	unsigned mFirstRowStripeSize;
	unsigned mSecondRowStripeSize;
	unsigned mFirstColumnStripeSize;
	unsigned mSecondColumnStripeSize;
}
-(void)dealloc;
-(void)applyProcessorToObject:(id)object sheet:(id)sheet;
@end

@interface EPStyleFlattener (EPInternal)
-(id)collectionFromWorksheet:(id)worksheet;
-(id)styleFromObject:(id)object;
-(id)wrapDifferentialStyleInATableStyleElement:(id)atableStyleElement type:(int)type;
-(id)extractKeys:(id)keys from:(id)from parent:(id)parent;
-(id)extractGlobalStyleElements:(id)elements;
-(id)extractRowStyleElements:(id)elements parentScope:(id)scope row:(int)row;
-(id)extractCellStyleElements:(id)elements parentScope:(id)scope row:(int)row column:(int)column;
-(id)keysInTheOrderTheyShouldBeApplied;
-(int)borderFlagsForStyleType:(int)styleType row:(int)row column:(int)column;
-(void)cacheRange:(id)range;
-(void)cacheSizes:(id)sizes inObject:(id)object;
-(void)clearCache;
@end

@interface EPStyleFlattener (Private)
-(void)processObject:(id)object;
-(EDCellHeader*)cellWithSetupStyleAtRowNumber:(int)rowNumber columnNumber:(int)number;
-(void)applyStyleElements:(id)elements toCell:(EDCellHeader*)cell row:(int)row column:(int)column;
-(void)applyDifferentialStyle:(id)style borderFlags:(int)flags precedence:(int)precedence toCell:(EDCellHeader**)cell row:(int)row column:(int)column;
-(id)flattenBorders:(id)borders differentialBorders:(id)borders2 borderFlags:(int)flags precedence:(int)precedence row:(int)row column:(int)column isBordersCopied:(bool*)copied;
-(id)flattenBorder:(int)border borders:(id)borders differentialBorders:(id)borders3 flag:(bool)flag precedence:(int)precedence row:(int)row column:(int)column isBorderCopied:(bool*)copied;
-(id)flattenFill:(id)fill differentialFill:(id)fill2 isFillCopied:(bool*)copied;
-(id)flattenFont:(id)font differentialFont:(id)font2 isFontCopied:(bool*)copied;
@end

