/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EXWorkbook.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EXWorkbook : XXUnknownSuperclass {
}
+(id)edWorkbookFromState:(id)state package:(id)package reader:(id)reader fileName:(id)name temporaryDirectory:(id)directory;
+(id)edWorkbookFromState:(id)state package:(id)package reader:(id)reader resourcesOnly:(bool)only fileName:(id)name temporaryDirectory:(id)directory;
@end

@interface EXWorkbook (Private)
+(void)readSheetsFrom:(id)from relationNS:(xmlNs*)ns state:(id)state;
+(void)readStylesFrom:(id)from state:(id)state;
+(void)readStringsFrom:(id)from state:(id)state;
+(void)setupProcessors:(id)processors;
@end

