/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "MFCocoaBrush.h"

@class NSColorStub;

__attribute__((visibility("hidden")))
@interface MFCocoaSolidBrush : MFCocoaBrush {
@private
	NSColorStub* m_colour;
}
+(id)solidBrushWithColour:(id)colour;
-(id)initWithColour:(id)colour;
-(void)dealloc;
-(void)fillPath:(id)path :(id)arg2;
@end

