/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "MFCocoaBrush.h"


__attribute__((visibility("hidden")))
@interface MFCocoaNullBrush : MFCocoaBrush {
}
+(id)nullBrush;
-(void)fillPath:(id)path :(id)arg2;
@end

