/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "OADBlipEffect.h"


__attribute__((visibility("hidden")))
@interface OADLuminanceEffect : OADBlipEffect {
@private
	float mBrightness;
	float mContrast;
}
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
-(float)brightness;
-(void)setBrightness:(float)brightness;
-(float)contrast;
-(void)setContrast:(float)contrast;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
@end

