/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADParagraph.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, OADParagraphProperties, OADCharacterProperties;

__attribute__((visibility("hidden")))
@interface OADParagraph : XXUnknownSuperclass {
@private
	OADParagraphProperties* mProperties;
	NSMutableArray* mTextRuns;
	OADCharacterProperties* mParagraphEndCharacterProperties;
}
-(id)init;
-(void)dealloc;
-(id)properties;
-(void)setProperties:(id)properties;
-(BOOL)isEmpty;
-(unsigned)textRunCount;
-(id)textRunAtIndex:(unsigned)index;
-(id)addTextLineBreak;
-(id)addRegularTextRun;
-(id)addGenericTextField;
-(id)addDateTimeField;
-(id)addFooterField;
-(id)paragraphEndCharacterProperties;
-(void)setParagraphEndCharacterProperties:(id)properties;
-(BOOL)hasBulletCharacterProperties;
-(id)bulletCharacterProperties;
-(void)setParentTextListStyle:(id)style;
-(void)applyProperties:(id)properties;
-(void)removeUnnecessaryOverrides;
-(id)plainText;
@end

@interface OADParagraph (PDTextField)
-(id)addSlideNumberField;
@end

@interface OADParagraph (FieldAdditions)
-(id)findFirstTextRunOfClass:(Class)aClass;
@end

