/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADCharacterProperties.h"

@class OADBulletSize, NSMutableArray, OADBulletProperties, OADTextSpacing, OADBulletFont, OADBulletColor;

__attribute__((visibility("hidden")))
@interface OADParagraphProperties : OADCharacterProperties {
@private
	OADBulletSize* mBulletSize;
	OADBulletColor* mBulletColor;
	OADBulletFont* mBulletFont;
	OADBulletProperties* mBulletProperties;
	OADTextSpacing* mLineSpacing;
	OADTextSpacing* mBeforeSpacing;
	OADTextSpacing* mAfterSpacing;
	NSMutableArray* mTabStops;
	double mLeftMargin;
	double mRightMargin;
	double mIndent;
	double mDefaultTab;
	int mLevel;
	int mBulletCharSet;
	unsigned char mAlign;
	unsigned char mWrap;
	unsigned char mFontAlign;
	unsigned mIsRightToLeft : 1;
	unsigned mIsLatinLineBreak : 1;
	unsigned mIsHangingPunctuation : 1;
	unsigned mHasTabStops : 1;
	unsigned mHasLeftMargin : 1;
	unsigned mHasRightMargin : 1;
	unsigned mHasLevel : 1;
	unsigned mHasIndent : 1;
	unsigned mHasAlign : 1;
	unsigned mHasDefaultTab : 1;
	unsigned mHasIsRightToLeft : 1;
	unsigned mHasWrap : 1;
	unsigned mHasFontAlign : 1;
	unsigned mHasIsLatinLineBreak : 1;
	unsigned mHasIsHangingPunctuation : 1;
	unsigned mHasBulletCharSet : 1;
}
@property(assign, nonatomic) int bulletCharSet;
@property(assign, nonatomic) BOOL hasBulletCharSet;
+(id)defaultProperties;
-(id)init;
-(id)initWithDefaults;
-(void)dealloc;
-(BOOL)hasLineSpacing;
-(id)lineSpacing;
-(void)setLineSpacing:(id)spacing;
-(BOOL)hasBeforeSpacing;
-(id)beforeSpacing;
-(void)setBeforeSpacing:(id)spacing;
-(BOOL)hasAfterSpacing;
-(id)afterSpacing;
-(void)setAfterSpacing:(id)spacing;
-(BOOL)hasTabStops;
-(unsigned)tabStopCount;
-(id)tabStopAtIndex:(unsigned)index;
-(id)addTabStop;
-(void)clearTabStops;
-(id)tabStops;
-(BOOL)hasLeftMargin;
-(double)leftMargin;
-(void)setLeftMargin:(double)margin;
-(double)nonOveridenLeftMargin;
-(BOOL)hasRightMargin;
-(double)rightMargin;
-(void)setRightMargin:(double)margin;
-(BOOL)hasLevel;
-(int)level;
-(void)setLevel:(int)level;
-(BOOL)hasIndent;
-(double)indent;
-(void)setIndent:(double)indent;
-(BOOL)hasAlign;
-(int)align;
-(void)setAlign:(int)align;
-(BOOL)hasDefaultTab;
-(double)defaultTab;
-(void)setDefaultTab:(double)tab;
-(BOOL)hasIsRightToLeft;
-(BOOL)isRightToLeft;
-(void)setIsRightToLeft:(BOOL)left;
-(BOOL)hasWrap;
-(int)wrap;
-(void)setWrap:(int)wrap;
-(BOOL)hasFontAlign;
-(int)fontAlign;
-(void)setFontAlign:(int)align;
-(BOOL)hasIsLatinLineBreak;
-(BOOL)isLatinLineBreak;
-(void)setIsLatinLineBreak:(BOOL)aBreak;
-(BOOL)hasIsHangingPunctuation;
-(BOOL)isHangingPunctuation;
-(void)setIsHangingPunctuation:(BOOL)punctuation;
-(BOOL)hasBulletSize;
-(id)bulletSize;
-(void)setBulletSize:(id)size;
-(BOOL)hasBulletColor;
-(id)bulletColor;
-(void)setBulletColor:(id)color;
-(BOOL)hasBulletFont;
-(id)bulletFont;
-(void)setBulletFont:(id)font;
-(BOOL)hasBulletProperties;
-(id)bulletProperties;
-(void)setBulletProperties:(id)properties;
-(void)overrideWithProperties:(id)properties;
-(void)removeUnnecessaryOverrides;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
@end

