/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class OADTableCellBorderStyle, OADFill;

__attribute__((visibility("hidden")))
@interface OADTableCellStyle : XXUnknownSuperclass {
@private
	OADTableCellBorderStyle* mBorderStyle;
	OADFill* mFill;
}
+(id)defaultFill;
+(id)defaultStyle;
-(void)dealloc;
-(id)borderStyle;
-(void)setBorderStyle:(id)style;
-(id)fill;
-(void)setFill:(id)fill;
-(id)shallowCopy;
-(void)applyOverridesFrom:(id)from;
@end

