/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OAXColorTransform.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OAXColorTransform : XXUnknownSuperclass {
}
+(id)readColorTransformsFromXmlNode:(xmlNode*)xmlNode;
@end

@interface OAXColorTransform (Private)
+(id)colorTransformTypeEnumMap;
@end

