/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "ODILayoutNode.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"

@class NSMutableArray, ODDPoint, ODDAlgorithm, ODDShape;

__attribute__((visibility("hidden")))
@interface ODILayoutNode : XXUnknownSuperclass {
@private
	ODDPoint* mPoint;
	ODDAlgorithm* mAlgorithm;
	ODDShape* mShape;
	NSMutableArray* mChildren;
}
-(id)initWithLayoutNode:(id)layoutNode point:(id)point;
-(void)dealloc;
@end

@interface ODILayoutNode (Private)
-(id)initWithLayoutNode:(id)layoutNode state:(ODILayoutNodeState*)state;
-(void)processLayoutObjects:(id)objects state:(ODILayoutNodeState*)state;
-(void)processLayoutNode:(id)node state:(ODILayoutNodeState*)state;
-(void)processChoose:(id)choose state:(ODILayoutNodeState*)state;
-(void)processForEach:(id)each state:(ODILayoutNodeState*)state;
-(void)processAlgorithm:(id)algorithm state:(ODILayoutNodeState*)state;
-(void)processShape:(id)shape state:(ODILayoutNodeState*)state;
@end

