/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "ODIPyramid.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ODIPyramid : XXUnknownSuperclass {
}
+(BOOL)mapIdentifier:(id)identifier state:(id)state;
@end

@interface ODIPyramid (Private)
+(void)addTrapezoidForNode:(id)node top:(float)top height:(float)height topBase:(float)base bottomBase:(float)base5 state:(id)state;
+(void)mapWithState:(id)state apexUp:(BOOL)up;
+(unsigned)nodeCountWithState:(id)state;
+(BOOL)verticalFlipWithState:(id)state;
@end

