/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "ODXData.h"


__attribute__((visibility("hidden")))
@interface ODXData : XXUnknownSuperclass {
}
+(void)readNode:(xmlNode*)node toDiagram:(id)diagram state:(id)state;
+(id)readModelIdentifierFromNode:(xmlNode*)node attributeName:(const char*)name;
@end

@interface ODXData (Private)
+(id)readPointListFromNode:(xmlNode*)node pointIdMap:(id)map state:(id)state;
+(id)readPointFromNode:(xmlNode*)node pointIdMap:(id)map state:(id)state;
+(int)readPointTypeFromNode:(xmlNode*)node;
+(void)readConnectionListFromNode:(xmlNode*)node pointIdMap:(id)map state:(id)state;
+(void)readConnectionFromNode:(xmlNode*)node pointIdMap:(id)map state:(id)state;
+(int)readConnectionTypeFromNode:(xmlNode*)node;
+(void)associatePresentationsInIdMap:(id)idMap;
@end

