/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class OAXDrawingState;

__attribute__((visibility("hidden")))
@interface ODXState : XXUnknownSuperclass {
@private
	OAXDrawingState* mOfficeArtState;
}
-(id)initWithOfficeArtState:(id)officeArtState;
-(void)dealloc;
-(id)officeArtState;
@end

