/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PBOutlineBulletDictionary : XXUnknownSuperclass {
@private
	NSMutableDictionary* mDictionary;
}
-(id)initFromContainer:(id)container objectType:(unsigned)type;
-(void)dealloc;
-(id)objectForSlideId:(unsigned long)slideId textType:(int)type placeholderIndex:(unsigned long)index;
@end

