/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"
#import "PBTextBlock.h"


__attribute__((visibility("hidden")))
@interface PBTextBlock : XXUnknownSuperclass {
}
+(void)readClientTextBox:(id)box textBody:(id)body state:(id)state;
@end

@interface PBTextBlock (Private)
+(void)styledText:(CFAttributedStringRef)text textBlock:(id)block;
+(void)styledPargraphs:(CFArrayRef)pargraphs styledText:(CFAttributedStringRef)text;
+(void)readParagraph:(id)paragraph paragraph:(CFAttributedStringRef)paragraph2 textType:(int)type state:(id)state;
+(void)applyTextRuler:(PptTextRulerAtom*)ruler toTextBlock:(id)textBlock;
@end

