/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "PDCommonBehaviorData.h"


__attribute__((visibility("hidden")))
@interface PDAnimateRotateBehavior : PDCommonBehaviorData {
@private
	double mTo;
	double mFrom;
	double mBy;
}
-(id)init;
-(double)to;
-(void)setTo:(double)to;
-(double)from;
-(void)setFrom:(double)from;
-(double)by;
-(void)setBy:(double)by;
@end

