/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSValue, NSString;

__attribute__((visibility("hidden")))
@interface PDBuildMapKey : XXUnknownSuperclass {
@private
	NSValue* mDrawableValue;
	NSString* mGroupId;
}
-(id)init;
-(id)initWithDrawable:(id)drawable groupId:(id)anId;
-(void)dealloc;
-(id)drawable;
-(void)setDrawable:(id)drawable;
-(id)groupId;
-(void)setGroupId:(id)anId;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)copyWithZone:(NSZone*)zone;
@end

