/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "PDTransitionOptions.h"


__attribute__((visibility("hidden")))
@interface PDEightDirectionOptions : PDTransitionOptions {
@private
	int mDirection;
}
-(int)direction;
-(void)setDirection:(int)direction;
@end

