/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "PDSlideChild.h"

@class PDSlideMaster;

__attribute__((visibility("hidden")))
@interface PDSlideLayout : PDSlideChild {
@private
	int mSlideLayoutType;
	PDSlideMaster* mSlideMaster;
}
-(id)initWithSlideMaster:(id)slideMaster;
-(void)dealloc;
-(int)slideLayoutType;
-(void)setSlideLayoutType:(int)type;
-(id)slideMaster;
-(void)setSlideMaster:(id)master;
-(id)defaultTheme;
-(id)parentTextBodyPropertiesForPlaceholderType:(int)placeholderType placeholderTypeIndex:(int)index;
-(id)parentTextStyleForPlaceholderType:(int)placeholderType placeholderTypeIndex:(int)index defaultTextListStyle:(id)style;
-(id)parentTextStyleForTables;
-(id)parentShapePropertiesForPlaceholderType:(int)placeholderType placeholderTypeIndex:(int)index;
-(id)masterGraphicForPlaceholderType:(int)placeholderType placeholderTypeIndex:(int)index;
-(id)parentSlideBase;
-(void)doneWithContent;
@end

