/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "CMMapper.h"
#import "PMSlideMapper.h"

@class PDSlideBase;

__attribute__((visibility("hidden")))
@interface PMSlideMapper : CMMapper {
@private
	PDSlideBase* mSlide;
	CGRect mRect;
}
-(id)initWithPDSlide:(id)pdslide slideRect:(CGRect)rect parent:(id)parent;
-(id)slideName;
-(id)defaultTheme;
-(id)styleMatrix;
-(void)mapAt:(id)at withState:(id)state;
-(CGRect)slideRect;
@end

@interface PMSlideMapper (Private)
-(void)mapMasterSlideAt:(id)at withState:(id)state;
-(void)mapBackgroundAt:(id)at recursive:(BOOL)recursive withState:(id)state;
-(void)mapDrawablesAt:(id)at withState:(id)state;
-(void)mapMasterGraphicsAt:(id)at withState:(id)state;
@end

