/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "PXOfficeArtClient.h"
#import "OAXClient.h"

@class PXPresentationState;

__attribute__((visibility("hidden")))
@interface PXOfficeArtClient : OAXClient {
@private
	PXPresentationState* mPresentationState;
}
-(id)initWithState:(id)state;
-(id)presentationState;
-(void)readClientDataFromShapeNode:(xmlNode*)shapeNode toShape:(id)shape state:(id)state;
-(void)readClientDataFromPictureNode:(xmlNode*)pictureNode toImage:(id)image state:(id)state;
-(void)readClientDataFromGraphicalFramePropertiesNode:(xmlNode*)graphicalFramePropertiesNode toDrawable:(id)drawable state:(id)state;
-(id)readClientTextField:(xmlNode*)field paragraph:(id)paragraph state:(id)state;
-(void)postprocessHyperlink:(id)hyperlink relationship:(id)relationship state:(id)state;
-(id)readOle:(xmlNode*)ole state:(id)state;
@end

@interface PXOfficeArtClient (Private)
+(int)readPlaceholderTypeFromNode:(xmlNode*)node;
+(int)readPlaceholderBoundsTrackFromNode:(xmlNode*)node;
@end

