/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"
#import "TSUProgressContext.h"

@class NSDate, TSUProgressStage;

__attribute__((visibility("hidden")))
@interface TSUProgressContext : XXUnknownSuperclass {
@private
	TSUProgressStage* m_currentStage;
	NSDate* m_lastReportTime;
	double m_lastProgressReport;
}
+(id)_singletonAlloc;
+(id)sharedContext;
+(id)allocWithZone:(NSZone*)zone;
+(void)reset;
+(void)addProgressObserver:(id)observer selector:(SEL)selector;
+(void)removeProgressObserver:(id)observer;
+(void)createStageWithSteps:(double)steps takingSteps:(double)steps2;
+(void)createStageWithSteps:(double)steps;
+(void)nextSubStageWillTakeThisManyOfMySteps:(double)nextSubStage;
+(void)endStage;
+(void)advanceProgress:(double)progress;
+(void)setProgress:(double)progress;
+(void)setPercentageProgressFromCPProgressContext:(double)cpprogressContext;
+(void)setMessage:(id)message;
+(double)currentPosition;
+(double)overallProgress;
-(id)retain;
-(unsigned)retainCount;
-(void)release;
-(id)autorelease;
-(id)copyWithZone:(NSZone*)zone;
@end

@interface TSUProgressContext (Private)
-(id)init;
-(void)dealloc;
-(void)_reset;
-(id)currentStage;
-(void)reportProgress:(double)progress;
@end

