/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"
#import "NSMutableCopying.h"
#import "OfficeImport-Structs.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface TSUPair : XXUnknownSuperclass <NSCopying, NSMutableCopying, NSCoding> {
@private
	id mFirst;
	id mSecond;
}
+(id)pairWithFirst:(id)first second:(id)second;
+(id)pairWithPair:(id)pair;
+(id)pair;
-(id)initWithFirst:(id)first second:(id)second;
-(id)initWithPair:(id)pair;
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)first;
-(id)second;
-(void)p_SetFirst:(id)first;
-(void)p_SetSecond:(id)second;
@end

