/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WBFontTable : XXUnknownSuperclass {
}
+(void)readFrom:(id)from fontTable:(id)table;
+(void)readFromFontTable:(id)fontTable wrdFontTable:(WrdFontFamilyNameTable*)table fontTable:(id)table3;
@end

