/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "WBStyleSheet.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "OfficeImport-Structs.h"


__attribute__((visibility("hidden")))
@interface WBStyleSheet : XXUnknownSuperclass {
}
+(void)readFrom:(id)from styleSheet:(id)sheet;
@end

@interface WBStyleSheet (Private)
+(void)initializeStyles:(id)styles with:(WrdStyleSheet*)with reader:(id)reader;
@end

