/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WDABoundingBox : XXUnknownSuperclass {
@private
	CGRect mRect;
	float mRotation;
	BOOL mFlipX;
	BOOL mFlipY;
}
-(id)initWithRect:(CGRect)rect rotation:(float)rotation flipX:(BOOL)x flipY:(BOOL)y;
-(CGRect)rect;
-(void)setRect:(CGRect)rect;
-(float)rotation;
-(void)setRotation:(float)rotation;
-(BOOL)flipX;
-(void)setFlipX:(BOOL)x;
-(BOOL)flipY;
-(void)setFlipY:(BOOL)y;
@end

