/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WDCharacterProperties.h"
#import "OfficeImport-Structs.h"

@class WDDocument;

__attribute__((visibility("hidden")))
@interface WDCharacterProperties : XXUnknownSuperclass {
@private
	WDDocument* mDocument;
	unsigned mOriginal : 1;
	unsigned mTracked : 1;
	unsigned mResolved : 1;
	XXStruct_FJp71A mOriginalProperties;
	XXStruct_FJp71A mTrackedProperties;
}
+(SEL)fontSelectorForLanguageType:(int)languageType;
+(SEL)fontOverriddenSelectorForLanguageType:(int)languageType;
-(id)initWithDocument:(id)document;
-(void)dealloc;
-(id)document;
-(BOOL)isAnythingOverridden;
-(int)resolveMode;
-(void)setResolveMode:(int)mode;
-(void)negateFormattingChangesWithDefaults:(id)defaults;
-(void)applyPropertiesFrom:(id)from ifOverriddenIn:(id)anIn;
-(void)removeEmptyFormattingChanges:(id)changes;
-(id)baseStyle;
-(void)setBaseStyle:(id)style;
-(BOOL)isBaseStyleOverridden;
-(void)clearBaseStyle;
-(id)border;
-(id)mutableBorder;
-(BOOL)isBorderOverridden;
-(id)shading;
-(id)mutableShading;
-(BOOL)isShadingOverridden;
-(id)font;
-(void)setFont:(id)font;
-(BOOL)isFontOverridden;
-(id)extendedFont;
-(void)setExtendedFont:(id)font;
-(BOOL)isExtendedFontOverridden;
-(id)farEastFont;
-(void)setFarEastFont:(id)font;
-(BOOL)isFarEastFontOverridden;
-(id)symbolFont;
-(void)setSymbolFont:(id)font;
-(BOOL)isSymbolFontOverridden;
-(id)fontForLanguageType:(int)languageType;
-(BOOL)isFontOverriddenForLanguageType:(int)languageType;
-(unsigned short)symbolCharacter;
-(void)setSymbolCharacter:(unsigned short)character;
-(BOOL)isSymbolCharacterOverridden;
-(int)bold;
-(void)setBold:(int)bold;
-(BOOL)isBoldOverridden;
-(int)italic;
-(void)setItalic:(int)italic;
-(BOOL)isItalicOverridden;
-(int)outline;
-(void)setOutline:(int)outline;
-(BOOL)isOutlineOverridden;
-(int)embossed;
-(void)setEmbossed:(int)embossed;
-(BOOL)isEmbossedOverridden;
-(int)imprint;
-(void)setImprint:(int)imprint;
-(BOOL)isImprintOverridden;
-(int)shadow;
-(void)setShadow:(int)shadow;
-(BOOL)isShadowOverridden;
-(id)underlineColor;
-(void)setUnderlineColor:(id)color;
-(BOOL)isUnderlineColorOverridden;
-(unsigned short)kerning;
-(void)setKerning:(unsigned short)kerning;
-(BOOL)isKerningOverridden;
-(int)underline;
-(void)setUnderline:(int)underline;
-(BOOL)isUnderlineOverridden;
-(int)strikeThrough;
-(void)setStrikeThrough:(int)through;
-(BOOL)isStrikeThroughOverridden;
-(int)doubleStrikeThrough;
-(void)setDoubleStrikeThrough:(int)through;
-(BOOL)isDoubleStrikeThroughOverridden;
-(BOOL)isHighlight;
-(void)setHighlight:(BOOL)highlight;
-(BOOL)isHighlightOverridden;
-(int)highlightColor;
-(void)setHighlightColor:(int)color;
-(BOOL)isHighlightColorOverridden;
-(int)smallCaps;
-(void)setSmallCaps:(int)caps;
-(BOOL)isSmallCapsOverridden;
-(int)caps;
-(void)setCaps:(int)caps;
-(BOOL)isCapsOverridden;
-(BOOL)isLowerCase;
-(void)setLowerCase:(BOOL)aCase;
-(BOOL)isLowerCaseOverridden;
-(int)hidden;
-(void)setHidden:(int)hidden;
-(BOOL)isHiddenOverridden;
-(short)spacing;
-(void)setSpacing:(short)spacing;
-(BOOL)isSpacingOverridden;
-(short)position;
-(void)setPosition:(short)position;
-(BOOL)isPositionOverridden;
-(unsigned short)fontSize;
-(void)setFontSize:(unsigned short)size;
-(BOOL)isFontSizeOverridden;
-(int)verticalAlign;
-(void)setVerticalAlign:(int)align;
-(BOOL)isVerticalAlignOverridden;
-(id)color;
-(void)setColor:(id)color;
-(BOOL)isColorOverridden;
-(BOOL)isColorAuto;
-(void)setColorAuto:(BOOL)auto;
-(BOOL)isColorAutoOverridden;
-(int)languageForDefaultText;
-(void)setLanguageForDefaultText:(int)defaultText;
-(BOOL)isLanguageForDefaultTextOverridden;
-(int)deleted;
-(void)setDeleted:(int)deleted;
-(BOOL)isDeletedOverridden;
-(int)edited;
-(void)setEdited:(int)edited;
-(BOOL)isEditedOverridden;
-(int)formattingChanged;
-(void)setFormattingChanged:(int)changed;
-(BOOL)isFormattingChangedOverridden;
-(BOOL)isSpecialCharacter;
-(void)setSpecialCharacter:(BOOL)character;
-(BOOL)isSpecialCharacterOverridden;
-(BOOL)isListCharacterPictureBullet;
-(void)setListCharacterPictureBullet:(BOOL)bullet;
-(BOOL)isListCharacterPictureBulletOverridden;
-(long)charPositionOfPictureBulletInBookmark;
-(void)setCharPositionOfPictureBulletInBookmark:(long)bookmark;
-(BOOL)isCharPositionOfPictureBulletInBookmarkOverridden;
-(int)languageForFarEast;
-(void)setLanguageForFarEast:(int)farEast;
-(BOOL)isLanguageForFarEastOverridden;
-(int)languageForBiText;
-(void)setLanguageForBiText:(int)biText;
-(BOOL)isLanguageForBiTextOverridden;
-(unsigned short)fontSizeForBiText;
-(void)setFontSizeForBiText:(unsigned short)biText;
-(BOOL)isFontSizeForBiTextOverridden;
-(BOOL)embeddedObject;
-(void)setEmbeddedObject:(BOOL)object;
-(BOOL)isEmbeddedObjectOverridden;
-(BOOL)ole2;
-(void)setOle2:(BOOL)a2;
-(BOOL)isOle2Overridden;
-(long)objectIDForOle2;
-(void)setObjectIDForOle2:(long)ole2;
-(BOOL)isObjectIDForOle2Overridden;
-(long)offsetToPictureData;
-(void)setOffsetToPictureData:(long)pictureData;
-(BOOL)isOffsetToPictureDataOverridden;
-(id)copyWithZone:(NSZone*)zone;
-(void)copyPropertiesInto:(id)into;
@end

@interface WDCharacterProperties (Private)
-(BOOL)isAnythingOverriddenIn:(XXStruct_R2fbzB*)anIn;
-(BOOL)isBooleanProbablyDifferent:(int)different than:(int)than;
-(int)reverseBooleanProperty:(int)property;
@end

