/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface WMListLevelTextToken : XXUnknownSuperclass {
@private
	NSString* m_string;
	int m_level;
}
+(id)tokenWithString:(id)string andLevel:(int)level;
-(id)initWithString:(id)string andLevel:(int)level;
-(void)dealloc;
-(id)string;
-(id)stringForIndex:(int)index withFormat:(int)format initialNumber:(int)number;
-(int)level;
@end

