/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "WMSectionContentMapper.h"
#import "CMMapper.h"

@class WDText;

__attribute__((visibility("hidden")))
@interface WMSectionContentMapper : CMMapper {
@private
	WDText* wdText;
}
-(id)initWithWDText:(id)wdtext parent:(id)parent;
-(void)mapAt:(id)at withState:(id)state;
@end

@interface WMSectionContentMapper (Private)
-(void)updateTextFrameState:(id)state atIndex:(int)index;
-(id)paragraphAtIndex:(int)index;
-(void)mapTextFrameAt:(id)at withState:(id)state;
-(void)mapTextFrameStyleTo:(id)to withState:(id)state;
@end

