/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "WXCharacterProperties.h"


__attribute__((visibility("hidden")))
@interface WXCharacterProperties : XXUnknownSuperclass {
}
+(void)initialize;
+(void)readFrom:(xmlNode*)from to:(id)to state:(id)state;
+(void)applyDeletionInsertionProperties:(id)properties state:(id)state;
@end

@interface WXCharacterProperties (Private)
+(BOOL)readBooleanCharacterProperty:(xmlNode*)property propertyName:(const char*)name attributeName:(const char*)name3 outValue:(int*)value;
+(int)languageFromString:(id)string;
@end

