/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "WXSection.h"
#import "OfficeImport-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface WXSection : XXUnknownSuperclass {
}
+(void)initialize;
+(void)readFrom:(xmlNode*)from to:(id)to state:(id)state;
@end

@interface WXSection (Private)
+(void)mapHeader:(xmlNode*)header toSection:(id)section state:(id)state;
+(void)mapFooter:(xmlNode*)footer toSection:(id)section state:(id)state;
+(void)mapProperties:(xmlNode*)properties toSection:(id)section state:(id)state;
@end

