/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "CorePDF-Structs.h"
#import "CPDisposable.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface CPFont : XXUnknownSuperclass <CPDisposable> {
	CGPDFFontRef cgPDFFont;
	CGFontRef cgFont;
	NSString* fontName;
	BOOL exactMatch;
	XXStruct_FvSZlC descriptor;
	CFDictionaryRef kernDictionary;
	double kernUnitsPerEm;
	BOOL disposed;
}
-(id)matchingFontName;
-(void)getFontName;
-(void)loadExternalFontInfoFor:(id)aFor;
-(void)loadEmbeddedFontInfo;
-(id)initWith:(CGPDFDictionaryRef)with;
-(void)dispose;
-(void)finalize;
-(void)dealloc;
-(CGPDFFontRef)cgPDFFont;
-(CGFontRef)cgFont;
-(id)fontName;
-(BOOL)isSameFontAs:(id)as;
-(float)fontStretch;
-(float)fontWeight;
-(unsigned)flags;
-(CGRect)fontBBox;
-(float)italicAngle;
-(float)ascent;
-(float)descent;
-(float)leading;
-(float)capHeight;
-(float)xHeight;
-(float)stemV;
-(float)stemH;
-(float)avgWidth;
-(float)maxWidth;
-(float)missingWidth;
-(float)spaceWidth;
-(float)underlinePosition;
-(float)underlineThickness;
-(double)kernBetweenUnicode:(unsigned short)unicode andUnicode:(unsigned short)unicode2;
-(BOOL)getGlyphs:(unsigned short*)glyphs forCodes:(const unsigned short*)codes count:(unsigned)count;
-(void)uniCharsFor:(unsigned long)aFor count:(unsigned*)count toArray:(unsigned short*)array maxChars:(unsigned)chars;
@end

