/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "CorePDF-Structs.h"
#import "CPDisposable.h"
#import "CPChunk.h"
#import "CPPage.h"

@class NSMutableArray;

@interface CPPage : CPChunk <CPDisposable> {
	int pageNumber;
	CGRect pageCropBox;
	BOOL hasZones;
	BOOL hasTextLines;
	BOOL isDirty;
	BOOL isStartOfSection;
	long maxLayoutZOrder;
	CPChunk* background;
	float complexity;
	int rotation;
	NSMutableArray* shapesOnPage;
	NSMutableArray* imagesOnPage;
	NSMutableArray* graphicsOnPage;
	NSMutableArray* columnsOnPage;
	CPPDFContext* pdfContext;
	BOOL contextOwner;
	CGPDFPageRef pdfPage;
	NSMutableArray* textLinesOnPage;
	void* _layout;
	id hitTest;
	BOOL reconstructed;
	opaque_pthread_mutex_t mutex;
}
+(void)sortByReadingOrder:(id)order;
-(id)init;
-(id)initWithPDFPage:(CGPDFPageRef)pdfpage;
-(void)dispose;
-(void)finalize;
-(void)dealloc;
-(CGPDFPageRef)pdfPage;
-(void)reconstruct;
-(void)setPDFContext:(CPPDFContext*)context;
-(CPPDFContext*)PDFContext;
-(id)copyWithZone:(NSZone*)zone;
-(void)setPageCropBox:(CGRect)box;
-(CGRect)pageCropBox;
-(void)accept:(id)accept;
-(float)complexity;
-(void)setComplexity:(float)complexity;
-(int)pageNumber;
-(void)setPageNumber:(int)number;
-(id)parent;
-(void)addShape:(id)shape;
-(id)shapesOnPage;
-(void)addImage:(id)image;
-(id)imagesOnPage;
-(id)graphicsOnPage;
-(void)setHasZones:(BOOL)zones;
-(BOOL)hasZones;
-(id)bodyZone;
-(BOOL)hasTextLines;
-(void)setHasTextLines:(BOOL)lines;
-(BOOL)isStartOfSection;
-(void)setIsStartOfSection:(BOOL)section;
-(int)rotation;
-(void)setRotation:(int)rotation;
-(id)background;
-(void)setBackground:(id)background;
-(void)restoreBackGroundObjectToPage;
-(id)children;
-(unsigned)traverse:(id)traverse ordinal:(unsigned)ordinal;
-(unsigned)setPositionsOf:(id)of from:(unsigned)from;
-(unsigned)setCellPositionsOf:(id)of from:(unsigned)from;
-(unsigned)setGraphicPositions:(id)positions from:(unsigned)from;
-(unsigned)setReadingOrder:(id)order from:(unsigned)from;
-(void)layDownObjectsOnPage;
-(void)sortByReadingOrder;
-(void)layDownObjectsOnPageOld;
-(id)textLinesOnPage;
-(id)columnsOnPage;
-(void)addColumns:(id)columns;
@end

@interface CPPage (CPPageSelections)
-(id)hitTest;
-(BOOL)populatePDFLayout:(CGPDFLayoutRef)layout;
-(CGPDFLayoutRef)layout;
@end

