/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "CorePDF-Structs.h"
#import "CPChunk.h"


@interface CPRegion : CPChunk {
	BOOL isTextRegion;
	BOOL isImageRegion;
	BOOL isCompoundShape;
	CPRegion* nextRegion;
	int order;
	id link;
}
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(void)accept:(id)accept;
-(BOOL)isTextRegion;
-(BOOL)isBoxRegion;
-(BOOL)isImageRegion;
-(void)setIsImageRegion:(BOOL)region;
-(BOOL)isShapeRegion;
-(BOOL)isParagraphRegion;
-(BOOL)isListItemRegion;
-(BOOL)isRowRegion;
-(BOOL)isTableCellRegion;
-(BOOL)isBodyZone;
-(void)setIsTextRegion:(BOOL)region;
-(BOOL)isGraphicalRegion;
-(BOOL)isCompoundShape;
-(void)setIsCompoundShape:(BOOL)shape;
-(BOOL)isZone;
-(BOOL)isRotated;
-(BOOL)isIndivisible;
-(id)nextRegion;
-(void)setNextRegion:(id)region;
-(int)order;
-(void)setOrder:(int)order;
-(void)setLink:(id)link;
-(id)link;
@end

