/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "CorePDF-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CPTable, CPZone;

@interface CPTableMaker : XXUnknownSuperclass {
	CPZone* tableZone;
	CPTable* table;
	unsigned cellIndex;
	CGPoint* rowYIntervals;
	CGPoint* columnXIntervals;
}
+(BOOL)isTable:(id)table;
+(void)makeTableFrom:(id)from;
+(void)makeTablesInZone:(id)zone;
+(void)makeTablesInPage:(id)page;
-(id)initWithZone:(id)zone;
-(void)dealloc;
-(id)newBackgroundGraphicArrayFromRectangularZone:(id)rectangularZone;
-(id)newTableCellFromZone:(id)zone;
-(void)determineRowsAndColumns:(BOOL)columns;
-(void)makeTable;
@end

