/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "NSCopying.h"
#import "CorePDF-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CPShape;

@interface CPZoneBorderNeighbor : XXUnknownSuperclass <NSCopying> {
	CPShape* neighborShape;
	int shapeSide;
}
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(void)setNeighborShape:(id)shape;
-(id)neighborShape;
-(void)setShapeSide:(int)side;
-(int)shapeSide;
@end

