/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "CorePDF-Structs.h"

@class NSString, UIPDFSelection;

@interface UIPDFPage : XXUnknownSuperclass {
	CGPDFPageRef cgPage;
	unsigned pageNumber;
	NSString* stringInReadingOrder;
	UIPDFSelection* _selection;
}
@property(readonly, assign, nonatomic) CGPDFPageRef CGPage;
@property(readonly, assign, nonatomic) unsigned pageNumber;
@property(retain, nonatomic) UIPDFSelection* selection;
@property(readonly, assign, nonatomic) CGRect cropBox;
-(id)initWithCGPDFPage:(CGPDFPageRef)cgpdfpage;
-(void)dealloc;
-(void)drawInRect:(CGRect)rect context:(CGContextRef)context;
-(CGSize)size;
-(CGRect)cropBoxAccountForRotation;
-(CGRect)mediaBox;
-(CGRect)mediaBoxAccountForRotation;
-(id)string;
@end

