/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import "UIPDFDocument.h"
#import "CorePDF-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface UIPDFDocument : XXUnknownSuperclass {
	CGPDFDocumentRef _cgDocument;
	UIPDFPage** _pageArray;
	unsigned _numberOfPages;
	float _cachedWidth;
}
@property(readonly, assign) unsigned numberOfPages;
@property(readonly, assign, nonatomic) CGPDFDocumentRef cgPDFDocument;
+(id)documentNamed:(id)named;
-(void)_clearCachedState;
-(void)purgePagesBefore:(unsigned)before;
-(void)_setDocument:(CGPDFDocumentRef)document;
-(id)initWithCGPDFDocument:(CGPDFDocumentRef)cgpdfdocument;
-(id)initWithURL:(id)url;
-(void)dealloc;
-(id)pageAtIndex:(unsigned)index;
-(id)findStringForward:(id)forward onPage:(id)page fromSelection:(id)selection compareFlags:(unsigned long)flags;
-(id)findStringBackward:(id)backward onPage:(id)page fromSelection:(id)selection compareFlags:(unsigned long)flags;
-(id)findString:(id)string fromSelection:(id)selection options:(unsigned)options;
-(id)findString:(id)string onPage:(id)page fromSelection:(id)selection options:(unsigned)options;
@end

@interface UIPDFDocument (UIPDFDocumentInternal)
-(unsigned long)cfCompareFlagsFromNSOptions:(unsigned)nsoptions;
-(float)maxWidth;
-(float)maxHeight;
-(float)sumWidth;
-(float)sumHeight;
-(unsigned)indexForPage:(id)page;
-(id)previousPage:(id)page;
-(id)followingPage:(id)page;
@end

