/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface NoteCollectionObject : XXUnknownSuperclass {
}
-(id)predicateForNotes;
-(id)collectionInfo;
-(id)basicAccountIdentifier;
@end

