/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/StoreKit.framework/StoreKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol SKRequestDelegate;

@interface SKRequest : XXUnknownSuperclass {
@private
	id _requestInternal;
}
@property(assign, nonatomic) id<SKRequestDelegate> delegate;
-(id)init;
-(void)dealloc;
-(void)cancel;
-(void)start;
-(BOOL)handleFinishResponse:(id)response returningError:(id*)error;
-(void)issueRequestForIdentifier:(id)identifier;
-(void)_daemonExited:(id)exited;
-(void)_mainThreadDaemonExited:(id)exited;
-(void)_requestFailedNotification:(id)notification;
-(void)_requestFinishedNotification:(id)notification;
-(void)_beginBackgroundTask;
-(void)_endBackgroundTask;
-(id)_newIdentifier;
-(void)_registerForNotifications;
-(void)_sendErrorToDelegate:(id)delegate;
-(void)_sendFinishToDelegate;
-(void)_unregisterForNotifications;
@end

