/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ScreenReaderCore.framework/ScreenReaderCore
 */

#import "ScreenReaderCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SCRCStackQueue : XXUnknownSuperclass {
	SCRCStackNode* _firstNode;
	SCRCStackNode* _lastNode;
	unsigned _count;
}
-(void)dealloc;
-(void)removeAllObjects;
-(void)pushArray:(id)array;
-(void)pushObject:(id)object;
-(id)popObject;
-(id)popObjectRetained;
-(id)topObject;
-(void)enqueueObject:(id)object;
-(id)dequeueObjectRetained;
-(id)dequeueObject;
-(unsigned)count;
-(id)description;
-(id)objectEnumerator;
-(BOOL)isEmpty;
@end

