/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import "IMExtendedOperation.h"

@class IMHandle, NSString;

@interface AVChatCancelInvitationOp : IMExtendedOperation {
	IMHandle* _imHandle;
	NSString* _conferenceID;
	unsigned _sessionID;
}
-(id)initWithIMHandle:(id)imhandle avChat:(id)chat;
-(void)dealloc;
-(void)didFinish;
@end

