/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */



@protocol AVConferenceDelegate
-(void)conference:(id)conference receivedNoRemotePacketsForTime:(double)time callID:(int)anId;
-(void)conference:(id)conference didStartSession:(BOOL)session withUserInfo:(id)userInfo;
-(void)conference:(id)conference didStopWithCallID:(int)callID error:(id)error;
-(void)conference:(id)conference updateInputMeterLevel:(float)level;
-(void)conference:(id)conference updateOutputMeterLevel:(float)level;
-(void)conference:(id)conference receivedFirstPreviewForCallID:(int)callID;
-(void)conference:(id)conference receivedFirstRemoteFrameForCallID:(int)callID;
-(void)conference:(id)conference remoteOrientationChangedForCallID:(int)callID orientation:(unsigned)orientation;
-(void)conference:(id)conference remoteCameraBeingChangedForCallID:(int)callID;
-(void)conference:(id)conference remoteCameraChangedForCallID:(int)callID cameraType:(unsigned)type;
-(void)conference:(id)conference remoteAudioPaused:(BOOL)paused callID:(int)anId;
-(void)conference:(id)conference remoteVideoPaused:(BOOL)paused callID:(int)anId;
-(id)localDisplayNameForCallID:(int)callID;
-(id)remoteDisplayNameForCallID:(int)callID;
-(void)conference:(id)conference inititiateRelayRequest:(int)request requestDict:(id)dict;
-(void)conference:(id)conference sendRelayUpdate:(int)update updateDict:(id)dict;
-(void)conference:(id)conference cancelRelayRequest:(int)request requestDict:(id)dict;
@optional
-(void)conference:(id)conference didStartSession:(BOOL)session withCallID:(int)callID error:(id)error;
@end

