/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import "IMAVCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CTCallCenter;

@interface IMAVTelephonyManager : XXUnknownSuperclass {
	CTCallCenter* _callCenter;
	CTServerConnectionRef _ctServerConnection;
	CTCallRef _currentCallRef;
	BOOL _isDesignatedServiceProvider;
	CFMachPortRef _ctServerMachPort;
	CFUUIDRef _ctToken;
}
@property(readonly, assign, nonatomic) unsigned callState;
+(id)sharedInstance;
+(id)numberToDialForNumber:(id)number dialAssist:(BOOL*)assist;
-(oneway void)release;
-(unsigned)retainCount;
-(id)autorelease;
-(id)init;
-(void)dealloc;
-(void)__handleCallEvent:(id)event;
-(void)_handleCallEvent:(id)event;
-(BOOL)_registerCTRequestService;
-(BOOL)_unregisterCTRequestService;
-(void)_cleanupMachInfo;
-(BOOL)_setupCTServerConnection;
-(BOOL)_reconnectCTServerConnectionIfNecessary;
-(BOOL)_disconnectCTServerConnection;
-(void)_dialRequested:(CFDictionaryRef)requested;
-(void)_answerCall:(CTCallRef)call;
-(void)_hangUpCall:(CTCallRef)call;
-(void)_handleCTServiceRequestName:(CFStringRef)name userInfo:(CFDictionaryRef)info contextInfo:(void*)info3;
-(void)_setCurrentCallStatus:(int)status;
-(void)notifyCallConnectedForChat:(id)chat;
-(void)notifyCallConnectingForChat:(id)chat;
-(void)notifyCallStartedForChat:(id)chat;
-(void)notifyMissedCallForChat:(id)chat;
-(void)notifyCallEndedForChat:(id)chat;
-(void)updateCallState;
-(void)startWatchingForCTRequests;
-(void)stopWatchingForCTRequests;
@end

