/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IMAVChat;

@interface IMAVChatFeature : XXUnknownSuperclass {
	IMAVChat* _avChat;
}
@property(assign, setter=setAVChat:) IMAVChat* avChat;
-(id)initWithAVChat:(id)avchat;
-(void)dealloc;
-(void)delegateChangedTo:(id)to;
-(BOOL)hasAddableParticipantsOtherwiseStatus:(unsigned*)status;
-(BOOL)handleGenericAVMessageFromParticipant:(id)participant type:(unsigned)type userInfo:(id)info;
-(void)participant:(id)participant changedFromState:(unsigned)state toState:(unsigned)state3;
-(unsigned)addStatusForIMHandle:(id)imhandle asVideo:(BOOL)video ardRole:(int)role;
-(void)participantRemoved:(id)removed;
-(void)participantInvited:(id)invited;
-(void)conferenceEndedWithReason:(unsigned)reason andError:(int)error;
@end

