/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

#import "Celestial-Structs.h"
#import <MediaToolbox/_kFigFormatWriterTrackProperty_InterleaveTrack.h>

@class NSString;

@interface AVFileValidator : _kFigFormatWriterTrackProperty_InterleaveTrack {
@private
	AVFileValidatorPrivate* _priv;
	NSString* _validationRules;
}
@property(retain) NSString* validationRules;
-(id)initWithURL:(id)url;
-(id)initWithURL:(id)url options:(id)options;
-(void)dealloc;
-(id)url;
-(BOOL)isStreaming;
-(id)notificationForFileCheckResult:(id)fileCheckResult;
-(void)postNotificationForCallback:(id)callback;
-(id)validateBlocking:(BOOL)blocking;
-(void)validateForCameraRoll;
-(void)validate;
-(BOOL)validateSyncWithError:(id*)error;
-(void)cancel;
-(BOOL)isCompleted;
-(float)progress;
@end

