/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
 */

#import "PhotoBoothEffects-Structs.h"
#import "PBRuntimeWrapper.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface PBRuntimeWrapper : XXUnknownSuperclass {
@private
	void** argList;
	unsigned* argSizeList;
	unsigned argIndex;
	CFArrayRef extraArgsList;
	id* cleanupHandler;
	CGSize imageDims;
}
@property(assign, nonatomic) void** argList;
@property(assign, nonatomic) unsigned* argSizeList;
@property(assign, nonatomic) unsigned argIndex;
@property(assign, nonatomic) id* cleanupHandler;
@property(assign, nonatomic) CFArrayRef extraArgsList;
@property(assign, nonatomic) CGSize imageDims;
-(id)init;
-(void)dealloc;
-(void)applyFilter:(id)filter onInputSurface:(IOSurfaceRef)surface mirrored:(BOOL)mirrored withResultHandler:(id)resultHandler;
-(void)setKernelArg:(void*)arg withSize:(unsigned long)size;
-(void)setKernelArgAsBuffer:(void*)buffer withSize:(unsigned long)size;
-(void)setKernelCleanupHandler:(id*)handler;
@end

@interface PBRuntimeWrapper (Private)
-(void)_applyFilter:(id)filter onInputSurface:(IOSurfaceRef)surface mirrored:(BOOL)mirrored withResultHandler:(id)resultHandler;
-(void)_setKernelArg:(void*)arg withSize:(unsigned long)size;
-(void)_setKernelArgAsBuffer:(void*)buffer withSize:(unsigned long)size;
-(void)_setKernelCleanupHandler:(id*)handler;
@end

@interface PBRuntimeWrapper (IOSurfaceConvenience)
-(IOSurfaceRef)createIOSurfaceForWidth:(unsigned long)width height:(unsigned long)height pixelFormat:(unsigned)format workOnRawData:(id)data;
@end

