/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface _MFMessageFlags : XXUnknownSuperclass <NSCoding> {
	unsigned long long realFlags;
}
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

