/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import "QueryProgressMonitor.h"
#import "MessageConsumer.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface _MFMessageCollector : XXUnknownSuperclass <MessageConsumer, QueryProgressMonitor> {
	NSMutableArray* messages;
}
-(id)init;
-(void)dealloc;
-(id)messages;
-(void)newMessagesAvailable:(id)available;
-(BOOL)shouldCancel;
@end

