/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MailMessageStore, NSMutableDictionary;

@interface DeliveryQueue : XXUnknownSuperclass {
	int _state;
	unsigned _messagesTotal;
	unsigned _messagesFromActiveAccounts;
	MailMessageStore* _outboxStore;
	NSMutableDictionary* _lastErrorForMessage;
	unsigned _resetDeliveryQueueWhenDoneWithCurrentMessage : 1;
	unsigned _suspendRequested : 1;
	unsigned _isReachable : 1;
	unsigned _deviceUnlockedAfterBoot : 1;
}
+(id)sharedDeliveryQueue;
-(id)init;
-(void)dealloc;
-(BOOL)isReady;
-(BOOL)isProcessing;
-(BOOL)isSuspended;
-(void)processQueue;
-(void)suspend;
-(void)resume:(BOOL)resume;
-(int)append:(id)append newMessageIDs:(id)ids;
-(int)append:(id)append;
-(int)deliverSynchronously:(id)synchronously;
-(id)lastErrorForMessage:(id)message;
-(id)_outboxStore;
-(void)_closeOutboxStore:(BOOL)store;
-(void)_setErrorForMessageLibraryID:(id)messageLibraryID error:(id)error;
-(void)_setErrorForMessage:(id)message error:(id)error;
-(void)_sendProcessingStartedNotification;
-(void)_sendProcessingFinishedNotification:(int)notification failed:(int)failed;
-(void)_sendUnsentCountChangedNotification:(int)notification activeAccountsOnly:(int)only;
-(void)_setDeliveryFlag:(id)flag state:(BOOL)state;
-(void)_updateStateFile:(BOOL)file;
-(void)_updateCounts;
-(void)_processQueue;
-(void)setPercentDone:(double)done;
-(void)_mailAccountsChanged:(id)changed;
-(void)_flagsChanged:(id)changed;
-(void)_messagesAdded:(id)added;
-(void)_reachabilityChanged:(id)changed;
@end

