/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MFMessageInfo;

@interface MailMessage : XXUnknownSuperclass {
	unsigned long long _messageFlags;
	unsigned char _subjectPrefixLength;
	unsigned long long _modSequenceNumber;
	MFMessageInfo* _info;
}
@property(assign) unsigned long long modSequenceNumber;
+(id)messageWithRFC822Data:(id)rfc822Data;
+(id)forwardedMessagePrefixWithSpacer:(BOOL)spacer;
+(id)replyPrefixWithSpacer:(BOOL)spacer;
+(unsigned)validatePriority:(int)priority;
+(unsigned)displayablePriorityForPriority:(int)priority;
-(id)messageStore;
-(unsigned long long)messageFlags;
-(void)setMessageFlags:(unsigned long long)flags;
-(void)setMessageFlagsWithoutCommitting:(unsigned long long)committing;
-(void)setPriorityFromHeaders:(id)headers;
-(int)priority;
-(void)loadCachedHeaderValuesFromHeaders:(id)headers;
-(void)markAsViewed;
-(void)markAsNotViewed;
-(void)markAsReplied;
-(void)markAsForwarded;
-(id)mailbox;
-(id)subjectAndPrefixLength:(unsigned*)length;
-(id)subjectNotIncludingReAndFwdPrefix;
-(id)subject;
-(void)setSubject:(id)subject;
-(id)loadMeetingExternalID;
-(id)loadMeetingData;
-(id)account;
-(id)remoteMailboxURL;
-(id)originalMailboxURL;
-(id)URL;
-(unsigned short)numberOfAttachments;
-(void)setMutableInfoFromMessage:(id)message;
-(void)setMessageInfo:(id)info to:(id)to cc:(id)cc bcc:(id)bcc sender:(id)sender dateReceivedTimeIntervalSince1970:(double)a1970 dateSentTimeIntervalSince1970:(double)a19707 messageIDHeaderDigest:(id)digest inReplyToHeaderDigest:(id)headerDigest conversationID:(id)anId summary:(id)summary;
-(void)setSummary:(id)summary;
-(BOOL)shouldSetSummary;
-(id)copyMessageInfo;
-(void)dealloc;
@end

