/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ActivityMonitor, NSInvocation;

@interface MonitoredInvocation : XXUnknownSuperclass {
	NSInvocation* _invocation;
	ActivityMonitor* _monitor;
	BOOL _shouldLogInvocation;
}
+(id)invocationWithMethodSignature:(id)methodSignature;
+(id)invocationWithSelector:(SEL)selector target:(id)target taskName:(id)name priority:(int)priority canBeCancelled:(BOOL)cancelled;
+(id)invocationWithSelector:(SEL)selector target:(id)target object:(id)object taskName:(id)name priority:(int)priority canBeCancelled:(BOOL)cancelled;
+(id)invocationWithSelector:(SEL)selector target:(id)target object1:(id)a1 object2:(id)a2 taskName:(id)name priority:(int)priority canBeCancelled:(BOOL)cancelled;
+(id)invocationWithInvocation:(id)invocation taskName:(id)name priority:(int)priority canBeCancelled:(BOOL)cancelled;
-(void)dealloc;
-(id)monitor;
-(void)setMonitor:(id)monitor;
-(BOOL)mf_shouldLogInvocation;
-(void)setShouldLogInvocation:(BOOL)logInvocation;
-(void)invoke;
-(id)description;
@end

