/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSData, NSMutableArray, ADAdData;

@interface ADBannerRepr : XXUnknownSuperclass {
	NSMutableArray* _bannerImages;
	ADAdData* _bannerDescription;
	NSData* _webArchiveData;
	NSData* _storyboardWebArchiveData;
	unsigned _actualNumberOfImpressions;
	BOOL _hasActualNumberOfImpressions;
	BOOL _isWebBanner;
	BOOL _hasIsWebBanner;
	NSString* _batchId;
	BOOL _supplyMetrics;
	BOOL _hasSupplyMetrics;
}
@property(retain, nonatomic) NSMutableArray* bannerImages;
@property(retain, nonatomic) ADAdData* bannerDescription;
@property(retain, nonatomic) NSData* webArchiveData;
@property(retain, nonatomic) NSData* storyboardWebArchiveData;
@property(assign, nonatomic) unsigned actualNumberOfImpressions;
@property(readonly, assign, nonatomic) BOOL hasActualNumberOfImpressions;
@property(assign, nonatomic) BOOL isWebBanner;
@property(readonly, assign, nonatomic) BOOL hasIsWebBanner;
@property(retain, nonatomic) NSString* batchId;
@property(assign, nonatomic) BOOL supplyMetrics;
@property(readonly, assign, nonatomic) BOOL hasSupplyMetrics;
@property(readonly, assign, nonatomic) BOOL hasBatchId;
@property(readonly, assign, nonatomic) BOOL hasStoryboardWebArchiveData;
@property(readonly, assign, nonatomic) BOOL hasWebArchiveData;
@property(readonly, assign, nonatomic) BOOL hasBannerDescription;
@property(readonly, assign, nonatomic) int bannerImagesCount;
-(id)init;
-(void)dealloc;
-(void)setBannerImage:(id)image atIndex:(unsigned)index;
-(id)bannerImageAtIndex:(unsigned)index;
-(void)addBannerImage:(id)image;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

