/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLConnection, NSURL, NSString, NSMutableData;
@protocol ADMailComposerJSOAttachmentDownloadDelegate;

@interface ADMailComposerJSOAttachmentDownload : XXUnknownSuperclass {
	NSURL* _url;
	NSString* _name;
	NSMutableData* _data;
	NSString* _mimeType;
	NSURLConnection* _connection;
	BOOL _hasCompleted;
	id<ADMailComposerJSOAttachmentDownloadDelegate> _delegate;
}
@property(copy, nonatomic) NSURL* url;
@property(copy, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) NSMutableData* data;
@property(readonly, assign, nonatomic) NSString* mimeType;
@property(readonly, assign, nonatomic) NSURLConnection* connection;
@property(readonly, assign, nonatomic) BOOL hasCompleted;
@property(assign, nonatomic) id<ADMailComposerJSOAttachmentDownloadDelegate> delegate;
-(void)dealloc;
-(id)init;
-(void)start;
-(void)cancel;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
@end

