/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, ADLogMetaData, ADAdData;

@interface ADServerErrorRequest : XXUnknownSuperclass {
	ADLogMetaData* _metaData;
	int _errorCode;
	BOOL _hasErrorCode;
	ADAdData* _badResponse;
	NSMutableArray* _urlWithErrors;
}
@property(retain, nonatomic) ADLogMetaData* metaData;
@property(assign, nonatomic) int errorCode;
@property(readonly, assign, nonatomic) BOOL hasErrorCode;
@property(retain, nonatomic) ADAdData* badResponse;
@property(retain, nonatomic) NSMutableArray* urlWithErrors;
@property(readonly, assign, nonatomic) int urlWithErrorsCount;
@property(readonly, assign, nonatomic) BOOL hasBadResponse;
@property(readonly, assign, nonatomic) BOOL hasMetaData;
-(id)init;
-(void)dealloc;
-(void)setUrlWithError:(id)error atIndex:(unsigned)index;
-(id)urlWithErrorAtIndex:(unsigned)index;
-(void)addUrlWithError:(id)error;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(Class)responseClass;
-(unsigned)requestTypeCode;
-(id)description;
@end

