/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import "Conference-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface CNFAudioTableSurroundingView : XXUnknownSuperclass {
}
-(void)drawRect:(CGRect)rect;
@end

