/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "CoreData-Structs.h"

@class NSManagedObject, NSMutableArray, NSPropertyDescription;

__attribute__((visibility("hidden")))
@interface _NSFaultingMutableArray : XXUnknownSuperclass {
@private
	int _cd_rc;
	NSMutableArray* _realArray;
	NSManagedObject* _source;
	NSPropertyDescription* _relationship;
	NSFaultingMutableArrayFlags _flags;
}
+(BOOL)accessInstanceVariablesDirectly;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
-(id)retain;
-(void)release;
-(unsigned)retainCount;
-(id)initWithSource:(id)source forRelationship:(id)relationship asFault:(BOOL)fault;
-(void)dealloc;
-(BOOL)isFault;
-(void)willRead;
-(void)turnIntoFault;
-(id)source;
-(id)relationship;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)description;
-(id)descriptionWithLocale:(id)locale;
-(id)descriptionWithLocale:(id)locale indent:(unsigned)indent;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)index;
-(void)addObject:(id)object;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)objectEnumerator;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(void)removeLastObject;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
-(void)getObjects:(id*)objects;
-(void)setValue:(id)value forKey:(id)key;
-(id)valueForKey:(id)key;
-(id)valueForKeyPath:(id)keyPath;
@end

