/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSQLCore;

__attribute__((visibility("hidden")))
@interface _NSSQLCoreConnectionObsever : XXUnknownSuperclass {
@private
	NSSQLCore* _core;
}
-(id)initWithSQLCore:(id)sqlcore;
-(void)dealloc;
-(id)_retainedBinding;
-(void)_clearBinding;
-(void)_purgeCaches:(id)caches;
@end

