/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "CoreData-Structs.h"


__attribute__((visibility("hidden")))
@interface _PFArray : XXUnknownSuperclass {
@private
	int _cd_rc;
	unsigned _count;
	id* _array;
	PFArrayFlags _flags;
}
+(void)initialize;
+(BOOL)accessInstanceVariablesDirectly;
-(id)initWithObjects:(const id*)objects count:(unsigned)count;
-(id)initWithObjects:(id*)objects count:(unsigned)count andFlags:(unsigned)flags;
-(id*)_objectsPointer;
-(id)arrayFromObjectIDs;
-(unsigned)indexOfObject:(id)object;
-(unsigned)indexOfObject:(id)object inRange:(NSRange)range;
-(unsigned)indexOfObjectIdenticalTo:(id)to;
-(unsigned)indexOfObjectIdenticalTo:(id)to inRange:(NSRange)range;
-(unsigned)indexOfManagedObjectForObjectID:(id)objectID;
-(id)managedObjectIDAtIndex:(unsigned)index;
-(id)subarrayWithRange:(NSRange)range;
-(id)newArrayFromObjectIDs;
-(void)dealloc;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)index;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)getObjects:(id*)objects;
-(void)getObjects:(id*)objects range:(NSRange)range;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)retain;
-(void)release;
-(unsigned)retainCount;
-(unsigned)_flags;
-(void)_setShouldRelease:(BOOL)_set;
-(void)_setShouldUseExtendedRelease:(BOOL)_set;
@end

