/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface _PFString : XXUnknownSuperclass {
@private
	int _reserved1;
	int _cd_rc;
	unsigned _length;
	id _sourceData;
	int _reserved2;
}
+(BOOL)accessInstanceVariablesDirectly;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)retain;
-(void)release;
-(unsigned)retainCount;
-(void)encodeWithCoder:(id)coder;
-(id)copy;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(unsigned)length;
-(unsigned short)characterAtIndex:(unsigned)index;
-(void)getCharacters:(unsigned short*)characters;
-(void)getCharacters:(unsigned short*)characters range:(NSRange)range;
-(const char*)cString;
-(const char*)_fastCStringContents:(BOOL)contents;
-(const char*)UTF8String;
-(void)getCString:(char*)string;
-(unsigned)cStringLength;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(BOOL)isEqualToString:(id)string;
-(id)description;
@end

