/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "NSManagedObjectID.h"
#import "CoreData-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface NSManagedObjectID : XXUnknownSuperclass <NSCopying> {
}
+(void)initialize;
+(int)version;
+(BOOL)accessInstanceVariablesDirectly;
-(id)entity;
-(id)persistentStore;
-(BOOL)isTemporaryID;
-(id)description;
-(id)URIRepresentation;
-(id)copyWithZone:(NSZone*)zone;
@end

@interface NSManagedObjectID (_NSInternalMethods)
-(id)_referenceData;
-(long long)_referenceData64;
-(id)_storeIdentifier;
-(id)_storeInfo1;
-(BOOL)_isPersistentStoreAlive;
-(id)_retainedURIString;
@end

