/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSBundle, NSDictionary;

__attribute__((visibility("hidden")))
@interface NSManagedObjectModelBundle : XXUnknownSuperclass {
@private
	NSBundle* _bundle;
	NSDictionary* _versionInfoDictionary;
}
-(id)initWithPath:(id)path;
-(void)dealloc;
-(id)bundle;
-(id)versionInfoDictionary;
-(id)versionHashInfo;
-(id)currentVersion;
-(id)modelVersions;
-(id)urlForModelVersionWithName:(id)name;
-(id)currentVersionURL;
-(id)_modelForVersionHashes:(id)versionHashes;
@end

