/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "NSSQLColumn.h"

@class NSSQLToOne;

__attribute__((visibility("hidden")))
@interface NSSQLForeignKey : NSSQLColumn {
@private
	NSSQLToOne* _toOne;
}
-(id)initWithEntity:(id)entity toOneRelationship:(id)oneRelationship;
-(id)initWithEntity:(id)entity propertyDescription:(id)description;
-(id)initForReadOnlyFetchingOfEntity:(id)entity toOneRelationship:(id)oneRelationship;
-(id)toOneRelationship;
-(void)dealloc;
-(void)copyValuesForReadOnlyFetch:(id)readOnlyFetch;
@end

