/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "NSSQLExpressionIntermediate.h"

@class NSSQLFetchIntermediate, NSString, NSSQLColumn, NSMutableString, NSExpression, NSMutableArray, NSSQLJoinIntermediate, NSSQLEntity;

__attribute__((visibility("hidden")))
@interface NSSQLSubqueryExpressionIntermediate : NSSQLExpressionIntermediate {
@private
	NSExpression* _trailingKeypath;
	NSSQLFetchIntermediate* _fetchIntermediate;
	NSSQLEntity* _selectFromEntity;
	NSMutableString* _selectFromCorrelationTarget;
	NSString* _selectEntityAlias;
	NSExpression* _variableExpression;
	NSSQLEntity* _governingEntityForVariable;
	NSSQLColumn* _variableColumn;
	NSString* _variableAlias;
	NSSQLJoinIntermediate* _variableJoin;
	BOOL _allowTrailingKeypath;
	BOOL _allowMoreToMany;
	BOOL _useDistinct;
	NSMutableArray* _keypathsToPromote;
	BOOL _isCount;
	BOOL _onlyTrailIsCount;
	BOOL _subqueryHasTruePredicate;
}
-(id)initWithExpression:(id)expression trailingKeypath:(id)keypath inScope:(id)scope;
-(void)dealloc;
-(BOOL)_isKeypathScopedToSubquery:(id)subquery;
-(id)fetchIntermediateForKeypathExpression:(id)keypathExpression;
-(id)governingEntityForKeypathExpression:(id)keypathExpression;
-(id)governingAliasForKeypathExpression:(id)keypathExpression;
-(id)_generateSQLForVariableExpression:(id)variableExpression inContext:(id)context;
-(void)_promoteJoinsForSubqueryScopedKeypath:(id)subqueryScopedKeypath;
-(void)_promoteJoinsForSubqueryScopedKeypaths;
-(BOOL)keypathExpressionIsSafeLHSForIn:(id)anIn;
-(void)selectDistinct;
-(void)_createSelectClauseInFetchWithContext:(id)context;
-(void)_setVariableColumn:(id)column;
-(void)_createCollectionJoinsForFetchInContext:(id)context;
-(id)generateSQLStringInContext:(id)context;
@end

