/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context;
-(id)_mapKVCOperatorsToFunctionsInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
+(id)_keyPathExpressionForString:(id)string;
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(BOOL)_isForeignObjectExpression:(id)expression givenContext:(id)context;
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context ofPredicates:(id)predicates;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context ofPredicate:(id)predicate;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context ofPredicate:(id)predicate;
@end

@interface XXUnknownSuperclass (_NSCoreDataSQLPredicateCategories)
-(id)minimalFormInContext:(id)context;
@end

@interface XXUnknownSuperclass (_CoreData_Extensions)
-(int)_caseInsensitiveNumericCompare:(id)compare;
@end

