/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import "NSCopying.h"
#import "EventKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURL;

@interface EKParticipant : XXUnknownSuperclass <NSCopying> {
@private
	NSURL* _address;
	NSString* _commonName;
	NSString* _emailAddress;
	int _status;
	int _role;
	int _type;
	BOOL _isSelf;
	unsigned _dirtyFlags;
}
@property(readonly, assign, nonatomic) int participantType;
@property(readonly, assign, nonatomic) int participantRole;
@property(readonly, assign, nonatomic) int participantStatus;
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) NSURL* URL;
+(id)participantWithEmailAddress:(id)emailAddress commonName:(id)name;
-(id)initWithEmailAddress:(id)emailAddress name:(id)name;
-(id)initWithEmailAddress:(id)emailAddress name:(id)name isSelf:(BOOL)aSelf;
-(id)initWithEmailAddress:(id)emailAddress name:(id)name role:(int)role status:(int)status type:(int)type;
-(id)initWithEmailAddress:(id)emailAddress name:(id)name role:(int)role status:(int)status type:(int)type isSelf:(BOOL)aSelf;
-(id)initWithURL:(id)url name:(id)name isSelf:(BOOL)aSelf;
-(id)initWithURL:(id)url name:(id)name role:(int)role status:(int)status type:(int)type isSelf:(BOOL)aSelf;
-(id)initWithURL:(id)url name:(id)name emailAddress:(id)address role:(int)role status:(int)status type:(int)type isSelf:(BOOL)aSelf;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(BOOL)isDirty;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)emailAddress;
-(BOOL)isCurrentUser;
-(void*)ABRecordWithAddressBook:(void*)addressBook;
@end

