/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (EventKit)
+(id)_defaultDescriptionForCode:(int)code;
+(id)errorWithCADResult:(int)cadresult;
+(id)errorWithCode:(int)code;
+(id)errorWithCode:(int)code description:(id)description;
@end

@interface XXUnknownSuperclass (CalendarAdditions)
-(id)dateInTimeZone:(id)timeZone fromTimeZone:(id)timeZone2;
-(id)dateForDayInTimeZone:(id)timeZone fromTimeZone:(id)timeZone2;
-(id)dateForEndOfDayInTimeZone:(id)timeZone fromTimeZone:(id)timeZone2;
-(id)dateForDayInTimeZone:(id)timeZone;
-(id)dateForEndOfDayInTimeZone:(id)timeZone;
@end

@interface XXUnknownSuperclass (CalendarAdditions)
+(id)calendarTimeZone;
@end

@interface XXUnknownSuperclass (EKMSUIDAdditions)
-(id)ekmsuidGMTDateToDateInTimeZone:(id)timeZone;
-(id)ekmsuidStringForYearMonthDay;
@end

