/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/iAd.framework/iAd
 */

#import "ADBannerControllerRecipient.h"
#import <XXUnknownSuperclass.h> // Unknown library


@protocol ADBannerControllerRecipient
-(void)bannerControllerDidBecomeAvailable:(id)bannerController;
@end

@interface ADBannerControllerRecipient : XXUnknownSuperclass <ADBannerControllerRecipient> {
	id<ADBannerControllerRecipient> _owner;
}
@property(assign, nonatomic) id<ADBannerControllerRecipient> owner;
-(void)bannerControllerDidBecomeAvailable:(id)bannerController;
@end

