/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/iAd.framework/iAd
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ADDistributedMessagingCenterCallout : XXUnknownSuperclass {
	id _target;
	SEL _selector;
}
@property(retain, nonatomic) id target;
@property(assign, nonatomic) SEL selector;
-(void)dealloc;
@end

