/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsVoices.framework/SportsVoices
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface AttributeKey : XXUnknownSuperclass {
	int _index;
	NSString* _key;
}
+(id)instanceFromPlist:(id)plist;
-(int)index;
-(id)key;
-(id)initFromPlist:(id)plist;
-(id)initWithIndex:(int)index attributeName:(id)name;
-(void)dealloc;
@end

