/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsVoices.framework/SportsVoices
 */

#import "Slot.h"

@class Cell;

@interface SimpleSlot : Slot {
	Cell* _cell;
}
@property(retain) Cell* cell;
+(id)blank;
+(id)instanceFromPlist:(id)plist;
+(id)empty;
+(id)simpleSlotWithCell:(id)cell;
-(id)content;
-(id)initFromPlist:(id)plist;
-(id)initWithCell:(id)cell;
-(void)dealloc;
-(id)reversed;
-(id)overlayedOn:(id)on;
-(id)attributeForKey:(id)key;
-(BOOL)matches:(id)matches;
-(id)description;
@end

