/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class GMMDateTime, GMMDirectionsIconResponse, NSMutableArray, NSString;

@interface GMMDirectionsResponse : XXUnknownSuperclass {
@private
	int _status;
	NSMutableArray* _modes;
	GMMDateTime* _requestedDateTime;
	int _requestedTimeType;
	BOOL _hasRequestedTimeType;
	NSMutableArray* _waypointFeedbacks;
	NSMutableArray* _trips;
	GMMDirectionsIconResponse* _icons;
	NSString* _notice;
	NSMutableArray* _agencys;
	int _recommendedDistanceUnits;
	BOOL _hasRecommendedDistanceUnits;
	NSMutableArray* _optionsUseds;
	NSMutableArray* _alerts;
	NSMutableArray* _alternateModes;
}
@property(assign, nonatomic) int status;
@property(retain, nonatomic) NSMutableArray* modes;
@property(retain, nonatomic) GMMDateTime* requestedDateTime;
@property(assign, nonatomic) int requestedTimeType;
@property(readonly, assign, nonatomic) BOOL hasRequestedTimeType;
@property(retain, nonatomic) NSMutableArray* waypointFeedbacks;
@property(retain, nonatomic) NSMutableArray* trips;
@property(retain, nonatomic) GMMDirectionsIconResponse* icons;
@property(retain, nonatomic) NSString* notice;
@property(retain, nonatomic) NSMutableArray* agencys;
@property(assign, nonatomic) int recommendedDistanceUnits;
@property(readonly, assign, nonatomic) BOOL hasRecommendedDistanceUnits;
@property(retain, nonatomic) NSMutableArray* optionsUseds;
@property(retain, nonatomic) NSMutableArray* alerts;
@property(retain, nonatomic) NSMutableArray* alternateModes;
@property(readonly, assign, nonatomic) int alternateModesCount;
@property(readonly, assign, nonatomic) int alertsCount;
@property(readonly, assign, nonatomic) int optionsUsedsCount;
@property(readonly, assign, nonatomic) int agencysCount;
@property(readonly, assign, nonatomic) BOOL hasNotice;
@property(readonly, assign, nonatomic) BOOL hasIcons;
@property(readonly, assign, nonatomic) int tripsCount;
@property(readonly, assign, nonatomic) int waypointFeedbacksCount;
@property(readonly, assign, nonatomic) BOOL hasRequestedDateTime;
@property(readonly, assign, nonatomic) int modesCount;
-(id)init;
-(void)dealloc;
-(void)setMode:(int)mode atIndex:(unsigned)index;
-(int)modeAtIndex:(unsigned)index;
-(void)addMode:(int)mode;
-(void)setWaypointFeedback:(id)feedback atIndex:(unsigned)index;
-(id)waypointFeedbackAtIndex:(unsigned)index;
-(void)addWaypointFeedback:(id)feedback;
-(void)setTrip:(id)trip atIndex:(unsigned)index;
-(id)tripAtIndex:(unsigned)index;
-(void)addTrip:(id)trip;
-(void)setAgency:(id)agency atIndex:(unsigned)index;
-(id)agencyAtIndex:(unsigned)index;
-(void)addAgency:(id)agency;
-(void)setOptionsUsed:(id)used atIndex:(unsigned)index;
-(id)optionsUsedAtIndex:(unsigned)index;
-(void)addOptionsUsed:(id)used;
-(void)setAlert:(id)alert atIndex:(unsigned)index;
-(id)alertAtIndex:(unsigned)index;
-(void)addAlert:(id)alert;
-(void)setAlternateMode:(id)mode atIndex:(unsigned)index;
-(id)alternateModeAtIndex:(unsigned)index;
-(void)addAlternateMode:(id)mode;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
@end

