/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import "GMMGeometry.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class GMMPixelPoint, GMMPolygon, GMMPolyLine, GMMEfficientMapPoint, GMMMapPoint;

@interface GMMGeometry : XXUnknownSuperclass {
@private
	int _type;
	GMMMapPoint* _mapPoint;
	GMMPolyLine* _polyLine;
	GMMPolygon* _polygon;
	GMMPixelPoint* _pixelPoint;
	GMMEfficientMapPoint* _efficientMapPoint;
}
@property(assign, nonatomic) int type;
@property(retain, nonatomic) GMMMapPoint* mapPoint;
@property(retain, nonatomic) GMMPolyLine* polyLine;
@property(retain, nonatomic) GMMPolygon* polygon;
@property(retain, nonatomic) GMMPixelPoint* pixelPoint;
@property(retain, nonatomic) GMMEfficientMapPoint* efficientMapPoint;
@property(readonly, assign, nonatomic) BOOL hasEfficientMapPoint;
@property(readonly, assign, nonatomic) BOOL hasPixelPoint;
@property(readonly, assign, nonatomic) BOOL hasPolygon;
@property(readonly, assign, nonatomic) BOOL hasPolyLine;
@property(readonly, assign, nonatomic) BOOL hasMapPoint;
-(id)init;
-(void)dealloc;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

@interface GMMGeometry (GMMProtoExtras)
-(id)description;
@end

