/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import "GMMNewLocation.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class GMMGeometry, NSString;

@interface GMMNewLocation : XXUnknownSuperclass {
@private
	NSString* _query;
	GMMGeometry* _geocode;
	NSString* _queryRefinementToken;
	BOOL _isVia;
	BOOL _hasIsVia;
}
@property(retain, nonatomic) NSString* query;
@property(retain, nonatomic) GMMGeometry* geocode;
@property(retain, nonatomic) NSString* queryRefinementToken;
@property(assign, nonatomic) BOOL isVia;
@property(readonly, assign, nonatomic) BOOL hasIsVia;
@property(readonly, assign, nonatomic) BOOL hasQueryRefinementToken;
@property(readonly, assign, nonatomic) BOOL hasGeocode;
@property(readonly, assign, nonatomic) BOOL hasQuery;
-(id)init;
-(void)dealloc;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

@interface GMMNewLocation (GMMProtoExtras)
-(id)description;
@end

