/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface GMMStreetViewViewpoint : XXUnknownSuperclass {
@private
	int _panningCount;
	BOOL _hasPanningCount;
	int _zoomingCount;
	BOOL _hasZoomingCount;
	int _navigationCount;
	BOOL _hasNavigationCount;
	int _scene;
	BOOL _hasScene;
}
@property(assign, nonatomic) int panningCount;
@property(readonly, assign, nonatomic) BOOL hasPanningCount;
@property(assign, nonatomic) int zoomingCount;
@property(readonly, assign, nonatomic) BOOL hasZoomingCount;
@property(assign, nonatomic) int navigationCount;
@property(readonly, assign, nonatomic) BOOL hasNavigationCount;
@property(assign, nonatomic) int scene;
@property(readonly, assign, nonatomic) BOOL hasScene;
-(id)init;
-(void)dealloc;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

