/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class GMMProjectionProperties, GMMAnnotationProperties, GMMModel, GMMDataProperties;

@interface GMMStreetViewMetadata : XXUnknownSuperclass {
@private
	GMMProjectionProperties* _projectionProperties;
	GMMAnnotationProperties* _annotationProperties;
	GMMModel* _model;
	GMMDataProperties* _dataProperties;
}
@property(retain, nonatomic) GMMProjectionProperties* projectionProperties;
@property(retain, nonatomic) GMMAnnotationProperties* annotationProperties;
@property(retain, nonatomic) GMMModel* model;
@property(retain, nonatomic) GMMDataProperties* dataProperties;
@property(readonly, assign, nonatomic) BOOL hasModel;
-(id)init;
-(void)dealloc;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

