/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface LBSName : XXUnknownSuperclass {
@private
	NSString* _text;
	NSString* _language;
	NSMutableArray* _flags;
	int _route_direction;
	BOOL _hasRoute_direction;
	NSString* _raw_text;
	NSString* _short_text;
}
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSString* language;
@property(retain, nonatomic) NSMutableArray* flags;
@property(assign, nonatomic) int route_direction;
@property(readonly, assign, nonatomic) BOOL hasRoute_direction;
@property(retain, nonatomic) NSString* raw_text;
@property(retain, nonatomic) NSString* short_text;
@property(readonly, assign, nonatomic) BOOL hasShort_text;
@property(readonly, assign, nonatomic) BOOL hasRaw_text;
@property(readonly, assign, nonatomic) int flagsCount;
@property(readonly, assign, nonatomic) BOOL hasLanguage;
-(id)init;
-(void)dealloc;
-(void)setFlag:(int)flag atIndex:(unsigned)index;
-(int)flagAtIndex:(unsigned)index;
-(void)addFlag:(int)flag;
-(BOOL)readFrom:(id)from;
-(void)writeTo:(id)to;
-(id)description;
-(id)dictionaryRepresentation;
@end

