/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

#import "DataDetectorsUI-Structs.h"
#import "EKEventEditViewDelegate.h"
#import "ABNewPersonViewControllerDelegate.h"
#import "ABPersonViewControllerDelegate.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class UIViewController, UIPopoverController, UIView, UIWindow;

__attribute__((visibility("hidden")))
@interface DDActionController : XXUnknownSuperclass <ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate, ABPersonViewControllerDelegate, EKEventEditViewDelegate, UIAlertViewDelegate, UIPopoverControllerDelegate> {
@private
	UIViewController* _presentedViewController;
	UIPopoverController* _currentPopoverController;
	UIView* _baseView;
	UIViewController* _currentBaseViewController;
	id _interactionDelegate;
	UIWindow* _originalWindow;
}
@property(retain, nonatomic) id interactionDelegate;
@property(retain, nonatomic) UIPopoverController* popoverController;
@property(retain, nonatomic) UIView* baseView;
-(id)init;
-(void)dealloc;
-(void)_cleanup;
-(id)actionNamesForResult:(DDResultRef)result;
-(id)actionNamesForURL:(id)url;
-(void)_copyURL:(id)url;
-(void)performActionNumber:(int)number forResult:(DDResultRef)result isDefaultAction:(BOOL)action context:(id)context;
-(void)performActionNumber:(int)number forURL:(id)url isDefaultAction:(BOOL)action context:(id)context;
-(void)_presentController:(id)controller;
-(void)dismissCurrentController;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)_presentCurrentViewControllerInWindow:(id)window;
-(void)_dismissCurrentViewController;
-(void)fallBackViewControllerWasDismissed:(id)dismissed;
-(void)_presentEventCreationPanelForResult:(DDResultRef)result context:(id)context;
-(void)eventEditViewController:(id)controller didCompleteWithAction:(int)action;
-(void)_presentNewPerson:(void*)person;
-(void)_presentPeoplePickerForValue:(id)value property:(int)property;
-(void)peoplePickerNavigationControllerDidCancel:(id)peoplePickerNavigationController;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)peoplePickerNavigationController:(id)controller shouldShowInsertEditorForPerson:(void*)person insertProperty:(int*)property copyInsertValue:(id*)value copyInsertLabel:(id*)label;
-(void)peoplePickerNavigationController:(id)controller insertEditorDidConfirm:(BOOL)insertEditor forPerson:(void*)person;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person;
-(BOOL)personViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(void)newPersonViewController:(id)controller didCompleteWithNewPerson:(void*)newPerson;
-(void)_augmentRecord:(void*)record withResult:(DDResultRef)result;
@end

