/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDecimalNumber, NSString;

@interface SWAchievement : XXUnknownSuperclass {
}
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSDecimalNumber* value;
@property(retain, nonatomic) NSString* sensorSerialNumber;
@end

