/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import "SWSyncServiceConnection.h"

@class NSInputStream, NSString;
@protocol SWSyncServiceConnectionDelegate, SWSyncWorkoutConnectionDelegate;

@interface SWSyncWorkoutConnection : SWSyncServiceConnection {
	id<SWSyncServiceConnectionDelegate, SWSyncWorkoutConnectionDelegate> _delegate;
	NSString* _PIN;
	NSInputStream* _workoutXMLStream;
}
@property(assign, nonatomic) id<SWSyncServiceConnectionDelegate, SWSyncWorkoutConnectionDelegate> delegate;
@property(readonly, assign, nonatomic) NSString* PIN;
@property(readonly, assign, nonatomic) NSInputStream* workoutXMLStream;
-(id)initWithPIN:(id)pin workoutXMLStream:(id)stream host:(id)host delegate:(id)delegate;
-(void)dealloc;
-(void)handleResponse:(id)response;
@end

