/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import "ManagedConfiguration-Structs.h"
#import "MCPayload.h"

@class NSString, NSData, NSDate;

@interface MCCertificatePayload : MCPayload {
@private
	NSData* _certificatePersistentID;
	NSString* _installedOnDeviceID;
}
@property(retain) NSData* certificatePersistentID;
@property(copy) NSString* installedOnDeviceID;
@property(readonly, assign) BOOL isSigned;
@property(readonly, assign) NSDate* expiry;
@property(readonly, assign) BOOL isIdentity;
@property(readonly, assign) BOOL isRoot;
-(id)initWithDictionary:(id)dictionary profile:(id)profile outError:(id*)error;
-(void)dealloc;
-(id)stubDictionary;
-(SecCertificate*)copyCertificate;
-(SecIdentity*)copyIdentityFromKeychain;
-(id)title;
-(id)subtitle1Label;
-(id)subtitle1Description;
-(id)subtitle2Label;
-(id)subtitle2Description;
-(id)description;
@end

