/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CACodingProxy : XXUnknownSuperclass <NSCoding> {
}
-(id)initWithObject:(id)object;
-(id)decodedObject;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

