/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, CADisplayMode, NSArray;

@interface CADisplay : XXUnknownSuperclass {
@private
	void* _impl;
}
@property(readonly, assign, getter=isCloningSupported) BOOL cloningSupported;
@property(readonly, assign, getter=isCloned) BOOL cloned;
@property(readonly, assign, getter=isOverscanned) BOOL overscanned;
@property(readonly, assign, getter=isExternal) BOOL external;
@property(readonly, assign) int tag;
@property(readonly, assign, getter=isSupported) BOOL supported;
@property(readonly, assign) unsigned displayId;
@property(readonly, assign, nonatomic) NSString* deviceName;
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) CGRect bounds;
@property(copy, nonatomic) NSString* colorMode;
@property(readonly, assign, nonatomic) CADisplayMode* preferredMode;
@property(retain, nonatomic) CADisplayMode* currentMode;
@property(readonly, assign, nonatomic) NSArray* availableModes;
+(id)displays;
+(id)mainDisplay;
+(id)TVOutDisplay;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(id)_initWithDisplay:(Display*)display;
-(void)_invalidate;
-(void)_update;
-(id)description;
@end

