/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "CADisplayLink.h"
#import "QuartzCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CADisplay;

@interface CADisplayLink : XXUnknownSuperclass {
@private
	void* _impl;
}
@property(assign, nonatomic) int frameInterval;
@property(assign, nonatomic, getter=isPaused) BOOL paused;
@property(readonly, assign, nonatomic) double duration;
@property(readonly, assign, nonatomic) double timestamp;
+(id)displayLinkWithTarget:(id)target selector:(SEL)selector;
-(id)_initWithDisplayLink:(DisplayLink*)displayLink;
-(void)dealloc;
-(void)addToRunLoop:(id)runLoop forMode:(id)mode;
-(void)removeFromRunLoop:(id)runLoop forMode:(id)mode;
-(void)invalidate;
@end

@interface CADisplayLink (CADisplayLinkPrivate)
@property(retain, nonatomic) id userInfo;
@property(readonly, assign, nonatomic) CADisplay* display;
+(id)displayLinkWithDisplay:(id)display target:(id)target selector:(SEL)selector;
@end

