/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import "CALayer.h"


@interface CAReplicatorLayer : CALayer {
}
@property(assign) float instanceAlphaOffset;
@property(assign) float instanceBlueOffset;
@property(assign) float instanceGreenOffset;
@property(assign) float instanceRedOffset;
@property(assign) CGColorRef instanceColor;
@property(assign) CATransform3D instanceTransform;
@property(assign) double instanceDelay;
@property(assign) BOOL preservesDepth;
@property(assign) int instanceCount;
+(id)defaultValueForKey:(id)key;
+(BOOL)CA_automaticallyNotifiesObservers:(Class)observers;
-(id)init;
-(void)didChangeValueForKey:(id)key;
-(id)_implicitActionForKey:(id)key;
-(void)_renderSublayersInContext:(CGContextRef)context;
-(Layer*)_copyRenderLayer:(Transaction*)layer layerFlags:(unsigned)flags commitFlags:(unsigned*)flags3;
-(bool)_renderLayerDefinesProperty:(unsigned)property;
-(unsigned)_renderLayerPropertyAnimationFlags:(unsigned)flags;
@end

