/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "CARenderer.h"
#import "QuartzCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CAContext, CALayer;

@interface CARenderer : XXUnknownSuperclass {
@private
	CARendererPriv* _priv;
}
@property(assign) CGRect bounds;
@property(retain) CALayer* layer;
+(id)rendererWithEAGLContext:(id)eaglcontext options:(id)options;
-(id)_initWithOptions:(id)options;
-(id)_initWithEAGLContext:(id)eaglcontext options:(id)options;
-(void)dealloc;
-(void)beginFrameAtTime:(double)time timeStamp:(XXStruct_soD7RD*)stamp;
-(CGRect)updateBounds;
-(void)addUpdateRect:(CGRect)rect;
-(double)nextFrameTime;
-(BOOL)hasMissingContent;
-(void)render;
-(void)endFrame;
@end

@interface CARenderer (CARendererPrivate)
@property(assign) id delegate;
@property(retain) CAContext* context;
@end

