/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import "CALayer.h"

@class NSArray, NSString;

@interface CAShapeLayer : CALayer {
}
@property(copy) NSArray* lineDashPattern;
@property(assign) float lineDashPhase;
@property(copy) NSString* lineJoin;
@property(copy) NSString* lineCap;
@property(assign) float miterLimit;
@property(assign) float lineWidth;
@property(assign) float strokeEnd;
@property(assign) float strokeStart;
@property(assign) CGColorRef strokeColor;
@property(copy) NSString* fillRule;
@property(assign) CGColorRef fillColor;
@property(assign) CGPathRef path;
+(id)defaultValueForKey:(id)key;
+(BOOL)CA_automaticallyNotifiesObservers:(Class)observers;
-(void)didChangeValueForKey:(id)key;
-(id)_implicitActionForKey:(id)key;
-(void)_renderForegroundInContext:(CGContextRef)context;
-(Layer*)_copyRenderLayer:(Transaction*)layer layerFlags:(unsigned)flags commitFlags:(unsigned*)flags3;
-(bool)_renderLayerDefinesProperty:(unsigned)property;
-(unsigned)_renderLayerPropertyAnimationFlags:(unsigned)flags;
@end

