/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "CAAnimation.h"
#import "QuartzCore-Structs.h"
#import "CATransition.h"

@class NSString, NSDictionary;

@interface CATransition : CAAnimation {
}
@property(retain) id filter;
@property(assign) float endProgress;
@property(assign) float startProgress;
@property(copy) NSString* subtype;
@property(copy) NSString* type;
-(Animation*)_copyRenderAnimationForLayer:(id)layer;
-(unsigned)_propertyFlagsForLayer:(id)layer;
@end

@interface CATransition (CAAnimationPrivate)
@property(assign) unsigned transitionFlags;
@property(copy) NSDictionary* options;
@end

