/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
 */

#import "ALAssetsLibraryAsset.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ALAssetsFilter, MLAlbum, ALAssetsLibrary;

__attribute__((visibility("hidden")))
@interface ALAssetsGroupPrivate : XXUnknownSuperclass <ALAssetsLibraryAsset> {
@private
	MLAlbum* _album;
	BOOL _loadedAssets;
	ALAssetsFilter* _assetsFilter;
	unsigned _groupType;
	BOOL _isValid;
	ALAssetsLibrary* _library;
}
@property(retain, nonatomic) MLAlbum* album;
@property(retain, nonatomic) ALAssetsFilter* assetsFilter;
@property(assign, nonatomic) unsigned groupType;
@property(assign, nonatomic) BOOL isValid;
@property(assign, nonatomic) ALAssetsLibrary* library;
-(id)initWithAlbum:(id)album library:(id)library;
-(void)dealloc;
-(void)resetAssets;
-(void)populateAssets;
-(void)libraryDidChange;
-(void)libraryWillDisappear;
@end

