/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GameKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UIImage, NSMutableArray, GKUITheme;

@interface GKCellBackgroundView : XXUnknownSuperclass {
	GKUITheme* _theme;
	NSMutableArray* _backgroundDrawDescriptors;
	struct {
		unsigned drawSelected : 1;
		unsigned groupedTableViewStyle : 1;
	} _gkViewFlags;
	int _backgroundStyle;
	CGSize _fillImagePhase;
	UIImage* _fillImage;
	BOOL _ignoreFillPhaseYOffset;
	unsigned _columnCount;
	int _selectedColumn;
	unsigned _cellCount;
	float _cellGapWidth;
	int _selectedCell;
	UIEdgeInsets _borderInsets;
}
@property(retain, nonatomic) GKUITheme* theme;
@property(retain, nonatomic) NSArray* backgroundDrawDescriptors;
@property(assign, nonatomic) int backgroundStyle;
@property(assign, nonatomic) CGSize fillImagePhase;
@property(retain, nonatomic) UIImage* fillImage;
@property(assign, nonatomic) BOOL ignoreFillPhaseYOffset;
@property(assign, nonatomic) unsigned columnCount;
@property(assign, nonatomic) int selectedColumn;
@property(assign, nonatomic) unsigned cellCount;
@property(assign, nonatomic) float cellGapWidth;
@property(assign, nonatomic) int selectedCell;
@property(assign, nonatomic) UIEdgeInsets borderInsets;
@property(assign, nonatomic) BOOL drawSelected;
@property(assign, nonatomic) BOOL grouped;
+(id)buttonCellBackgroundWithTheme:(id)theme;
+(id)selectedButtonCellBackgroundWithTheme:(id)theme;
+(id)cellBackgroundWithTheme:(id)theme;
+(id)selectedCellBackgroundWithTheme:(id)theme;
+(id)cellBackgroundWithTheme:(id)theme tableViewStyle:(int)style;
+(id)selectedCellBackgroundWithTheme:(id)theme tableViewStyle:(int)style;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)drawDescriptorForCellIndex:(int)cellIndex;
-(void)setBounds:(CGRect)bounds;
-(void)updateContentStretchForFrame:(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(BOOL)hasKnownLocations;
-(void)configureBorderImages;
-(int)sectionLocation;
-(void)setSectionLocation:(int)location animated:(BOOL)animated;
-(void)setSectionLocations:(id)locations;
-(void)drawFillInRect:(CGRect)rect;
-(void)_drawFourPartBorderImage:(id)image inRect:(CGRect)rect;
-(void)_drawBorderOutlineInRect:(CGRect)rect cellIndex:(int)index;
-(void)drawBorderInRect:(CGRect)rect cellIndex:(int)index;
-(BOOL)shouldDrawBorderAtIndex:(int)index;
-(void)drawRect:(CGRect)rect;
-(CGRect)fillRectForColumn:(unsigned)column;
-(CGRect)rectForCell:(unsigned)cell withBounds:(CGRect)bounds;
-(CGRect)borderRectForCell:(unsigned)cell;
-(CGRect)fillRectForCell:(unsigned)cell;
-(CGPathRef)pathForRect:(CGRect)rect withRoundedCorners:(int)roundedCorners cornerRadius:(float)radius;
-(CGPathRef)fillPathForCell:(unsigned)cell;
-(CGPathRef)fillPathForColumn:(unsigned)column;
@end

