/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKComposeHeaderView.h"
#import "GameKit-Structs.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "GKComposeRecipientAtomDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, GKComposeRecipientAtom, UITextField, NSObject, NSMutableDictionary, NSTimer, NSArray;
@protocol GKComposeRecipientViewDelegate;

@interface GKComposeRecipientView : GKComposeHeaderView <UITextFieldDelegate, ABPeoplePickerNavigationControllerDelegate, GKComposeRecipientAtomDelegate> {
	NSMutableArray* _recipients;
	NSMutableDictionary* _atoms;
	GKComposeRecipientAtom* _selectedAtom;
	BOOL _editable;
	BOOL _editing;
	BOOL _picking;
	NSArray* _properties;
	int _maxRecipients;
	BOOL _parentIsClosing;
	NSTimer* _delayTimer;
	UIEdgeInsets _contentInsetsWhileEditing;
	UITextField* _textField;
	NSObject<GKComposeRecipientViewDelegate>* _composeDelegate;
}
@property(assign, nonatomic, getter=isEditable) BOOL editable;
@property(assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) UIEdgeInsets contentInsetsWhileEditing;
@property(assign, nonatomic) NSObject<GKComposeRecipientViewDelegate>* composeDelegate;
-(id)initWithFrame:(CGRect)frame;
-(void)setLabel:(id)label;
-(id)fadeTransition;
-(void)clearText;
-(void)setProperty:(int)property;
-(void)setProperties:(id)properties;
-(id)addresses;
-(void)setAddresses:(id)addresses;
-(void)removeRecipient:(id)recipient;
-(void)addRecipient:(id)recipient;
-(void)recipientWasUpdated:(id)updated;
-(void)addAddress:(id)address;
-(void)addRecord:(void*)record identifier:(int)identifier;
-(void)addRecord:(void*)record property:(int)property identifier:(int)identifier;
-(void)removeAddressAtIndex:(int)index;
-(void)removeAddresses;
-(BOOL)_addable;
-(void)setMaxRecipients:(int)recipients;
-(int)maxRecipients;
-(void)keyboardInputChangedSelection:(id)selection;
-(void)selectComposeRecipientAtom:(id)atom;
-(void)layoutAtomViews;
-(void)reflow;
-(id)textField;
-(BOOL)shouldShowCardForPerson:(void*)person;
-(void)_dismissPicker:(id)picker;
-(void)peoplePickerNavigationControllerDidCancel:(id)peoplePickerNavigationController;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)textFieldShouldBecomeFirstResponder:(id)textField;
-(void)textFieldDidBecomeFirstResponder:(id)textField;
-(void)textFieldDidResignFirstResponder:(id)textField;
-(id)text;
-(BOOL)becomeFirstResponder;
-(void)_cancelDelayTimer;
-(void)_delayTimerFired:(id)fired;
-(void)composeRecipientAtomSelectPrevious:(id)previous;
-(void)composeRecipientAtomSelectNext:(id)next;
-(void)textChanged:(id)changed;
-(void)windowDidResignKey:(id)window;
-(void)_deselectAtom;
-(void)_deleteSelectedAtom;
-(BOOL)keyboardInput:(id)input shouldInsertText:(id)text isMarkedText:(BOOL)text3;
-(BOOL)keyboardInputShouldDelete:(id)keyboardInput;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)dealloc;
-(id)recipients;
-(void)parentWillClose;
-(void)parentDidClose;
@end

