/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKAcceptFriendRequestDataRequest.h"


@interface GKDeclineFriendRequestDataRequest : GKAcceptFriendRequestDataRequest {
}
-(id)key;
-(id)invalidateCacheKeys;
-(id)request;
@end

