/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class GKPlayer, UILabel, UIImageView, NSString;

@interface GKFriendRequestAlertView : XXUnknownSuperclass {
@private
	GKPlayer* _player;
	UIImageView* _avatarImageView;
	UILabel* _aliasLabel;
}
@property(readonly, assign, nonatomic) GKPlayer* player;
@property(retain, nonatomic) NSString* request;
-(id)initWithPlayer:(id)player;
-(void)dealloc;
-(void)layout;
@end

