/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface GKMatchPacket : XXUnknownSuperclass {
	unsigned char _version;
	unsigned char _packetType;
	unsigned _sequenceNumber;
	unsigned _totalLength;
	unsigned short _checksum;
	BOOL _valid;
	NSData* _data;
}
@property(assign, nonatomic) unsigned char version;
@property(assign, nonatomic) unsigned char packetType;
@property(assign, nonatomic) unsigned sequenceNumber;
@property(assign, nonatomic) unsigned totalLength;
@property(assign, nonatomic) unsigned short checksum;
@property(assign, nonatomic) BOOL valid;
@property(retain, nonatomic) NSData* data;
-(id)init;
-(id)initWithMessage:(id)message;
-(id)message;
-(void)dealloc;
@end

