/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GameKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface GKMatchRequest : XXUnknownSuperclass {
	unsigned _minPlayers;
	unsigned _maxPlayers;
	unsigned _playerGroup;
	unsigned _playerAttributes;
	BOOL _attributesSet;
	NSArray* _playersToInvite;
}
@property(assign, nonatomic) unsigned minPlayers;
@property(assign, nonatomic) unsigned maxPlayers;
@property(assign, nonatomic) unsigned playerGroup;
@property(assign, nonatomic) unsigned playerAttributes;
@property(assign, nonatomic) BOOL attributesSet;
@property(retain, nonatomic) NSArray* playersToInvite;
-(id)init;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)isValidForHosted:(BOOL)hosted;
@end

