/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, GKSession, GKVoiceChatSession;

@interface GKVoiceChat : XXUnknownSuperclass {
	id _playerStateUpdateHandler;
	GKSession* _gkSession;
	GKVoiceChatSession* _gkVoiceChatSession;
}
@property(copy, nonatomic) id playerStateUpdateHandler;
@property(retain, nonatomic) GKSession* gkSession;
@property(retain, nonatomic) GKVoiceChatSession* gkVoiceChatSession;
@property(assign, nonatomic) float volume;
@property(assign, nonatomic, getter=isActive) BOOL active;
@property(readonly, assign, nonatomic) NSString* name;
+(BOOL)isVoIPAllowed;
-(id)initChat:(id)chat withSession:(id)session;
-(void)dealloc;
-(void)start;
-(void)stop;
-(void)setMute:(BOOL)mute forPlayer:(id)player;
-(void)gkVoiceChatSession:(id)session stateUpdate:(unsigned)update forPeer:(id)peer;
@end

