/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIKit-Structs.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface UICompositeImageElement : XXUnknownSuperclass {
@private
	UIImage* m_image;
	CGRect m_fromRect;
	CGRect m_toRect;
	int m_operation;
	float m_fraction;
}
+(id)elementWithImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3 operation:(int)operation fraction:(float)fraction;
-(id)initWithImage:(id)image toRect:(CGRect)rect fromRect:(CGRect)rect3 operation:(int)operation fraction:(float)fraction;
-(void)dealloc;
-(void)draw;
@end

