/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIKit-Structs.h"
#import "NSCopying.h"

@class UIEvent, UITouch;

__attribute__((visibility("hidden")))
@interface UIGestureDelayedTouch : XXUnknownSuperclass <NSCopying> {
@private
	UITouch* _touch;
	UITouch* _stateWhenDelayed;
	UITouch* _stateWhenDelivered;
	UIEvent* _event;
	int _delayCount;
	BOOL _cloneForSecondDelivery;
}
@property(retain) UITouch* touch;
@property(retain) UITouch* stateWhenDelayed;
@property(retain) UITouch* stateWhenDelivered;
@property(retain) UIEvent* event;
@property(assign) BOOL cloneForSecondDelivery;
-(id)init;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(int)decrementDelayCount;
-(void)incrementDelayCount;
-(int)delayCount;
-(void)saveCurrentTouchState;
-(int)phaseForDelivery;
-(int)timestampForDelivery;
-(id)description;
@end

