/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSCoding.h"
#import "UIKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "UIKeyboardRivenKeyplane.h"

@class NSMutableArray, UIKBIdentifierList, UIKBAttributeList, NSArray, NSString;

@interface UIKBKeyplane : XXUnknownSuperclass <NSCoding, NSCopying, UIKeyboardRivenKeyplane> {
	NSString* m_name;
	NSMutableArray* m_keylayouts;
	UIKBAttributeList* m_attributes;
	UIKBIdentifierList* m_supportedTypes;
	NSArray* m_keys;
}
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSArray* keylayouts;
@property(copy, nonatomic) UIKBAttributeList* attributes;
@property(copy, nonatomic) UIKBIdentifierList* supportedTypes;
@property(readonly, assign, nonatomic) NSArray* keysOrderedByPosition;
@property(readonly, assign, nonatomic) NSArray* keys;
+(id)keyplane;
-(id)init;
-(id)initWithName:(id)name keylayouts:(id)keylayouts attributes:(id)attributes supportedTypes:(id)types;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(id)keylayoutWithName:(id)name;
-(void)layoutInRect:(CGRect)rect;
-(BOOL)looksLike:(id)like;
-(BOOL)looksLikeShiftAlternate;
-(id)keysByKeyName:(id)name;
-(id)description;
-(BOOL)usesAutoShift;
-(id)alternateKeyplaneName;
-(id)shiftAlternateKeyplaneName;
-(BOOL)isShiftKeyplane;
-(BOOL)shouldSkipCandidateSelection;
-(BOOL)isShiftKeyPlaneChooser;
-(BOOL)usesAdaptiveKeys;
-(BOOL)usesKeyCharging;
-(BOOL)supportsType:(int)type;
@end

