/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIGestureRecognizer.h"


__attribute__((visibility("hidden")))
@interface UIKeyboardZoomGesture : UIGestureRecognizer {
@private
	BOOL _waiting;
	int _zoomType;
	float _initialDistance;
	double _maximumWaitForMultitouch;
	double _maximumWaitForMovement;
}
@property(assign, nonatomic) int zoomType;
@property(assign, nonatomic) double maximumWaitForMultitouch;
@property(assign, nonatomic) double maximumWaitForMovement;
-(id)initWithTarget:(id)target action:(SEL)action;
-(void)_resetGestureRecognizer;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)tooSlow:(id)slow;
-(void)clearTimers;
-(void)failAfterDelay:(double)delay;
-(CGPoint)centroidForTouches:(id)touches;
-(float)averageDistanceForTouches:(id)touches;
@end

