/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSCoding.h"
#import "UIKit-Structs.h"
#import "UIView.h"

@class UIRoundedCornerView;

__attribute__((visibility("hidden")))
@interface UILayoutContainerView : UIView <NSCoding> {
@private
	id _delegate;
	BOOL _usesRoundedCorners;
	float _cornerRadius;
	BOOL _fastMode;
	UIRoundedCornerView* _roundedCornerView;
	BOOL _usesInnerShadow;
	BOOL _shadowViewsInstalled;
	UIView* _shadowView;
}
@property(assign, nonatomic) BOOL usesRoundedCorners;
@property(assign, nonatomic) BOOL useFastMode;
@property(assign, nonatomic) BOOL usesInnerShadow;
@property(assign, nonatomic) id delegate;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)layoutSubviews;
-(void)_installShadowViews;
-(void)_tearDownShadowViews;
-(void)addSubview:(id)subview;
-(void)_beginFastMode;
-(void)_endFastMode;
-(void)dealloc;
@end

