/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIGestureRecognizer.h"

@class UIPanGestureVelocitySample, NSMutableArray;

@interface UIPanGestureRecognizer : UIGestureRecognizer {
@private
	CGPoint _firstScreenLocation;
	CGPoint _lastScreenLocation;
	double _lastTouchTime;
	id _velocitySample;
	id _previousVelocitySample;
	NSMutableArray* _touches;
	unsigned _lastTouchCount;
	unsigned _minTouchCount;
	unsigned _maxTouchCount;
	float _hysteresis;
	unsigned _failsPastMaxTouches : 1;
}
@property(assign, nonatomic) unsigned minimumNumberOfTouches;
@property(assign, nonatomic) unsigned maximumNumberOfTouches;
@property(readonly, assign, getter=_velocitySample) UIPanGestureVelocitySample* _velocitySample;
@property(readonly, assign, getter=_previousVelocitySample) UIPanGestureVelocitySample* _previousVelocitySample;
-(id)initWithTarget:(id)target action:(SEL)action;
-(void)dealloc;
-(void)_resetVelocitySamples;
-(void)_resetGestureRecognizer;
-(void)setFailsPastMaxTouches:(BOOL)touches;
-(BOOL)failsPastMaxTouches;
-(int)_lastTouchCount;
-(void)_setHysteresis:(float)hysteresis;
-(float)_hysteresis;
-(CADoublePoint)_convertPoint:(CGPoint)point toScreenCoordinatesFromView:(id)view;
-(CADoublePoint)_convertPoint:(CGPoint)point fromScreenCoordinatesToView:(id)view;
-(CGPoint)translationInView:(id)view;
-(void)setTranslation:(CGPoint)translation inView:(id)view;
-(CADoublePoint)_convertVelocitySample:(id)sample fromScreenCoordinatesToView:(id)view;
-(CGPoint)velocityInView:(id)view;
-(void)_touchesListChangedFrom:(id)from to:(id)to;
-(void)_centroidMovedTo:(CGPoint)to atTime:(double)time;
-(BOOL)_willScrollX;
-(BOOL)_willScrollY;
-(BOOL)_shouldTryToBeginWithEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(CGPoint)locationInView:(id)view;
-(unsigned)numberOfTouches;
-(CGPoint)locationOfTouch:(unsigned)touch inView:(id)view;
@end

