/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIButton.h"
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface UIPopoverButton : UIButton {
}
-(id)initWithFrame:(CGRect)frame buttonType:(int)type;
-(void)setEnabled:(BOOL)enabled;
-(id)_setupBackgroundView;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

