/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIPrintPaper.h"
#import "UIKit-Structs.h"


@interface UIPrintPaper : XXUnknownSuperclass {
@private
	BOOL _landscape;
	id _internal;
}
@property(assign, nonatomic) BOOL landscape;
@property(readonly, assign) CGRect printableRect;
@property(readonly, assign) CGSize paperSize;
+(id)bestPaperForPageSize:(CGSize)pageSize withPapersFromArray:(id)array;
+(id)_paperListForPrinter:(id)printer withDuplexMode:(int)duplexMode;
+(id)_defaultPaperForOuptutType:(int)ouptutType;
-(id)_initWithPrintKitPaper:(id)printKitPaper;
-(void)_updatePKPaper:(id)paper;
-(void)dealloc;
-(CGRect)_printableRectForDuplex:(BOOL)duplex;
-(id)_pkPaper;
@end

@interface UIPrintPaper (Deprecated_Nonfunctional)
-(CGRect)printRect;
@end

