/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITableViewCell.h"

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface UIPrintStatusJobTableViewCell : UITableViewCell {
@private
	UIActivityIndicatorView* _activityIndicator;
	UIView* _verticalSeparator;
}
@property(assign, nonatomic) BOOL showActive;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
-(void)dealloc;
-(void)layoutSubviews;
@end

