/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface UITextInputMode : XXUnknownSuperclass {
}
@property(readonly, retain, nonatomic) NSString* primaryLanguage;
+(id)currentInputMode;
@end

