/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL;

__attribute__((visibility("hidden")))
@interface UIWebClipIcon : XXUnknownSuperclass {
@private
	BOOL _precomposed;
	BOOL _siteWide;
	CGSize _bestSize;
	NSURL* _url;
}
@property(assign, nonatomic, getter=isPrecomposed) BOOL precomposed;
@property(assign, nonatomic, getter=isSiteWide) BOOL siteWide;
@property(assign, nonatomic) CGSize bestSize;
@property(retain, nonatomic) NSURL* url;
-(void)dealloc;
-(int)compare:(id)compare forVariant:(int)variant;
@end

