/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLRequest, UIWebBrowserView, UIScrollView, UICheckeredPatternView, UIWebViewWebViewDelegate;
@protocol UIWebViewDelegate;

__attribute__((visibility("hidden")))
@interface UIWebViewInternal : XXUnknownSuperclass {
@private
	UIScrollView* scroller;
	UIWebBrowserView* browserView;
	UICheckeredPatternView* checkeredPatternView;
	id<UIWebViewDelegate> delegate;
	unsigned scalesPageToFit : 1;
	unsigned isLoading : 1;
	unsigned drawsCheckeredPattern : 1;
	unsigned usedGeolocation : 1;
	unsigned webSelectionEnabled : 1;
	unsigned drawInWebThread : 1;
	NSURLRequest* request;
	int clickedAlertButtonIndex;
	UIWebViewWebViewDelegate* webViewDelegate;
}
@end

