/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AddressBookUI-Structs.h"

@class NSString;

@interface ABBannerView : XXUnknownSuperclass {
	NSString* _title;
	NSString* _value;
}
+(float)defaultHeight;
-(void)dealloc;
-(void)setTitle:(id)title;
-(id)title;
-(void)setValue:(id)value;
-(id)value;
-(void)drawRect:(CGRect)rect;
@end

