/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface ABFavoritesLookupChangeRecord : XXUnknownSuperclass {
	int identifier;
	int uid;
	NSString* value;
	NSString* name;
	NSString* label;
	NSString* abDatabaseUUID;
}
@end

