/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "AddressBookUI-Structs.h"
#import "ABMultiCellContentView_Rows.h"


@interface ABMultiCellContentView_Name : ABMultiCellContentView_Rows {
}
+(unsigned)rowsForPropertyGroup:(id)propertyGroup info:(id)info;
-(id)displayTextColor;
-(id)labelTextColorWhenEditing:(BOOL)editing;
-(id)keyboardSettingsForKey:(id)key;
-(void)reloadLabelFromModel;
-(void)reload;
-(void)reloadFromModel;
-(void)reloadFromModelIncludingRows:(BOOL)modelIncludingRows;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)entryField:(id)field valueDidChange:(id)value forKey:(id)key;
@end

