/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "AddressBookUI-Structs.h"
#import "ABDateFieldDelegate.h"
#import "ABMultiCellContentView.h"

@class ABDateField, NSDate;

@interface ABMultiCellContentView_Date : ABMultiCellContentView <ABDateFieldDelegate> {
@private
	ABDateField* _dateField;
}
@property(readonly, assign, nonatomic) NSDate* date;
+(CGSize)layoutSubviewsForView:(id)view usingSize:(CGSize)size propertyGroup:(id)group info:(id)info styleProvider:(id)provider whenEditing:(BOOL)editing;
-(void)dealloc;
-(void)setUpdateDelegate:(id)delegate;
-(void)reload;
-(void)reloadFromModel;
-(void)updateSubviewsForNewStateAnimated:(BOOL)newStateAnimated;
-(id)viewForFirstResponder;
-(void)setAbCellStyle:(int)style;
-(id)hitTestForTouches:(id)touches withEvent:(id)event;
-(void)dateFieldDateDidChange:(id)dateFieldDate;
-(BOOL)dateFieldShouldBeginEditing:(id)dateField;
-(BOOL)dateFieldShouldEndEditing:(id)dateField;
-(void)dateFieldDidEndEditing:(id)dateField;
-(void)dateFieldDidBeginEditing:(id)dateField;
-(BOOL)dateFieldShouldReturn:(id)dateField;
-(BOOL)dateFieldShouldClear:(id)dateField;
@end

