/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AddressBookUI-Structs.h"
#import "ABPersonTableActionDataSource.h"

@class NSMutableArray;

@interface ABPersonTableActionDataSource : XXUnknownSuperclass {
@private
	NSMutableArray* _topActions;
	NSMutableArray* _bottomActions;
	CFDictionaryRef _actionsByProperty;
	CFDictionaryRef _actionGroupingsByProperty;
	CFSetRef _hiddenActions;
}
-(void)dealloc;
-(CFDictionaryRef)actionsByProperty;
-(CFDictionaryRef)actionGroupingsByProperty;
-(id)topActions;
-(id)bottomActions;
-(id)addActionWithTitle:(id)title shortTitle:(id)title2 detailText:(id)text style:(int)style target:(id)target selector:(SEL)selector property:(int)property actionGrouping:(int)grouping ordering:(int)ordering;
-(BOOL)hasActionWithTarget:(id)target selector:(SEL)selector matchProperty:(BOOL)property property:(int)property4 inArray:(id)array outActions:(id*)actions outIndex:(int*)index;
-(BOOL)hasActionWithTarget:(id)target selector:(SEL)selector property:(int)property actionGrouping:(int)grouping ordering:(int)ordering outActions:(id*)actions outIndex:(int*)index;
-(void)removeActionWithTarget:(id)target selector:(SEL)selector forProperty:(int)property withActionGrouping:(int)actionGrouping ordering:(int)ordering;
-(void)removeAction:(id)action;
-(id)actionsForProperty:(int)property withActionGrouping:(int)actionGrouping;
-(id)newActionsForProperty:(int)property;
-(CFArrayRef)groupingsForProperty:(int)property;
-(int)groupingCountForProperty:(int)property;
-(int)actionCountForProperty:(int)property withActionGrouping:(int)actionGrouping;
-(id)actionForProperty:(int)property withActionGrouping:(int)actionGrouping atIndex:(int)index;
-(id)actionsForProperty:(int)property withActionGroupingAtIndex:(int)index;
-(int)actionCountForActionGrouping:(int)actionGrouping;
-(CFArrayRef)indexesOfActionsForProperty:(int)property withActionGrouping:(int)actionGrouping;
-(id)actionWithActionGrouping:(int)actionGrouping atIndex:(int)index;
@end

@interface ABPersonTableActionDataSource (TableViewDataSourceTracking)
-(BOOL)isActionHidden:(id)hidden;
-(void)setAction:(id)action hidden:(BOOL)hidden;
@end

