/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "AddressBookUI-Structs.h"
#import "ABPersonTableActionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIButton, UIView, ABPersonTableAction;
@protocol ABStyleProvider;

@interface ABPersonTableFooterView : XXUnknownSuperclass <ABPersonTableActionDelegate> {
@private
	BOOL _editing;
	ABPersonTableAction* _deleteAction;
	UIView* _deleteView;
	UIView* _accessoryView;
	UIButton* _attributionButton;
	id<ABStyleProvider> _styleProvider;
}
@property(assign, nonatomic, getter=isEditing) BOOL tableEditing;
@property(retain, nonatomic) id<ABStyleProvider> styleProvider;
@property(retain, nonatomic) UIView* accessoryView;
@property(readonly, assign, nonatomic, getter=isAttributionEnabled) BOOL attributionEnabled;
@property(readonly, assign, nonatomic) NSString* attribution;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(CGRect)deleteViewFrame;
-(CGRect)attributionFrame;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)setAttribution:(id)attribution enabled:(BOOL)enabled target:(id)target action:(SEL)action;
-(void)setDeleteActionWithTitle:(id)title target:(id)target selector:(SEL)selector animated:(BOOL)animated;
-(void)removeDeleteAction;
-(void)setEditing:(BOOL)editing;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)layoutSubviews;
@end

