/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AddressBookUI-Structs.h"

@class ABPersonViewControllerHelper;

@interface ABPersonTableView : XXUnknownSuperclass {
	ABPersonViewControllerHelper* _helper;
}
@property(assign, nonatomic) ABPersonViewControllerHelper* helper;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(BOOL)touchesShouldCancelInContentView:(id)touches;
-(void)setContentOffset:(CGPoint)offset;
@end

