/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AddressBookUI-Structs.h"

@class UILabel, NSString, UIColor, UIFont;

@interface ABUILabelWithPlaceholder : XXUnknownSuperclass {
@private
	UILabel* _label;
	BOOL _isPlaceholderActive;
	NSString* _placeholder;
	NSString* _actualText;
	UIColor* _actualTextColor;
}
@property(assign, nonatomic) UIFont* font;
@property(assign, nonatomic) CGSize shadowOffset;
@property(assign, nonatomic) UIColor* shadowColor;
@property(assign, nonatomic) UIColor* highlightedTextColor;
@property(retain, nonatomic) UIColor* textColor;
@property(copy, nonatomic) NSString* placeholder;
@property(copy, nonatomic) NSString* text;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_setActualText:(id)text;
-(void)_setActualTextColor:(id)color;
-(id)label;
-(float)labelLeftEdgeInset;
-(void)sizeToFit;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGRect)_labelFrameForBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
@end

