/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "AddressBookUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (ABCompare)
-(int)abCompare:(id)compare;
@end

@interface XXUnknownSuperclass (ABCompare)
-(int)abCompare:(id)compare;
@end

@interface XXUnknownSuperclass (PrivateModalViewControllerIntercept)
-(BOOL)ab_wantsToPresentModalViewControllerWithoutAnyHelp;
@end

@interface XXUnknownSuperclass (ABAdditions)
-(void*)newAddressBookRecord;
@end

@interface XXUnknownSuperclass (ABViewControllerType)
-(int)abViewControllerType;
@end

@interface XXUnknownSuperclass (ABKeyboardAdjuster)
-(void)ab_scrollToSelectionOfTextView:(id)textView animated:(BOOL)animated;
-(void)ab_scrollToSelectionOfTextView:(id)textView;
-(float)ab_verticalOverlapUsingKeyboardInfo:(id)info;
-(void)ab_adjustForAutomaticKeyboardInfo:(id)automaticKeyboardInfo lastAdjustment:(float*)adjustment;
@end

@interface XXUnknownSuperclass (ABKeyboardAdjuster)
-(void)ab_delayedScrollRespectingCaretOfActiveTextViewToCell:(id)cell atIndexPath:(id)indexPath atScrollPosition:(int)scrollPosition animated:(BOOL)animated;
-(void)ab_internalScrollToRowAtIndexPathRespectingCaretOfActiveTextView:(id)activeTextView atScrollPosition:(int)scrollPosition animated:(BOOL)animated;
-(void)ab_scrollToRowAtIndexPathRespectingCaretOfActiveTextView:(id)activeTextView atScrollPosition:(int)scrollPosition animated:(BOOL)animated;
@end

@interface XXUnknownSuperclass (ABUIBundle)
+(id)abImageNamed:(id)named;
@end

@interface XXUnknownSuperclass (ABDebugging)
-(void)abSetLayoutDebuggingColor:(id)color;
@end

@interface XXUnknownSuperclass (ABUIViewIndexPathDrillDown)
-(id)abIndexPathOfSubview:(id)subview;
-(id)abSubviewAtIndexPath:(id)indexPath;
@end

@interface XXUnknownSuperclass (ABPersonImageSharing)
+(id)sharedImageNamed:(id)named size:(CGSize)size drawUsingBlock:(id)block;
-(void)setCacheNameKey:(id)key;
-(id)cacheNameKey;
-(void)setCacheSizeKey:(id)key;
-(id)cacheSizeKey;
-(void)removeFromCache;
-(void)abpis_swizzleClass;
@end

@interface XXUnknownSuperclass (ABPadFaceTimeColors)
+(id)padFaceTimeBabyBlueColor;
+(id)padFaceTimeLightBabyBlueColor;
+(id)padFaceTimeShadowedGroupBackgroundColor;
+(id)padFaceTimeDarkSeparatorColor;
+(id)padFaceTimeLightSeparatorColor;
+(id)padFaceTimeSectionOutlineColor;
@end

@interface XXUnknownSuperclass (ABPadFaceTimeColors)
+(id)padFaceTimeBabyBlueColor;
+(id)padFaceTimeLightBabyBlueColor;
+(id)padFaceTimeShadowedGroupBackgroundColor;
+(id)padFaceTimeDarkSeparatorColor;
+(id)padFaceTimeLightSeparatorColor;
+(id)padFaceTimeSectionOutlineColor;
@end

@interface XXUnknownSuperclass (ABPadFaceTimeColors)
+(id)padFaceTimeBabyBlueColor;
+(id)padFaceTimeLightBabyBlueColor;
+(id)padFaceTimeShadowedGroupBackgroundColor;
+(id)padFaceTimeDarkSeparatorColor;
+(id)padFaceTimeLightSeparatorColor;
+(id)padFaceTimeSectionOutlineColor;
@end

