/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

#import "QLDisplayBundle.h"
#import "QLDelayedScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "QuickLook-Structs.h"
#import "UIGestureRecognizerDelegate.h"

@class UICheckeredPatternView, UIWebBrowserView, QLDelayedScrollView, UITapGestureRecognizer;

@interface QLWebViewDisplayBundle : QLDisplayBundle <UIWebViewDelegate, UIScrollViewDelegate, QLDelayedScrollViewDelegate, UIGestureRecognizerDelegate> {
	QLDelayedScrollView* _scrollView;
	UICheckeredPatternView* _checkeredView;
	UIWebBrowserView* _webView;
	UITapGestureRecognizer* _tapRecognizer;
	int _lastOrientation;
	CGPoint _savedOffset;
	unsigned _isHTMLContent : 1;
	unsigned _isPDFContent : 1;
	unsigned _isSpreadsheetContent : 1;
	unsigned _isPlainText : 1;
	unsigned _isRTFContent : 1;
	unsigned _isCSVContent : 1;
	unsigned _loadStarted : 1;
	float _navigationBarHeight;
}
+(BOOL)_isSpreadsheetType:(id)type;
+(BOOL)_isIWorkType:(id)type;
-(void)loadView;
-(id)_webView;
-(void)dealloc;
-(BOOL)shouldDisplayFullScreen;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(id)webLayerControlledByScroller:(id)scroller;
-(CGSize)minimumSizeOfWebLayerControlledByScroller:(id)webLayerControlledByScroller;
-(void)viewWillDisappear:(BOOL)view;
-(void)setNavigationBarHeight:(float)height animated:(BOOL)animated;
-(float)_pdfPageNumberLabelYOffset;
-(void)tearDownUI;
-(void)reloadUI;
-(void)loadWithHints:(id)hints;
-(void)cancelLoad;
-(id)webView:(id)view identifierForInitialRequest:(id)initialRequest fromDataSource:(id)dataSource;
-(void)_finishLoading;
-(void)webView:(id)view didFirstVisuallyNonEmptyLayoutInFrame:(id)frame;
-(void)webView:(id)view resource:(id)resource didFinishLoadingFromDataSource:(id)dataSource;
-(void)webView:(id)view resource:(id)resource didFailLoadingWithError:(id)error fromDataSource:(id)dataSource;
-(void)webView:(id)view decidePolicyForNewWindowAction:(id)newWindowAction request:(id)request newFrameName:(id)name decisionListener:(id)listener;
-(void)webView:(id)view decidePolicyForNavigationAction:(id)navigationAction request:(id)request frame:(id)frame decisionListener:(id)listener;
-(id)webView:(id)view resource:(id)resource willSendRequest:(id)request redirectResponse:(id)response fromDataSource:(id)dataSource;
-(void)_viewWasTapped:(id)tapped;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)view:(id)view didSetFrame:(CGRect)frame oldFrame:(CGRect)frame3 asResultOfZoom:(BOOL)zoom;
-(id)viewForZoomingInScrollView:(id)scrollView;
-(void)scrollViewWillBeginZooming:(id)scrollView withView:(id)view;
-(void)scrollViewDidZoom:(id)scrollView;
-(void)scrollViewDidEndZooming:(id)scrollView withView:(id)view atScale:(float)scale;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(BOOL)canPrint;
-(id)printPageRenderer;
-(id)pdfPreviewURL;
@end

