/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "NSObject.h"


@protocol CoreDAVAccountInfoProvider <NSObject>
-(id)scheme;
-(id)host;
-(int)port;
-(id)serverRoot;
-(id)user;
-(id)password;
-(id)identityPersist;
-(id)principalURL;
-(id)accountID;
-(id)serverComplianceClasses;
-(id)userAgentHeader;
-(void)promptUserForNewCoreDAVPasswordWithCompletionBlock:(id)completionBlock;
-(BOOL)handleTrustChallenge:(id)challenge;
-(BOOL)handleCertificateError:(id)error;
-(BOOL)shouldFailAllTasks;
@optional
-(id)mmeToken;
-(BOOL)handleTrustChallenge:(id)challenge withConnection:(id)connection;
-(BOOL)handleAuthenticateAgainstProtectionSpace:(id)space withConnection:(id)connection;
-(BOOL)handleAuthenticateAgainstProtectionSpace:(id)space;
-(BOOL)handleShouldUseCredentialStorage;
-(void)noteHomeSetOnDifferentHost:(id)host;
-(BOOL)shouldHandleHTTPCookiesForURL:(id)url;
-(BOOL)shouldTurnModalOnBadPassword;
-(void)noteSuccessfulRequestWithNumDownloadedElements:(int)numDownloadedElements;
-(void)noteFailedNetworkRequest;
-(void)noteFailedProtocolRequest;
-(void)noteTimeSpentInNetworking:(double)networking;
@end

