/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSDictionary, CoreDAVItem, NSMutableData;

@interface CoreDAVXMLElementGenerator : XXUnknownSuperclass {
	int _parsingState;
	SEL _parentElementSetter;
	CoreDAVItem* _element;
	CoreDAVItem* _parentElement;
	CoreDAVXMLElementGenerator* _parentGenerator;
	NSMutableData* _characters;
	NSMutableData* _cDATA;
	CoreDAVXMLElementGenerator* _currentlyParsingSubItem;
	NSDictionary* _cachedElementParseRules;
	BOOL _checkedElementValidityIfRootElement;
	BOOL _isUnrecognized;
	NSURL* _baseURL;
}
@property(assign) BOOL isUnrecognized;
@property(assign) int parsingState;
@property(assign) SEL parentElementSetter;
@property(retain) NSMutableData* characters;
@property(retain) NSMutableData* cDATA;
@property(retain) CoreDAVXMLElementGenerator* currentlyParsingSubItem;
@property(retain) CoreDAVItem* element;
@property(assign) CoreDAVXMLElementGenerator* parentGenerator;
@property(retain) NSDictionary* cachedElementParseRules;
@property(assign) BOOL checkedElementValidityIfRootElement;
@property(retain) NSURL* baseURL;
-(id)initWithParser:(id)parser baseURL:(id)url rootElementNameSpace:(id)space elementName:(id)name parseClass:(Class)aClass;
-(id)initWithParser:(id)parser parentGenerator:(id)generator parentElementSetter:(SEL)setter element:(id)element;
-(void)dealloc;
-(id)description;
-(BOOL)tracksRootElement;
-(void)notifyElement:(id)element ofAttributesFound:(id)attributesFound;
-(BOOL)isExpectedNameSpace:(id)space andElementName:(id)name;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)parser:(id)parser foundCharacters:(id)characters;
-(void)parser:(id)parser foundCDATA:(id)cdata;
-(void)parser:(id)parser parseErrorOccurred:(id)occurred;
-(void)parser:(id)parser validationErrorOccurred:(id)occurred;
-(void)parserDidEndDocument:(id)parser;
-(void)noteChildCascadingFailure;
-(void)resumeParsingWithParser:(id)parser;
@end

