/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface CoreDAVParseRule : XXUnknownSuperclass {
	int _minimumNumber;
	int _maximumNumber;
	NSString* _nameSpace;
	NSString* _elementName;
	Class _objectClass;
	SEL _setterMethod;
}
@property(readonly, assign) int minimumNumber;
@property(readonly, assign) int maximumNumber;
@property(readonly, assign) NSString* nameSpace;
@property(readonly, assign) NSString* elementName;
@property(readonly, assign) Class objectClass;
@property(readonly, assign) SEL setterMethod;
-(id)initWithMinimumNumber:(int)minimumNumber maximumNumber:(int)number nameSpace:(id)space elementName:(id)name objectClass:(Class)aClass setterMethod:(SEL)method;
-(void)dealloc;
-(id)description;
@end

