/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AVAsset, AVWeakReference, NSString, AVVideoComposition, NSMutableArray;

@interface AVAssetImageGeneratorInternal : XXUnknownSuperclass {
	AVWeakReference* weakReference;
	OpaqueFigAssetImageGenerator* generator;
	AVAsset* asset;
	BOOL appliesPreferredTrackTransform;
	CGSize maximumSize;
	NSString* apertureMode;
	XXStruct_pwHToB requestedTimeToleranceBefore;
	XXStruct_pwHToB requestedTimeToleranceAfter;
	NSMutableArray* requests;
	dispatch_queue_s* requestsQueue;
	int nextRequestID;
	AVVideoComposition* videoComposition;
	dispatch_queue_s* imageRequestQueue;
	int cancelledRequestIDThreshold;
}
@end

