/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AVFoundation-Structs.h"

@class AVAssetWriterInternal, NSError, NSURL, NSString, AVAssetWriterHelper, NSArray;

@interface AVAssetWriter : XXUnknownSuperclass {
@private
	AVAssetWriterInternal* _internal;
}
@property(retain, getter=_helper, setter=_setHelper:) AVAssetWriterHelper* helper;
@property(readonly, assign, nonatomic) NSArray* inputs;
@property(assign, nonatomic) BOOL shouldOptimizeForNetworkUse;
@property(copy, nonatomic) NSArray* metadata;
@property(readonly, assign) NSError* error;
@property(readonly, assign) int status;
@property(readonly, assign, nonatomic) NSArray* availableMediaTypes;
@property(readonly, copy, nonatomic) NSString* outputFileType;
@property(readonly, copy, nonatomic) NSURL* outputURL;
+(void)initialize;
+(id)assetWriterWithURL:(id)url fileType:(id)type error:(id*)error;
+(id)keyPathsForValuesAffectingStatus;
+(id)keyPathsForValuesAffectingError;
-(id)init;
-(id)initWithURL:(id)url fileType:(id)type error:(id*)error;
-(id)retain;
-(void)release;
-(void)dealloc;
-(void)finalize;
-(id)description;
-(XXStruct_pwHToB)movieFragmentInterval;
-(void)setMovieFragmentInterval:(XXStruct_pwHToB)interval;
-(int)movieTimeScale;
-(void)setMovieTimeScale:(int)scale;
-(BOOL)canApplyOutputSettings:(id)settings forMediaType:(id)mediaType;
-(BOOL)canAddInput:(id)input;
-(void)addInput:(id)input;
-(BOOL)startWriting;
-(void)startSessionAtSourceTime:(XXStruct_pwHToB)sourceTime;
-(void)endSessionAtSourceTime:(XXStruct_pwHToB)sourceTime;
-(void)cancelWriting;
-(BOOL)finishWriting;
-(void)_transitionToFailedStatusWithError:(id)error;
@end

