/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, AVWeakReference, AVAssetReaderOutputInternal, NSString;

@interface AVAssetReaderOutput : XXUnknownSuperclass {
@private
	AVAssetReaderOutputInternal* _internal;
}
@property(readonly, assign, nonatomic, getter=_trimsSampleDurations) BOOL trimsSampleDurations;
@property(readonly, assign, nonatomic, getter=_figAssetReaderExtractionOptions) NSDictionary* figAssetReaderExtractionOptions;
@property(assign, nonatomic, getter=_extractionID, setter=_setExtractionID:) int extractionID;
@property(readonly, assign, getter=_status) int status;
@property(readonly, assign, nonatomic, getter=_weakReferenceToAssetReader) AVWeakReference* weakReferenceToAssetReader;
@property(readonly, assign, nonatomic) NSString* mediaType;
+(void)initialize;
-(id)init;
-(id)retain;
-(void)release;
-(void)dealloc;
-(void)finalize;
-(id)_asset;
-(OpaqueFigAssetReader*)_figAssetReader;
-(void)_setFigAssetReader:(OpaqueFigAssetReader*)reader;
-(void)_attachToWeakReferenceToAssetReader:(id)assetReader;
-(BOOL)_prepareForReadingReturningError:(id*)readingReturningError;
-(BOOL)_enableTrackExtractionReturningError:(id*)error;
-(BOOL)_isFinished;
-(void)_markAsFinished;
-(void)_cancelReading;
-(opaqueCMSampleBuffer*)copyNextSampleBuffer;
-(void)_figAssetReaderSampleBufferDidBecomeAvailableForExtractionID:(int)_figAssetReaderSampleBuffer;
-(void)_figAssetReaderDecodeError;
-(void)_figAssetReaderFailed;
@end

