/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVAssetReaderOutput.h"

@class NSDictionary, NSArray, AVVideoComposition, AVAssetReaderVideoCompositionOutputInternal;

@interface AVAssetReaderVideoCompositionOutput : AVAssetReaderOutput {
@private
	AVAssetReaderVideoCompositionOutputInternal* _videoCompositionOutputInternal;
}
@property(copy, nonatomic) AVVideoComposition* videoComposition;
@property(readonly, assign, nonatomic) NSDictionary* videoSettings;
@property(readonly, assign, nonatomic) NSArray* videoTracks;
+(id)assetReaderVideoCompositionOutputWithVideoTracks:(id)videoTracks videoSettings:(id)settings;
-(id)init;
-(id)initWithVideoTracks:(id)videoTracks videoSettings:(id)settings;
-(void)dealloc;
-(void)finalize;
-(id)description;
-(id)mediaType;
-(id)_asset;
-(BOOL)_enableTrackExtractionReturningError:(id*)error;
@end

