/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVAssetWriterInputHelper.h"
#import "AVFoundation-Structs.h"


@interface AVAssetWriterInputUnknownHelper : AVAssetWriterInputHelper {
}
-(id)initWithConfigurationState:(id)configurationState;
-(id)initWithMediaType:(id)mediaType outputSettings:(id)settings;
-(int)status;
-(void)setTransform:(CGAffineTransform)transform;
-(void)setMetadata:(id)metadata;
-(void)setMediaTimeScale:(int)scale;
-(void)setExpectsMediaDataInRealTime:(BOOL)realTime;
-(void)setSourcePixelBufferAttributes:(id)attributes;
@end

