/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol AVAudioSessionDelegate;

@interface AVAudioSession : XXUnknownSuperclass {
@private
	void* _impl;
}
@property(assign) id<AVAudioSessionDelegate> delegate;
@property(readonly, assign) NSString* category;
@property(readonly, assign) BOOL inputIsAvailable;
@property(readonly, assign) double currentHardwareSampleRate;
@property(readonly, assign) double preferredHardwareSampleRate;
@property(readonly, assign) double preferredIOBufferDuration;
@property(readonly, assign) int currentHardwareInputNumberOfChannels;
@property(readonly, assign) int currentHardwareOutputNumberOfChannels;
+(id)sharedInstance;
-(BOOL)setCategory:(id)category error:(id*)error;
-(BOOL)setActive:(BOOL)active error:(id*)error;
-(BOOL)setActive:(BOOL)active withFlags:(int)flags error:(id*)error;
-(BOOL)setPreferredHardwareSampleRate:(double)rate error:(id*)error;
-(BOOL)setPreferredIOBufferDuration:(double)duration error:(id*)error;
-(void)privateInputIsAvailableChanged:(id)changed;
-(void)privateBeginInterruption;
-(void)privateEndInterruption;
-(void)privateEndInterruptionWithFlags:(id)flags;
@end

