/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import "AVAssetInspectorLoader.h"


@interface AVFormatReaderInspectorLoader : AVAssetInspectorLoader {
	OpaqueFigFormatReaderLoader* _formatReaderLoader;
	BOOL _prefersAccurateTiming;
}
+(void)initialize;
+(id)_avfValidationPlist;
+(id)formatReaderInspectorLoaderWithURL:(id)url options:(id)options;
-(id)initWithURL:(id)url options:(id)options;
-(void)_addFormatReaderLoaderNotifications;
-(void)_removeFormatReaderLoaderNotifications;
-(void)dealloc;
-(void)finalize;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)assetInspector;
-(OpaqueFigFormatReaderLoader*)_formatReaderLoader;
-(OpaqueFigFormatReader*)_copyFormatReaderFromFigObjectWithFigErrorCode:(int*)figErrorCode;
-(BOOL)_inspectionRequiresAFormatReader;
-(BOOL)_providesAccurateTiming;
-(id)_dictionaryOfSpecialGettersForKeyValueStatus;
-(id)_formatReaderLoaderProductsForKeys:(id)keys;
-(id)_loadValuesUsingDefaultLoadingMethodWhileMutexLockedForKeys:(id)keys;
-(void)cancelLoading;
-(void)_loadDurationSynchronously;
@end

