/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import "AVAsynchronousKeyValueLoading.h"
#import "NSMutableCopying.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "AVMetadataItem.h"

@class NSNumber, NSData, NSLocale, NSDate, NSString, AVMetadataItemInternal, NSDictionary;
@protocol NSObject;

@interface AVMetadataItem : XXUnknownSuperclass <AVAsynchronousKeyValueLoading, NSCopying, NSMutableCopying> {
	AVMetadataItemInternal* _priv;
}
@property(readonly, copy) NSDictionary* extraAttributes;
@property(readonly, copy) id<NSCopying, NSObject> value;
@property(readonly, assign) XXStruct_pwHToB duration;
@property(readonly, assign) XXStruct_pwHToB time;
@property(readonly, copy) NSLocale* locale;
@property(readonly, copy) NSString* keySpace;
@property(readonly, copy) NSString* commonKey;
@property(readonly, copy) id<NSCopying, NSObject> key;
+(id)metadataItemsFromArray:(id)array withLocale:(id)locale;
+(id)metadataItemsFromArray:(id)array withKey:(id)key keySpace:(id)space;
+(id)_figMetadataPropertyFromMetadataItems:(id)metadataItems;
-(id)init;
-(id)_initWithReader:(OpaqueFigMetadataReader*)reader itemIndex:(long)index;
-(id)_initWithFigMetadataDictionary:(id)figMetadataDictionary;
-(void)dealloc;
-(void)finalize;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)_figMetadataDictionary;
-(id)_figMetadataFormat;
-(int)statusOfValueForKey:(id)key error:(id*)error;
-(void)loadValuesAsynchronouslyForKeys:(id)keys completionHandler:(id)handler;
-(void)cancelLoading;
@end

@interface AVMetadataItem (AVMetadataItemTypeCoercion)
@property(readonly, assign) NSData* dataValue;
@property(readonly, assign) NSDate* dateValue;
@property(readonly, assign) NSNumber* numberValue;
@property(readonly, assign) NSString* stringValue;
-(CGImageRef)imageValue;
@end

@interface AVMetadataItem (AVMetadataItem_Local)
-(void)_makeValueReady;
-(void)_makePropertiesReady;
-(void)_updateCommonKey;
-(void)_extractPropertiesFromDictionary:(id)dictionary;
-(id)_keyAsString;
@end

