/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AVFoundation-Structs.h"

@class AVPlayerItem, NSMutableDictionary, NSArray, CALayer, AVPropertyStorage, NSMutableSet, NSError, AVWeakReference;

@interface AVPlayerInternal : XXUnknownSuperclass {
	AVWeakReference* weakReference;
	OpaqueFigPlayer* figPlayer;
	AVPropertyStorage* propertyStorage;
	NSMutableDictionary* pendingFigPlayerProperties;
	AVPlayerItem* currentItem;
	AVPlayerItem* lastItem;
	NSMutableSet* items;
	CALayer* caLayer;
	int status;
	NSError* error;
	dispatch_queue_s* stateDispatchQueue;
	NSArray* displaysUsedForPlayback;
	int figPlayerType;
	BOOL waitsUntilItemsAreReadyForInspectionBeforeEnqueuingIntoFigPlayer;
	BOOL needsToCreateFigPlayer;
	BOOL logPerformanceData;
}
@end

