/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURL, NSArray, AVAssetInspectorLoader;

@interface AVURLAssetInternal : XXUnknownSuperclass {
	AVAssetInspectorLoader* loader;
	NSURL* URL;
	NSArray* tracks;
	NSArray* chapterGroupInfo;
	NSString* anchorChapterType;
}
@end

