/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import "NSCoding.h"
#import "MPEffectContainer.h"
#import "NSCopying.h"
#import "MPAudioSupport.h"
#import "MPFilterSupport.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MPAudioPlaylist, MPLayer, NSMutableArray, NSMutableDictionary, MPEffectContainerInternal, MCContainerParallelizer, MPTransition, MCPlug;

@interface MPEffectContainer : XXUnknownSuperclass <NSCoding, NSCopying, MPFilterSupport, MPAudioSupport> {
@private
	MCPlug* _containerPlug;
	MCContainerParallelizer* _containerParallelizer;
	NSMutableArray* _effects;
	NSMutableArray* _filters;
	NSMutableDictionary* _attributes;
	MPTransition* _transition;
	MPLayer* _parentLayer;
	MPEffectContainerInternal* _internal;
	MPAudioPlaylist* _audioPlaylist;
	BOOL _transitionDisconnected;
}
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
+(id)effectContainer;
-(id)init;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(void)finialize;
-(void)dealloc;
-(id)effects;
-(void)addEffect:(id)effect;
-(void)addEffects:(id)effects;
-(void)insertEffects:(id)effects atIndex:(int)index;
-(void)removeEffectsAtIndices:(id)indices;
-(void)removeAllEffects;
-(void)moveEffectsFromIndices:(id)indices toIndex:(int)index;
-(id)transition;
-(void)setTransition:(id)transition;
-(id)filters;
-(void)addFilter:(id)filter;
-(void)addFilters:(id)filters;
-(void)insertFilters:(id)filters atIndex:(int)index;
-(void)removeFiltersAtIndices:(id)indices;
-(void)removeAllFilters;
-(void)moveFiltersFromIndices:(id)indices toIndex:(int)index;
-(id)backgroundColor;
-(void)setBackgroundColor:(id)color;
-(id)audioPlaylist;
-(void)setAudioPlaylist:(id)playlist;
-(int)index;
-(id)parentLayer;
-(double)startTime;
-(double)duration;
-(void)setDuration:(double)duration;
-(double)beginingTransitionTime;
-(double)introTransitionDuration;
-(double)outroTransitionDuration;
-(double)endTransitionTime;
@end

@interface MPEffectContainer (AppleScript)
-(int)countOfEffects;
-(id)objectInEffectsAtIndex:(int)index;
-(void)insertObject:(id)object inEffectsAtIndex:(int)index;
-(void)removeObjectFromEffectsAtIndex:(int)index;
-(void)replaceObjectInEffectsAtIndex:(int)index withObject:(id)object;
-(int)countOfFilters;
-(id)objectInFiltersAtIndex:(int)index;
-(void)insertObject:(id)object inFiltersAtIndex:(int)index;
-(void)removeObjectFromFiltersAtIndex:(int)index;
-(void)replaceObjectInFiltersAtIndex:(int)index withObject:(id)object;
-(id)scriptingTransition;
-(void)setScriptingTransition:(id)transition;
@end

@interface MPEffectContainer (Internal)
-(void)copyStruct:(id)aStruct;
-(void)copyEffects:(id)effects;
-(void)copyFilters:(id)filters;
-(void)copyTransition:(id)transition;
-(void)copyAudioPlaylist:(id)playlist;
-(void)cleanup;
-(void)setContainerPlug:(id)plug;
-(void)setContainerParallelizer:(id)parallelizer;
-(void)setContainerEffect:(id)effect;
-(void)setParentLayer:(id)layer;
-(void)setStartTime:(double)time;
-(BOOL)shouldBeParallelizer;
-(void)convertFromParallelizerToEffectContainer;
-(void)convertFromEffectContainerToParallelizer;
-(void)calculateDurationToSmallest:(BOOL)smallest;
-(void)recreateWithContainerPlug:(id)containerPlug;
-(void)setUserInfoAttribute:(id)attribute forKey:(id)key;
-(id)userInfoAttributeForKey:(id)key;
-(void)setCGBackgroundColor:(CGColorRef)color;
@end

@interface MPEffectContainer (Private)
-(id)container;
-(id)containerPlug;
-(id)containerParallelizer;
-(void)dump;
-(double)findMinDuration;
-(void)disconnectTransition;
-(void)reconnectTransition;
-(BOOL)isTransitionConnected;
-(id)fullDebugLog;
@end

