/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import "NSCoding.h"
#import "NSCopying.h"
#import "MPFilter.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MPAnimationSupport.h"

@class NSMutableDictionary, MPFilterInternal, MCFilter, NSObject;
@protocol MPFilterSupport;

@interface MPFilter : XXUnknownSuperclass <NSCoding, NSCopying, MPAnimationSupport> {
@private
	NSMutableDictionary* _attributes;
	NSMutableDictionary* _animationPaths;
	MCFilter* _filter;
	NSObject<MPFilterSupport>* _parent;
	MPFilterInternal* _internal;
}
+(id)filterWithFilterID:(id)filterID;
-(id)initWithFilterID:(id)filterID;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)finalize;
-(void)dealloc;
-(id)filterID;
-(void)setFilterID:(id)anId;
-(id)presetID;
-(void)setPresetID:(id)anId;
-(id)filterAttributes;
-(id)filterAttributeForKey:(id)key;
-(void)setFilterAttribute:(id)attribute forKey:(id)key;
-(id)animationPaths;
-(id)animationPathForKey:(id)key;
-(void)setAnimationPath:(id)path forKey:(id)key;
-(void)removeAnimationPathForKey:(id)key;
-(int)index;
-(id)parent;
@end

@interface MPFilter (AppleScript)
@end

@interface MPFilter (Internal)
-(void)copyStruct:(id)aStruct;
-(void)copyAnimationPaths:(id)paths;
-(void)setFilter:(id)filter;
-(void)setParent:(id)parent;
-(id)parentDocument;
-(void)recreateWithFilter:(id)filter;
@end

@interface MPFilter (Private)
-(id)filter;
-(void)dump;
-(id)fullDebugLog;
-(void)setDefaults;
-(id)convertMPAttributeToMCAttribute:(id)mcattribute withKey:(id)key;
-(id)convertMCAttributeToMPAttribute:(id)mpattribute withKey:(id)key;
@end

