/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MPKeyframeInternal : XXUnknownSuperclass {
	double time;
	unsigned offset;
	double preControl;
	double postControl;
}
@property(assign, nonatomic) double time;
@property(assign, nonatomic) unsigned offset;
@property(assign, nonatomic) double preControl;
@property(assign, nonatomic) double postControl;
@end

