/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import "MRLayer.h"

@class MCContainerEffect, NSMutableArray;

@interface MRLayerEffect : MRLayer {
	MCContainerEffect* mContainer;
	NSMutableArray* mImageProviders;
	BOOL mNeedsToPreloadImageProviders;
	BOOL mIsPreloaded;
	BOOL mNeedsToResumeRenderer;
	BOOL mIsPartOfWarmingUp;
}
@property(readonly, assign) BOOL isPreloaded;
@property(assign) BOOL needsToResumeRenderer;
@property(assign) BOOL isPartOfWarmingUp;
+(id)effectLayerWithPlug:(id)plug andParameters:(id)parameters inSuperlayer:(id)superlayer;
-(id)initWithPlug:(id)plug andParameters:(id)parameters inSuperlayer:(id)superlayer;
-(void)cleanup;
-(void)updateSize;
-(void)renderAtTime:(double)time;
-(const XXStruct_ywZ0fB*)renderedImageAtTime:(double)time;
-(id)patchworkAtBeginning;
-(id)patchworkAtEnd;
-(void)preactivate;
-(void)activate;
-(void)depreactivate;
-(void)contextChanged;
-(double)stillDurationFromTime:(double)time;
-(BOOL)changedBetweenTime:(double)time andTime:(double)time2 remainingStillDuration:(double)duration;
-(void)_fillInTiming:(XXStruct_VSauOA*)timing forTime:(double)time;
-(void)_setTargetSizeOfImageProviders;
-(void)_preloadCompleted;
@end

