/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MRRenderer, NSDictionary, MCPlug, MCPlugParallel, MCPlugSerial;

@interface MRLayer : XXUnknownSuperclass {
	MRLayer* mSuperlayer;
	MCPlug* mPlug;
	MCPlugSerial* mPlugAsSerial;
	MCPlugParallel* mPlugAsParallel;
	BOOL mIsPreactivated;
	BOOL mIsActivated;
	double mTimeIn;
	CGSize mSize;
	MRRenderer* mRenderer;
	NSDictionary* mParameters;
}
@property(readonly, assign) MRLayer* superlayer;
@property(readonly, assign) MCPlug* plug;
@property(readonly, assign) MCPlugParallel* plugAsParallel;
@property(readonly, assign) MCPlugSerial* plugAsSerial;
@property(readonly, assign) BOOL isPreactivated;
@property(readonly, assign) BOOL isActivated;
@property(assign) double timeIn;
@property(readonly, assign) CGSize size;
-(id)initWithPlug:(id)plug andParameters:(id)parameters inSuperlayer:(id)superlayer;
-(void)dealloc;
-(void)cleanup;
-(void)updateSize;
-(id)sublayerWithPlug:(id)plug;
-(void)renderAtTime:(double)time;
-(const XXStruct_ywZ0fB*)renderedImageAtTime:(double)time;
-(id)patchworkAtBeginning;
-(id)patchworkAtEnd;
-(void)preactivate;
-(void)activate;
-(void)deactivate;
-(void)depreactivate;
-(void)contextChanged;
-(double)stillDurationFromTime:(double)time;
-(BOOL)changedBetweenTime:(double)time andTime:(double)time2 remainingStillDuration:(double)duration;
@end

