/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"


@protocol MRTransition
@property(assign) float pixelUnit;
-(id)initWithAttributes:(id)attributes;
-(void)renderAtTime:(double)time andSize:(CGSize)size withSourcePatchwork:(id)sourcePatchwork andTargetPatchwork:(id)patchwork;
@optional
-(void)precompute;
-(void)precomputeWithImage:(const XXStruct_ywZ0fB*)image isTargetImage:(BOOL)image2;
@end

