/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import "iLifeSlideshow-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface MRUtilities : XXUnknownSuperclass {
}
+(void)setImage:(const XXStruct_ywZ0fB*)image onTextureUnit:(unsigned)unit withReferenceAspectRatio:(float)referenceAspectRatio;
+(void)setImage:(const XXStruct_ywZ0fB*)image onTextureUnit:(unsigned)unit withReferenceAspectRatio:(float)referenceAspectRatio state:(float [16])state;
+(void)unsetImage:(const XXStruct_ywZ0fB*)image onTextureUnit:(unsigned)unit;
+(void)unsetImage:(const XXStruct_ywZ0fB*)image onTextureUnit:(unsigned)unit state:(float [16])state;
+(double)transformTime:(double)time forAnimationPath:(id)animationPath;
+(float)valueForScalarAnimationPath:(id)scalarAnimationPath atTime:(double)time defaultsTo:(float)to previousKeyValue:(float*)value nextKeyValue:(float*)value5;
+(CGPoint)valueForPointAnimationPath:(id)pointAnimationPath atTime:(double)time defaultsTo:(CGPoint)to previousKeyPoint:(CGPoint*)point nextKeyPoint:(CGPoint*)point5;
@end

